%%% % DO NOT EDIT: this file was generated by 'just codegen'
%%% % @generated SignedSource<<a3b3ebf564c3f74b44783a120366e5b5>>
%%%-----------------------------------------------------------------------------
%%% Copyright (c) Meta Platforms, Inc. and affiliates.
%%% Copyright (c) WhatsApp LLC
%%%
%%% This source code is licensed under the MIT license found in the
%%% LICENSE.md file in the root directory of this source tree.
%%%
%%% @author Andrew Bennett <potatosaladx@meta.com>
%%% @copyright (c) Meta Platforms, Inc. and affiliates.
%%% Created :  04 Mar 2025 by Andrew Bennett <potatosaladx@meta.com>
%%%-----------------------------------------------------------------------------
%%% % @format
-module(markdown_debug_types).
-moduledoc """
Debugging utilities for types.
""".
-compile(warn_missing_spec_all).
-oncall("whatsapp_clr").

-include_lib("markdown/include/markdown_debug_types.hrl").
-include_lib("markdown/include/markdown_html.hrl").
-include_lib("markdown/include/markdown_mdast.hrl").
-include_lib("markdown/include/markdown_parser.hrl").
-include_lib("markdown/include/markdown_unist.hrl").
-include_lib("markdown/include/markdown_vec.hrl").

%% API
-export([
    is_record/2,
    is_rust_enum/1,
    record_fields/1,
    record_rust_name/1,
    record_size/1
]).

%% Types
-type record_name() ::
    array
    | markdown_attempt
    | markdown_construct_options
    | markdown_container
    | markdown_edit_map
    | markdown_event
    | markdown_event_link
    | markdown_html_media
    | markdown_index
    | markdown_indices
    | markdown_label_start
    | markdown_label
    | markdown_list_item
    | markdown_location
    | markdown_mdast_blockquote
    | markdown_mdast_emphasis
    | markdown_mdast_node
    | markdown_mdast_paragraph
    | markdown_mdast_reference
    | markdown_mdast_root
    | markdown_mdast_text
    | markdown_mdast_thematic_break
    | markdown_message
    | markdown_parse_options
    | markdown_parse_state
    | markdown_place
    | markdown_point
    | markdown_position
    | markdown_progress
    | markdown_sequence
    | markdown_slice
    | markdown_space_or_tab_options
    | markdown_subresult
    | markdown_tokenize_state
    | markdown_tokenizer
    | markdown_unist_point
    | markdown_unist_position
    | markdown_vec.
-type rust_enum() ::
    markdown_mdast_node.

-export_type([
    record_name/0,
    rust_enum/0
]).

%%%=============================================================================
%%% API functions
%%%=============================================================================

-spec is_record(RecordName | OtherRecordName, RecordSize) -> boolean() when
    RecordName :: record_name(), OtherRecordName :: atom(), RecordSize :: non_neg_integer().
is_record(array, 4) ->
    true;
is_record(RecordName, RecordSize) when
    ?is_markdown_record_name(RecordName) andalso is_integer(RecordSize) andalso RecordSize >= 0
->
    case record_size(RecordName) of
        RecordSize ->
            true;
        _OtherRecordSize ->
            false
    end;
is_record(_OtherRecordName, _RecordSize) ->
    false.

-spec is_rust_enum(RustEnum | OtherRecordName) -> boolean() when RustEnum :: rust_enum(), OtherRecordName :: atom().
is_rust_enum(markdown_mdast_node) -> true;
is_rust_enum(_OtherRecordName) -> false.

-spec record_fields(RecordName) -> Fields when RecordName :: record_name(), Fields :: [Field], Field :: atom().
record_fields(array) -> [size, max, default, elements];
record_fields(markdown_attempt) -> record_info(fields, markdown_attempt);
record_fields(markdown_construct_options) -> record_info(fields, markdown_construct_options);
record_fields(markdown_container) -> record_info(fields, markdown_container);
record_fields(markdown_edit_map) -> record_info(fields, markdown_edit_map);
record_fields(markdown_event) -> record_info(fields, markdown_event);
record_fields(markdown_event_link) -> record_info(fields, markdown_event_link);
record_fields(markdown_html_media) -> record_info(fields, markdown_html_media);
record_fields(markdown_index) -> record_info(fields, markdown_index);
record_fields(markdown_indices) -> record_info(fields, markdown_indices);
record_fields(markdown_label_start) -> record_info(fields, markdown_label_start);
record_fields(markdown_label) -> record_info(fields, markdown_label);
record_fields(markdown_list_item) -> record_info(fields, markdown_list_item);
record_fields(markdown_location) -> record_info(fields, markdown_location);
record_fields(markdown_mdast_blockquote) -> record_info(fields, markdown_mdast_blockquote);
record_fields(markdown_mdast_emphasis) -> record_info(fields, markdown_mdast_emphasis);
record_fields(markdown_mdast_node) -> record_info(fields, markdown_mdast_node);
record_fields(markdown_mdast_paragraph) -> record_info(fields, markdown_mdast_paragraph);
record_fields(markdown_mdast_reference) -> record_info(fields, markdown_mdast_reference);
record_fields(markdown_mdast_root) -> record_info(fields, markdown_mdast_root);
record_fields(markdown_mdast_text) -> record_info(fields, markdown_mdast_text);
record_fields(markdown_mdast_thematic_break) -> record_info(fields, markdown_mdast_thematic_break);
record_fields(markdown_message) -> record_info(fields, markdown_message);
record_fields(markdown_parse_options) -> record_info(fields, markdown_parse_options);
record_fields(markdown_parse_state) -> record_info(fields, markdown_parse_state);
record_fields(markdown_place) -> record_info(fields, markdown_place);
record_fields(markdown_point) -> record_info(fields, markdown_point);
record_fields(markdown_position) -> record_info(fields, markdown_position);
record_fields(markdown_progress) -> record_info(fields, markdown_progress);
record_fields(markdown_sequence) -> record_info(fields, markdown_sequence);
record_fields(markdown_slice) -> record_info(fields, markdown_slice);
record_fields(markdown_space_or_tab_options) -> record_info(fields, markdown_space_or_tab_options);
record_fields(markdown_subresult) -> record_info(fields, markdown_subresult);
record_fields(markdown_tokenize_state) -> record_info(fields, markdown_tokenize_state);
record_fields(markdown_tokenizer) -> record_info(fields, markdown_tokenizer);
record_fields(markdown_unist_point) -> record_info(fields, markdown_unist_point);
record_fields(markdown_unist_position) -> record_info(fields, markdown_unist_position);
record_fields(markdown_vec) -> record_info(fields, markdown_vec).

-spec record_rust_name(RecordName) -> RustName when RecordName :: record_name(), RustName :: binary().
record_rust_name(array) -> <<"Array">>;
record_rust_name(markdown_attempt) -> <<"Attempt">>;
record_rust_name(markdown_construct_options) -> <<"Constructs">>;
record_rust_name(markdown_container) -> <<"ContainerState">>;
record_rust_name(markdown_edit_map) -> <<"EditMap">>;
record_rust_name(markdown_event) -> <<"Event">>;
record_rust_name(markdown_event_link) -> <<"Link">>;
record_rust_name(markdown_html_media) -> <<"Media">>;
record_rust_name(markdown_index) -> <<"Index">>;
record_rust_name(markdown_indices) -> <<"Indices">>;
record_rust_name(markdown_label_start) -> <<"LabelStart">>;
record_rust_name(markdown_label) -> <<"Label">>;
record_rust_name(markdown_list_item) -> <<"ListItem">>;
record_rust_name(markdown_location) -> <<"Location">>;
record_rust_name(markdown_mdast_blockquote) -> <<"Blockquote">>;
record_rust_name(markdown_mdast_emphasis) -> <<"Emphasis">>;
record_rust_name(markdown_mdast_node) -> <<"Node">>;
record_rust_name(markdown_mdast_paragraph) -> <<"Paragraph">>;
record_rust_name(markdown_mdast_reference) -> <<"Reference">>;
record_rust_name(markdown_mdast_root) -> <<"Root">>;
record_rust_name(markdown_mdast_text) -> <<"Text">>;
record_rust_name(markdown_mdast_thematic_break) -> <<"ThematicBreak">>;
record_rust_name(markdown_message) -> <<"Message">>;
record_rust_name(markdown_parse_options) -> <<"ParseOptions">>;
record_rust_name(markdown_parse_state) -> <<"ParseState">>;
record_rust_name(markdown_place) -> <<"Place">>;
record_rust_name(markdown_point) -> <<"Point">>;
record_rust_name(markdown_position) -> <<"Position">>;
record_rust_name(markdown_progress) -> <<"Progress">>;
record_rust_name(markdown_sequence) -> <<"Sequence">>;
record_rust_name(markdown_slice) -> <<"Slice">>;
record_rust_name(markdown_space_or_tab_options) -> <<"SpaceOrTabOptions">>;
record_rust_name(markdown_subresult) -> <<"Subresult">>;
record_rust_name(markdown_tokenize_state) -> <<"TokenizeState">>;
record_rust_name(markdown_tokenizer) -> <<"Tokenizer">>;
record_rust_name(markdown_unist_point) -> <<"Point">>;
record_rust_name(markdown_unist_position) -> <<"Position">>;
record_rust_name(markdown_vec) -> <<"Vec">>.

-spec record_size(RecordName) -> RecordSize when RecordName :: record_name(), RecordSize :: non_neg_integer().
record_size(array) -> 4;
record_size(markdown_attempt) -> record_info(size, markdown_attempt) - 1;
record_size(markdown_construct_options) -> record_info(size, markdown_construct_options) - 1;
record_size(markdown_container) -> record_info(size, markdown_container) - 1;
record_size(markdown_edit_map) -> record_info(size, markdown_edit_map) - 1;
record_size(markdown_event) -> record_info(size, markdown_event) - 1;
record_size(markdown_event_link) -> record_info(size, markdown_event_link) - 1;
record_size(markdown_html_media) -> record_info(size, markdown_html_media) - 1;
record_size(markdown_index) -> record_info(size, markdown_index) - 1;
record_size(markdown_indices) -> record_info(size, markdown_indices) - 1;
record_size(markdown_label_start) -> record_info(size, markdown_label_start) - 1;
record_size(markdown_label) -> record_info(size, markdown_label) - 1;
record_size(markdown_list_item) -> record_info(size, markdown_list_item) - 1;
record_size(markdown_location) -> record_info(size, markdown_location) - 1;
record_size(markdown_mdast_blockquote) -> record_info(size, markdown_mdast_blockquote) - 1;
record_size(markdown_mdast_emphasis) -> record_info(size, markdown_mdast_emphasis) - 1;
record_size(markdown_mdast_node) -> record_info(size, markdown_mdast_node) - 1;
record_size(markdown_mdast_paragraph) -> record_info(size, markdown_mdast_paragraph) - 1;
record_size(markdown_mdast_reference) -> record_info(size, markdown_mdast_reference) - 1;
record_size(markdown_mdast_root) -> record_info(size, markdown_mdast_root) - 1;
record_size(markdown_mdast_text) -> record_info(size, markdown_mdast_text) - 1;
record_size(markdown_mdast_thematic_break) -> record_info(size, markdown_mdast_thematic_break) - 1;
record_size(markdown_message) -> record_info(size, markdown_message) - 1;
record_size(markdown_parse_options) -> record_info(size, markdown_parse_options) - 1;
record_size(markdown_parse_state) -> record_info(size, markdown_parse_state) - 1;
record_size(markdown_place) -> record_info(size, markdown_place) - 1;
record_size(markdown_point) -> record_info(size, markdown_point) - 1;
record_size(markdown_position) -> record_info(size, markdown_position) - 1;
record_size(markdown_progress) -> record_info(size, markdown_progress) - 1;
record_size(markdown_sequence) -> record_info(size, markdown_sequence) - 1;
record_size(markdown_slice) -> record_info(size, markdown_slice) - 1;
record_size(markdown_space_or_tab_options) -> record_info(size, markdown_space_or_tab_options) - 1;
record_size(markdown_subresult) -> record_info(size, markdown_subresult) - 1;
record_size(markdown_tokenize_state) -> record_info(size, markdown_tokenize_state) - 1;
record_size(markdown_tokenizer) -> record_info(size, markdown_tokenizer) - 1;
record_size(markdown_unist_point) -> record_info(size, markdown_unist_point) - 1;
record_size(markdown_unist_position) -> record_info(size, markdown_unist_position) - 1;
record_size(markdown_vec) -> record_info(size, markdown_vec) - 1.
