%%% % DO NOT EDIT: this file was generated by 'just codegen'
%%% % @generated <<SignedSource::*O*zOeWoEQle#+L!plEphiEmie@IsG>>
%%%-----------------------------------------------------------------------------
%%% Copyright (c) Meta Platforms, Inc. and affiliates.
%%% Copyright (c) WhatsApp LLC
%%%
%%% This source code is licensed under the MIT license found in the
%%% LICENSE.md file in the root directory of this source tree.
%%%
%%% @author Andrew Bennett <potatosaladx@meta.com>
%%% @copyright (c) Meta Platforms, Inc. and affiliates.
%%% @doc
%%%
%%% @end
%%% Created :  04 Mar 2025 by Andrew Bennett <potatosaladx@meta.com>
%%%-----------------------------------------------------------------------------
%%% % @format
%% @oncall whatsapp_clr
-ifndef(MARKDOWN_DEBUG_TYPES_HRL).
-define(MARKDOWN_DEBUG_TYPES_HRL, 1).

%% Macros
-define(is_markdown_record_name(X),
    ((X) =:= array orelse
        (X) =:= markdown_attempt orelse
        (X) =:= markdown_construct_options orelse
        (X) =:= markdown_container orelse
        (X) =:= markdown_edit_map orelse
        (X) =:= markdown_event orelse
        (X) =:= markdown_event_link orelse
        (X) =:= markdown_html_media orelse
        (X) =:= markdown_index orelse
        (X) =:= markdown_indices orelse
        (X) =:= markdown_label_start orelse
        (X) =:= markdown_label orelse
        (X) =:= markdown_list_item orelse
        (X) =:= markdown_location orelse
        (X) =:= markdown_mdast_blockquote orelse
        (X) =:= markdown_mdast_emphasis orelse
        (X) =:= markdown_mdast_footnote_definition orelse
        (X) =:= markdown_mdast_footnote_reference orelse
        (X) =:= markdown_mdast_node orelse
        (X) =:= markdown_mdast_paragraph orelse
        (X) =:= markdown_mdast_reference orelse
        (X) =:= markdown_mdast_root orelse
        (X) =:= markdown_mdast_text orelse
        (X) =:= markdown_mdast_thematic_break orelse
        (X) =:= markdown_message orelse
        (X) =:= markdown_parse_options orelse
        (X) =:= markdown_parse_state orelse
        (X) =:= markdown_place orelse
        (X) =:= markdown_point orelse
        (X) =:= markdown_position orelse
        (X) =:= markdown_progress orelse
        (X) =:= markdown_sequence orelse
        (X) =:= markdown_slice orelse
        (X) =:= markdown_space_or_tab_options orelse
        (X) =:= markdown_subresult orelse
        (X) =:= markdown_tokenize_state orelse
        (X) =:= markdown_tokenizer orelse
        (X) =:= markdown_unist_point orelse
        (X) =:= markdown_unist_position orelse
        (X) =:= markdown_vec)
).

-endif.
