%%% % DO NOT EDIT: this file was generated by 'just codegen'
%%% % @generated SignedSource<<359dfb453bafecfad5031f9602180f5b>>
%%%-----------------------------------------------------------------------------
%%% %CopyrightBegin%
%%%
%%% SPDX-License-Identifier: Apache-2.0
%%%
%%% Copyright (c) Meta Platforms, Inc. and affiliates.
%%% Copyright (c) WhatsApp LLC
%%%
%%% Licensed under the Apache License, Version 2.0 (the "License");
%%% you may not use this file except in compliance with the License.
%%% You may obtain a copy of the License at
%%%
%%%     http://www.apache.org/licenses/LICENSE-2.0
%%%
%%% Unless required by applicable law or agreed to in writing, software
%%% distributed under the License is distributed on an "AS IS" BASIS,
%%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%%% See the License for the specific language governing permissions and
%%% limitations under the License.
%%%
%%% %CopyrightEnd%
%%%-----------------------------------------------------------------------------
%%% @doc
%%%
%%% @end
%%% Created :  04 Mar 2025 by Andrew Bennett <potatosaladx@meta.com>
%%%-----------------------------------------------------------------------------
%%% % @format
%%% % @oncall whatsapp_clr
-ifndef(MARKDOWN_RESOLVE_HRL).
-define(MARKDOWN_RESOLVE_HRL, 1).

%% Macros
-define(is_markdown_resolve_name(X),
    ((X) =:= label orelse
        (X) =:= attention orelse
        (X) =:= gfm_table orelse
        (X) =:= heading_atx orelse
        (X) =:= heading_setext orelse
        (X) =:= list_item orelse
        (X) =:= content orelse
        (X) =:= data orelse
        (X) =:= string orelse
        (X) =:= text)
).

-endif.
