%%% % DO NOT EDIT: this file was generated by 'just codegen'
%%% % @generated SignedSource<<f3c34f460fc33134b76f71b572dc5dd5>>
%%%-----------------------------------------------------------------------------
%%% Copyright (c) Meta Platforms, Inc. and affiliates.
%%% Copyright (c) WhatsApp LLC
%%%
%%% This source code is licensed under the MIT license found in the
%%% LICENSE.md file in the root directory of this source tree.
%%%
%%% @author Andrew Bennett <potatosaladx@meta.com>
%%% @copyright (c) Meta Platforms, Inc. and affiliates.
%%% @doc
%%%
%%% @end
%%% Created :  04 Mar 2025 by Andrew Bennett <potatosaladx@meta.com>
%%%-----------------------------------------------------------------------------
%%% % @format
%% @oncall whatsapp_clr
-ifndef(MARKDOWN_RESOLVE_HRL).
-define(MARKDOWN_RESOLVE_HRL, 1).

%% Macros
-define(is_markdown_resolve_name(X),
    ((X) =:= label orelse
        (X) =:= attention orelse
        (X) =:= gfm_table orelse
        (X) =:= heading_atx orelse
        (X) =:= heading_setext orelse
        (X) =:= list_item orelse
        (X) =:= content orelse
        (X) =:= data orelse
        (X) =:= string orelse
        (X) =:= text)
).

-endif.
