%%% % DO NOT EDIT: this file was generated by 'just codegen'
%%% % @generated SignedSource<<f6c80788e90b599fab3a3b76c65f3469>>
%%%-----------------------------------------------------------------------------
%%% %CopyrightBegin%
%%%
%%% SPDX-License-Identifier: Apache-2.0
%%%
%%% Copyright (c) Meta Platforms, Inc. and affiliates.
%%% Copyright (c) WhatsApp LLC
%%%
%%% Licensed under the Apache License, Version 2.0 (the "License");
%%% you may not use this file except in compliance with the License.
%%% You may obtain a copy of the License at
%%%
%%%     http://www.apache.org/licenses/LICENSE-2.0
%%%
%%% Unless required by applicable law or agreed to in writing, software
%%% distributed under the License is distributed on an "AS IS" BASIS,
%%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%%% See the License for the specific language governing permissions and
%%% limitations under the License.
%%%
%%% %CopyrightEnd%
%%%-----------------------------------------------------------------------------
%%% @doc
%%%
%%% @end
%%% Created :  04 Mar 2025 by Andrew Bennett <potatosaladx@meta.com>
%%%-----------------------------------------------------------------------------
%%% % @format
%%% % @oncall whatsapp_clr
-ifndef(MARKDOWN_DEBUG_TYPES_HRL).
-define(MARKDOWN_DEBUG_TYPES_HRL, 1).

%% Macros
-define(is_markdown_record_name(X),
    ((X) =:= array orelse
        (X) =:= markdown_attempt orelse
        (X) =:= markdown_construct_options orelse
        (X) =:= markdown_container orelse
        (X) =:= markdown_edit_map orelse
        (X) =:= markdown_event orelse
        (X) =:= markdown_event_link orelse
        (X) =:= markdown_html_media orelse
        (X) =:= markdown_index orelse
        (X) =:= markdown_indices orelse
        (X) =:= markdown_label_start orelse
        (X) =:= markdown_label orelse
        (X) =:= markdown_list_item orelse
        (X) =:= markdown_location orelse
        (X) =:= markdown_mdast_blockquote orelse
        (X) =:= markdown_mdast_emphasis orelse
        (X) =:= markdown_mdast_footnote_definition orelse
        (X) =:= markdown_mdast_footnote_reference orelse
        (X) =:= markdown_mdast_node orelse
        (X) =:= markdown_mdast_paragraph orelse
        (X) =:= markdown_mdast_reference orelse
        (X) =:= markdown_mdast_root orelse
        (X) =:= markdown_mdast_text orelse
        (X) =:= markdown_mdast_thematic_break orelse
        (X) =:= markdown_message orelse
        (X) =:= markdown_parse_options orelse
        (X) =:= markdown_parse_state orelse
        (X) =:= markdown_place orelse
        (X) =:= markdown_point orelse
        (X) =:= markdown_position orelse
        (X) =:= markdown_progress orelse
        (X) =:= markdown_sequence orelse
        (X) =:= markdown_slice orelse
        (X) =:= markdown_space_or_tab_options orelse
        (X) =:= markdown_subresult orelse
        (X) =:= markdown_tokenize_state orelse
        (X) =:= markdown_tokenizer orelse
        (X) =:= markdown_unist_point orelse
        (X) =:= markdown_unist_position orelse
        (X) =:= markdown_vec)
).

-endif.
