%%% % DO NOT EDIT: this file was generated by 'just codegen'
%%% % @generated SignedSource<<d58e1d7a8e0e9d2a3a430035a8c23bb5>>
%%%-----------------------------------------------------------------------------
%%% %CopyrightBegin%
%%%
%%% SPDX-License-Identifier: Apache-2.0
%%%
%%% Copyright (c) Meta Platforms, Inc. and affiliates.
%%% Copyright (c) WhatsApp LLC
%%%
%%% Licensed under the Apache License, Version 2.0 (the "License");
%%% you may not use this file except in compliance with the License.
%%% You may obtain a copy of the License at
%%%
%%%     http://www.apache.org/licenses/LICENSE-2.0
%%%
%%% Unless required by applicable law or agreed to in writing, software
%%% distributed under the License is distributed on an "AS IS" BASIS,
%%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%%% See the License for the specific language governing permissions and
%%% limitations under the License.
%%%
%%% %CopyrightEnd%
%%%-----------------------------------------------------------------------------
%%% % @format
-module(markdown_misc_dangerous_protocol_SUITE).
-moduledoc """

""".
-moduledoc #{author => ["Andrew Bennett <potatosaladx@meta.com>"]}.
-moduledoc #{created => "", modified => ""}.
-moduledoc #{copyright => "Meta Platforms, Inc. and affiliates."}.
-compile(warn_missing_spec_all).
-oncall("whatsapp_clr").

-include_lib("markdown/include/markdown_mdast.hrl").
-include_lib("markdown/include/markdown_util.hrl").
-include_lib("stdlib/include/assert.hrl").

-behaviour(ct_suite).

%% ct_suite callbacks
-export([
    all/0,
    groups/0,
    init_per_suite/1,
    end_per_suite/1,
    init_per_group/2,
    end_per_group/2
]).

%% Test Cases
-export([
    test_misc_dangerous_protocol_case_1/1,
    test_misc_dangerous_protocol_case_2/1,
    test_misc_dangerous_protocol_case_3/1,
    test_misc_dangerous_protocol_case_4/1,
    test_misc_dangerous_protocol_case_5/1,
    test_misc_dangerous_protocol_case_6/1,
    test_misc_dangerous_protocol_case_7/1,
    test_misc_dangerous_protocol_case_8/1,
    test_misc_dangerous_protocol_case_9/1,
    test_misc_dangerous_protocol_case_10/1,
    test_misc_dangerous_protocol_case_11/1,
    test_misc_dangerous_protocol_case_12/1,
    test_misc_dangerous_protocol_case_13/1,
    test_misc_dangerous_protocol_case_14/1,
    test_misc_dangerous_protocol_case_15/1,
    test_misc_dangerous_protocol_case_16/1,
    test_misc_dangerous_protocol_case_17/1,
    test_misc_dangerous_protocol_case_18/1,
    test_misc_dangerous_protocol_case_19/1,
    test_misc_dangerous_protocol_case_20/1,
    test_misc_dangerous_protocol_case_21/1,
    test_misc_dangerous_protocol_case_22/1,
    test_misc_dangerous_protocol_case_23/1,
    test_misc_dangerous_protocol_case_24/1,
    test_misc_dangerous_protocol_case_25/1,
    test_misc_dangerous_protocol_case_26/1,
    test_misc_dangerous_protocol_case_27/1,
    test_misc_dangerous_protocol_case_28/1,
    test_misc_dangerous_protocol_case_29/1,
    test_misc_dangerous_protocol_case_30/1,
    test_misc_dangerous_protocol_case_31/1,
    test_misc_dangerous_protocol_case_32/1,
    test_misc_dangerous_protocol_case_33/1,
    test_misc_dangerous_protocol_case_34/1
]).

%% Macros
-define(options, markdown_options:new(#{compile => #{allow_any_img_src => true}})).

%%%=============================================================================
%%% ct_suite callbacks
%%%=============================================================================

-spec all() -> markdown_test:all().
all() ->
    [
        {group, static}
    ].

-spec groups() -> markdown_test:groups().
groups() ->
    [
        {static, [parallel], [
            test_misc_dangerous_protocol_case_1,
            test_misc_dangerous_protocol_case_2,
            test_misc_dangerous_protocol_case_3,
            test_misc_dangerous_protocol_case_4,
            test_misc_dangerous_protocol_case_5,
            test_misc_dangerous_protocol_case_6,
            test_misc_dangerous_protocol_case_7,
            test_misc_dangerous_protocol_case_8,
            test_misc_dangerous_protocol_case_9,
            test_misc_dangerous_protocol_case_10,
            test_misc_dangerous_protocol_case_11,
            test_misc_dangerous_protocol_case_12,
            test_misc_dangerous_protocol_case_13,
            test_misc_dangerous_protocol_case_14,
            test_misc_dangerous_protocol_case_15,
            test_misc_dangerous_protocol_case_16,
            test_misc_dangerous_protocol_case_17,
            test_misc_dangerous_protocol_case_18,
            test_misc_dangerous_protocol_case_19,
            test_misc_dangerous_protocol_case_20,
            test_misc_dangerous_protocol_case_21,
            test_misc_dangerous_protocol_case_22,
            test_misc_dangerous_protocol_case_23,
            test_misc_dangerous_protocol_case_24,
            test_misc_dangerous_protocol_case_25,
            test_misc_dangerous_protocol_case_26,
            test_misc_dangerous_protocol_case_27,
            test_misc_dangerous_protocol_case_28,
            test_misc_dangerous_protocol_case_29,
            test_misc_dangerous_protocol_case_30,
            test_misc_dangerous_protocol_case_31,
            test_misc_dangerous_protocol_case_32,
            test_misc_dangerous_protocol_case_33,
            test_misc_dangerous_protocol_case_34
        ]}
    ].

-spec init_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:init_per_suite().
init_per_suite(Config) ->
    Config.

-spec end_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:end_per_suite().
end_per_suite(_Config) ->
    ok.

-spec init_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:init_per_group().
init_per_group(_Group, Config) ->
    Config.

-spec end_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:end_per_group().
end_per_group(_Group, _Config) ->
    ok.

%%%=============================================================================
%%% Test Cases
%%%=============================================================================

-spec test_misc_dangerous_protocol_case_1(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_1(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"\">javascript:alert(1)</a></p>"/utf8>>},
        markdown:to_html(<<"<javascript:alert(1)>"/utf8>>),
        "should be safe by default"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_2(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_2(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"http://a\">http://a</a></p>"/utf8>>},
        markdown:to_html(<<"<http://a>"/utf8>>),
        "should allow `http:`"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_3(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_3(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"https://a\">https://a</a></p>"/utf8>>},
        markdown:to_html(<<"<https://a>"/utf8>>),
        "should allow `https:`"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_4(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_4(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"irc:///help\">irc:///help</a></p>"/utf8>>},
        markdown:to_html(<<"<irc:///help>"/utf8>>),
        "should allow `irc:`"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_5(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_5(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"mailto:a\">mailto:a</a></p>"/utf8>>},
        markdown:to_html(<<"<mailto:a>"/utf8>>),
        "should allow `mailto:`"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_6(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_6(_Config) ->
    ?assertMatch(
        {ok, <<"<p><img src=\"\" alt=\"\" /></p>"/utf8>>},
        markdown:to_html(<<"![](javascript:alert(1))"/utf8>>),
        "should be safe by default"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_7(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_7(_Config) ->
    ?assertMatch(
        {ok, <<"<p><img src=\"http://a\" alt=\"\" /></p>"/utf8>>},
        markdown:to_html(<<"![](http://a)"/utf8>>),
        "should allow `http:`"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_8(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_8(_Config) ->
    ?assertMatch(
        {ok, <<"<p><img src=\"https://a\" alt=\"\" /></p>"/utf8>>},
        markdown:to_html(<<"![](https://a)"/utf8>>),
        "should allow `https:`"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_9(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_9(_Config) ->
    ?assertMatch(
        {ok, <<"<p><img src=\"\" alt=\"\" /></p>"/utf8>>},
        markdown:to_html(<<"![](irc:///help)"/utf8>>),
        "should not allow `irc:`"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_10(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_10(_Config) ->
    ?assertMatch(
        {ok, <<"<p><img src=\"\" alt=\"\" /></p>"/utf8>>},
        markdown:to_html(<<"![](mailto:a)"/utf8>>),
        "should not allow `mailto:`"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_11(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_11(_Config) ->
    ?assertMatch(
        {ok, <<"<p><img src=\"#a\" alt=\"\" /></p>"/utf8>>},
        markdown:to_html(<<"![](#a)"/utf8>>),
        "should allow a hash"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_12(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_12(_Config) ->
    ?assertMatch(
        {ok, <<"<p><img src=\"?a\" alt=\"\" /></p>"/utf8>>},
        markdown:to_html(<<"![](?a)"/utf8>>),
        "should allow a search"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_13(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_13(_Config) ->
    ?assertMatch(
        {ok, <<"<p><img src=\"/a\" alt=\"\" /></p>"/utf8>>},
        markdown:to_html(<<"![](/a)"/utf8>>),
        "should allow an absolute"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_14(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_14(_Config) ->
    ?assertMatch(
        {ok, <<"<p><img src=\"./a\" alt=\"\" /></p>"/utf8>>},
        markdown:to_html(<<"![](./a)"/utf8>>),
        "should allow an relative"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_15(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_15(_Config) ->
    ?assertMatch(
        {ok, <<"<p><img src=\"../a\" alt=\"\" /></p>"/utf8>>},
        markdown:to_html(<<"![](../a)"/utf8>>),
        "should allow an upwards relative"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_16(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_16(_Config) ->
    ?assertMatch(
        {ok, <<"<p><img src=\"a#b:c\" alt=\"\" /></p>"/utf8>>},
        markdown:to_html(<<"![](a#b:c)"/utf8>>),
        "should allow a colon in a hash"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_17(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_17(_Config) ->
    ?assertMatch(
        {ok, <<"<p><img src=\"a?b:c\" alt=\"\" /></p>"/utf8>>},
        markdown:to_html(<<"![](a?b:c)"/utf8>>),
        "should allow a colon in a search"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_18(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_18(_Config) ->
    ?assertMatch(
        {ok, <<"<p><img src=\"a/b:c\" alt=\"\" /></p>"/utf8>>},
        markdown:to_html(<<"![](a/b:c)"/utf8>>),
        "should allow a colon in a path"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_19(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_19(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"\"></a></p>"/utf8>>},
        markdown:to_html(<<"[](javascript:alert(1))"/utf8>>),
        "should be safe by default"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_20(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_20(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"http://a\"></a></p>"/utf8>>},
        markdown:to_html(<<"[](http://a)"/utf8>>),
        "should allow `http:`"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_21(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_21(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"https://a\"></a></p>"/utf8>>},
        markdown:to_html(<<"[](https://a)"/utf8>>),
        "should allow `https:`"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_22(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_22(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"irc:///help\"></a></p>"/utf8>>},
        markdown:to_html(<<"[](irc:///help)"/utf8>>),
        "should allow `irc:`"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_23(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_23(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"mailto:a\"></a></p>"/utf8>>},
        markdown:to_html(<<"[](mailto:a)"/utf8>>),
        "should allow `mailto:`"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_24(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_24(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"#a\"></a></p>"/utf8>>},
        markdown:to_html(<<"[](#a)"/utf8>>),
        "should allow a hash"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_25(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_25(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"?a\"></a></p>"/utf8>>},
        markdown:to_html(<<"[](?a)"/utf8>>),
        "should allow a search"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_26(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_26(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"/a\"></a></p>"/utf8>>},
        markdown:to_html(<<"[](/a)"/utf8>>),
        "should allow an absolute"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_27(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_27(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"./a\"></a></p>"/utf8>>},
        markdown:to_html(<<"[](./a)"/utf8>>),
        "should allow an relative"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_28(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_28(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"../a\"></a></p>"/utf8>>},
        markdown:to_html(<<"[](../a)"/utf8>>),
        "should allow an upwards relative"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_29(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_29(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"a#b:c\"></a></p>"/utf8>>},
        markdown:to_html(<<"[](a#b:c)"/utf8>>),
        "should allow a colon in a hash"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_30(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_30(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"a?b:c\"></a></p>"/utf8>>},
        markdown:to_html(<<"[](a?b:c)"/utf8>>),
        "should allow a colon in a search"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_31(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_31(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"a/b:c\"></a></p>"/utf8>>},
        markdown:to_html(<<"[](a/b:c)"/utf8>>),
        "should allow a colon in a path"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_32(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_32(_Config) ->
    ?assertMatch(
        {ok, <<"<p><img src=\"javascript:alert(1)\" alt=\"\" /></p>"/utf8>>},
        markdown:to_html_with_options(<<"![](javascript:alert(1))"/utf8>>, ?options),
        "should allow javascript protocol with allow_any_img_src option"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_33(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_33(_Config) ->
    ?assertMatch(
        {ok, <<"<p><img src=\"irc:///help\" alt=\"\" /></p>"/utf8>>},
        markdown:to_html_with_options(<<"![](irc:///help)"/utf8>>, ?options),
        "should allow irc protocol with allow_any_img_src option"
    ),
    ok.

-spec test_misc_dangerous_protocol_case_34(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_dangerous_protocol_case_34(_Config) ->
    ?assertMatch(
        {ok, <<"<p><img src=\"mailto:a\" alt=\"\" /></p>"/utf8>>},
        markdown:to_html_with_options(<<"![](mailto:a)"/utf8>>, ?options),
        "should allow mailto protocol with allow_any_img_src option"
    ),
    ok.
