%%% % DO NOT EDIT: this file was generated by 'just codegen'
%%% % @generated <<SignedSource::*O*zOeWoEQle#+L!plEphiEmie@IsG>>
%%% % @format
%%%-----------------------------------------------------------------------------
%%% Copyright (c) Meta Platforms, Inc. and affiliates.
%%% Copyright (c) WhatsApp LLC
%%%
%%% This source code is licensed under the MIT license found in the
%%% LICENSE.md file in the root directory of this source tree.
%%%-----------------------------------------------------------------------------
-module(markdown_hard_break_escape_SUITE).
-moduledoc """

""".
-moduledoc #{author => ["Andrew Bennett <potatosaladx@meta.com>"]}.
-moduledoc #{created => "", modified => ""}.
-moduledoc #{copyright => "Meta Platforms, Inc. and affiliates."}.
-compile(warn_missing_spec_all).
-oncall("whatsapp_clr").

-include_lib("markdown/include/markdown_mdast.hrl").
-include_lib("markdown/include/markdown_util.hrl").
-include_lib("stdlib/include/assert.hrl").

-behaviour(ct_suite).

%% ct_suite callbacks
-export([
    all/0,
    groups/0,
    init_per_suite/1,
    end_per_suite/1,
    init_per_group/2,
    end_per_group/2
]).

%% Test Cases
-export([
    test_hard_break_escape_case_1/1,
    test_hard_break_escape_case_2/1,
    test_hard_break_escape_case_3/1,
    test_hard_break_escape_case_4/1,
    test_hard_break_escape_case_5/1,
    test_hard_break_escape_case_6/1,
    test_hard_break_escape_case_7/1,
    test_hard_break_escape_case_8/1
]).

%%%=============================================================================
%%% ct_suite callbacks
%%%=============================================================================

-spec all() -> markdown_test:all().
all() ->
    [
        {group, static}
    ].

-spec groups() -> markdown_test:groups().
groups() ->
    [
        {static, [parallel], [
            test_hard_break_escape_case_1,
            test_hard_break_escape_case_2,
            test_hard_break_escape_case_3,
            test_hard_break_escape_case_4,
            test_hard_break_escape_case_5,
            test_hard_break_escape_case_6,
            test_hard_break_escape_case_7,
            test_hard_break_escape_case_8
        ]}
    ].

-spec init_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:init_per_suite().
init_per_suite(Config) ->
    Config.

-spec end_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:end_per_suite().
end_per_suite(_Config) ->
    ok.

-spec init_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:init_per_group().
init_per_group(_Group, Config) ->
    Config.

-spec end_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:end_per_group().
end_per_group(_Group, _Config) ->
    ok.

%%%=============================================================================
%%% Test Cases
%%%=============================================================================

-spec test_hard_break_escape_case_1(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_escape_case_1(_Config) ->
    ?assertMatch(
        {ok, <<"<p>foo<br />\nbaz</p>"/utf8>>},
        markdown:to_html(<<"foo\\\nbaz"/utf8>>),
        "should support a backslash to form a hard break"
    ),
    ok.

-spec test_hard_break_escape_case_2(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_escape_case_2(_Config) ->
    ?assertMatch(
        {ok, <<"<p>foo<br />\nbar</p>"/utf8>>},
        markdown:to_html(<<"foo\\\n     bar"/utf8>>),
        "should support leading spaces after an escape hard break"
    ),
    ok.

-spec test_hard_break_escape_case_3(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_escape_case_3(_Config) ->
    ?assertMatch(
        {ok, <<"<p><em>foo<br />\nbar</em></p>"/utf8>>},
        markdown:to_html(<<"*foo\\\nbar*"/utf8>>),
        "should support escape hard breaks in emphasis"
    ),
    ok.

-spec test_hard_break_escape_case_4(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_escape_case_4(_Config) ->
    ?assertMatch(
        {ok, <<"<p><code>code\\ text</code></p>"/utf8>>},
        markdown:to_html(<<"``code\\\ntext``"/utf8>>),
        "should not support escape hard breaks in code"
    ),
    ok.

-spec test_hard_break_escape_case_5(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_escape_case_5(_Config) ->
    ?assertMatch(
        {ok, <<"<p>foo\\</p>"/utf8>>},
        markdown:to_html(<<"foo\\"/utf8>>),
        "should not support escape hard breaks at the end of a paragraph"
    ),
    ok.

-spec test_hard_break_escape_case_6(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_escape_case_6(_Config) ->
    ?assertMatch(
        {ok, <<"<h3>foo\\</h3>"/utf8>>},
        markdown:to_html(<<"### foo\\"/utf8>>),
        "should not support escape hard breaks at the end of a heading"
    ),
    ok.

-spec test_hard_break_escape_case_7(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_escape_case_7(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a\\\nb</p>"/utf8>>},
        markdown:to_html_with_options(
            <<"a\\\nb"/utf8>>, markdown_options:default(#{parse => #{constructs => #{hard_break_escape => false}}})
        ),
        "should support turning off hard break (escape)"
    ),
    ok.

-spec test_hard_break_escape_case_8(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_escape_case_8(_Config) ->
    ?assertEqual(
        {ok,
            markdown_mdast_node:root(#markdown_mdast_root{
                children = ?'vec!'([
                    markdown_mdast_node:paragraph(#markdown_mdast_paragraph{
                        children = ?'vec!'([
                            markdown_mdast_node:text(#markdown_mdast_text{
                                value = <<"a">>,
                                position = {some, markdown_unist_position:new(1, 1, 0, 1, 2, 1)}
                            }),
                            markdown_mdast_node:break(#markdown_mdast_break{
                                position = {some, markdown_unist_position:new(1, 2, 1, 2, 1, 3)}
                            }),
                            markdown_mdast_node:text(#markdown_mdast_text{
                                value = <<"b.">>,
                                position = {some, markdown_unist_position:new(2, 1, 3, 2, 3, 5)}
                            })
                        ]),
                        position = {some, markdown_unist_position:new(1, 1, 0, 2, 3, 5)}
                    })
                ]),
                position = {some, markdown_unist_position:new(1, 1, 0, 2, 3, 5)}
            })},
        markdown:to_mdast(<<"a\\\nb."/utf8>>, markdown_parse_options:default()),
        "should support hard break (escape) as `Break`s in mdast"
    ),
    ok.
