%%% % DO NOT EDIT: this file was generated by 'just codegen'
%%% % @generated SignedSource<<0bfea51409a5aded2106cd4083ce5125>>
%%%-----------------------------------------------------------------------------
%%% %CopyrightBegin%
%%%
%%% SPDX-License-Identifier: Apache-2.0
%%%
%%% Copyright (c) Meta Platforms, Inc. and affiliates.
%%% Copyright (c) WhatsApp LLC
%%%
%%% Licensed under the Apache License, Version 2.0 (the "License");
%%% you may not use this file except in compliance with the License.
%%% You may obtain a copy of the License at
%%%
%%%     http://www.apache.org/licenses/LICENSE-2.0
%%%
%%% Unless required by applicable law or agreed to in writing, software
%%% distributed under the License is distributed on an "AS IS" BASIS,
%%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%%% See the License for the specific language governing permissions and
%%% limitations under the License.
%%%
%%% %CopyrightEnd%
%%%-----------------------------------------------------------------------------
%%% % @format
-module(markdown_heading_setext_SUITE).
-moduledoc """

""".
-moduledoc #{author => ["Andrew Bennett <potatosaladx@meta.com>"]}.
-moduledoc #{created => "2025-10-08", modified => "2025-10-08"}.
-moduledoc #{copyright => "Meta Platforms, Inc. and affiliates."}.
-compile(warn_missing_spec_all).
-oncall("whatsapp_clr").

-include_lib("markdown/include/markdown_mdast.hrl").
-include_lib("markdown/include/markdown_util.hrl").
-include_lib("stdlib/include/assert.hrl").

-behaviour(ct_suite).

%% ct_suite callbacks
-export([
    all/0,
    groups/0,
    init_per_suite/1,
    end_per_suite/1,
    init_per_group/2,
    end_per_group/2
]).

%% Test Cases
-export([
    test_heading_setext_case_1/1,
    test_heading_setext_case_2/1,
    test_heading_setext_case_3/1,
    test_heading_setext_case_4/1,
    test_heading_setext_case_5/1,
    test_heading_setext_case_6/1,
    test_heading_setext_case_7/1,
    test_heading_setext_case_8/1,
    test_heading_setext_case_9/1,
    test_heading_setext_case_10/1,
    test_heading_setext_case_11/1,
    test_heading_setext_case_12/1,
    test_heading_setext_case_13/1,
    test_heading_setext_case_14/1,
    test_heading_setext_case_15/1,
    test_heading_setext_case_16/1,
    test_heading_setext_case_17/1,
    test_heading_setext_case_18/1,
    test_heading_setext_case_19/1,
    test_heading_setext_case_20/1,
    test_heading_setext_case_21/1,
    test_heading_setext_case_22/1,
    test_heading_setext_case_23/1,
    test_heading_setext_case_24/1,
    test_heading_setext_case_25/1,
    test_heading_setext_case_26/1,
    test_heading_setext_case_27/1,
    test_heading_setext_case_28/1,
    test_heading_setext_case_29/1,
    test_heading_setext_case_30/1,
    test_heading_setext_case_31/1,
    test_heading_setext_case_32/1,
    test_heading_setext_case_33/1,
    test_heading_setext_case_34/1,
    test_heading_setext_case_35/1,
    test_heading_setext_case_36/1,
    test_heading_setext_case_37/1,
    test_heading_setext_case_38/1,
    test_heading_setext_case_39/1,
    test_heading_setext_case_40/1,
    test_heading_setext_case_41/1,
    test_heading_setext_case_42/1,
    test_heading_setext_case_43/1,
    test_heading_setext_case_44/1,
    test_heading_setext_case_45/1,
    test_heading_setext_case_46/1,
    test_heading_setext_case_47/1
]).

%%%=============================================================================
%%% ct_suite callbacks
%%%=============================================================================

-spec all() -> markdown_test:all().
all() ->
    [
        {group, static}
    ].

-spec groups() -> markdown_test:groups().
groups() ->
    [
        {static, [parallel], [
            test_heading_setext_case_1,
            test_heading_setext_case_2,
            test_heading_setext_case_3,
            test_heading_setext_case_4,
            test_heading_setext_case_5,
            test_heading_setext_case_6,
            test_heading_setext_case_7,
            test_heading_setext_case_8,
            test_heading_setext_case_9,
            test_heading_setext_case_10,
            test_heading_setext_case_11,
            test_heading_setext_case_12,
            test_heading_setext_case_13,
            test_heading_setext_case_14,
            test_heading_setext_case_15,
            test_heading_setext_case_16,
            test_heading_setext_case_17,
            test_heading_setext_case_18,
            test_heading_setext_case_19,
            test_heading_setext_case_20,
            test_heading_setext_case_21,
            test_heading_setext_case_22,
            test_heading_setext_case_23,
            test_heading_setext_case_24,
            test_heading_setext_case_25,
            test_heading_setext_case_26,
            test_heading_setext_case_27,
            test_heading_setext_case_28,
            test_heading_setext_case_29,
            test_heading_setext_case_30,
            test_heading_setext_case_31,
            test_heading_setext_case_32,
            test_heading_setext_case_33,
            test_heading_setext_case_34,
            test_heading_setext_case_35,
            test_heading_setext_case_36,
            test_heading_setext_case_37,
            test_heading_setext_case_38,
            test_heading_setext_case_39,
            test_heading_setext_case_40,
            test_heading_setext_case_41,
            test_heading_setext_case_42,
            test_heading_setext_case_43,
            test_heading_setext_case_44,
            test_heading_setext_case_45,
            test_heading_setext_case_46,
            test_heading_setext_case_47
        ]}
    ].

-spec init_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:init_per_suite().
init_per_suite(Config) ->
    Config.

-spec end_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:end_per_suite().
end_per_suite(_Config) ->
    ok.

-spec init_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:init_per_group().
init_per_group(_Group, Config) ->
    Config.

-spec end_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:end_per_group().
end_per_group(_Group, _Config) ->
    ok.

%%%=============================================================================
%%% Test Cases
%%%=============================================================================

-spec test_heading_setext_case_1(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_1(_Config) ->
    ?assertMatch(
        {ok, <<"<h1>Foo <em>bar</em></h1>"/utf8>>},
        markdown:to_html(<<"Foo *bar*\n========="/utf8>>),
        "should support a heading w/ an equals to (rank of 1)"
    ),
    ok.

-spec test_heading_setext_case_2(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_2(_Config) ->
    ?assertMatch(
        {ok, <<"<h2>Foo <em>bar</em></h2>"/utf8>>},
        markdown:to_html(<<"Foo *bar*\n---------"/utf8>>),
        "should support a heading w/ a dash (rank of 2)"
    ),
    ok.

-spec test_heading_setext_case_3(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_3(_Config) ->
    ?assertMatch(
        {ok, <<"<h1>Foo <em>bar\nbaz</em></h1>"/utf8>>},
        markdown:to_html(<<"Foo *bar\nbaz*\n===="/utf8>>),
        "should support line endings in setext headings"
    ),
    ok.

-spec test_heading_setext_case_4(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_4(_Config) ->
    ?assertMatch(
        {ok, <<"<h1>Foo <em>bar\nbaz</em></h1>"/utf8>>},
        markdown:to_html(<<"  Foo *bar\nbaz*\t\n===="/utf8>>),
        "should not include initial and final whitespace around content"
    ),
    ok.

-spec test_heading_setext_case_5(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_5(_Config) ->
    ?assertMatch(
        {ok, <<"<h2>Foo</h2>"/utf8>>},
        markdown:to_html(<<"Foo\n-------------------------"/utf8>>),
        "should support long underlines"
    ),
    ok.

-spec test_heading_setext_case_6(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_6(_Config) ->
    ?assertMatch(
        {ok, <<"<h1>Foo</h1>"/utf8>>},
        markdown:to_html(<<"Foo\n="/utf8>>),
        "should support short underlines"
    ),
    ok.

-spec test_heading_setext_case_7(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_7(_Config) ->
    ?assertMatch(
        {ok, <<"<h1>Foo</h1>"/utf8>>},
        markdown:to_html(<<" Foo\n  ==="/utf8>>),
        "should support indented content w/ 1 space"
    ),
    ok.

-spec test_heading_setext_case_8(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_8(_Config) ->
    ?assertMatch(
        {ok, <<"<h2>Foo</h2>"/utf8>>},
        markdown:to_html(<<"  Foo\n---"/utf8>>),
        "should support indented content w/ 2 spaces"
    ),
    ok.

-spec test_heading_setext_case_9(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_9(_Config) ->
    ?assertMatch(
        {ok, <<"<h2>Foo</h2>"/utf8>>},
        markdown:to_html(<<"   Foo\n---"/utf8>>),
        "should support indented content w/ 3 spaces"
    ),
    ok.

-spec test_heading_setext_case_10(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_10(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code>Foo\n---\n</code></pre>"/utf8>>},
        markdown:to_html(<<"    Foo\n    ---"/utf8>>),
        "should not support too much indented content (1)"
    ),
    ok.

-spec test_heading_setext_case_11(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_11(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code>Foo\n</code></pre>\n<hr />"/utf8>>},
        markdown:to_html(<<"    Foo\n---"/utf8>>),
        "should not support too much indented content (2)"
    ),
    ok.

-spec test_heading_setext_case_12(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_12(_Config) ->
    ?assertMatch(
        {ok, <<"<h2>Foo</h2>"/utf8>>},
        markdown:to_html(<<"Foo\n   ----      "/utf8>>),
        "should support initial and final whitespace around the underline"
    ),
    ok.

-spec test_heading_setext_case_13(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_13(_Config) ->
    ?assertMatch(
        {ok, <<"<h1>Foo</h1>"/utf8>>},
        markdown:to_html(<<"Foo\n   ="/utf8>>),
        "should support whitespace before underline"
    ),
    ok.

-spec test_heading_setext_case_14(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_14(_Config) ->
    ?assertMatch(
        {ok, <<"<p>Foo\n=</p>"/utf8>>},
        markdown:to_html(<<"Foo\n    ="/utf8>>),
        "should not support too much whitespace before underline (1)"
    ),
    ok.

-spec test_heading_setext_case_15(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_15(_Config) ->
    ?assertMatch(
        {ok, <<"<p>Foo\n=</p>"/utf8>>},
        markdown:to_html(<<"Foo\n\t="/utf8>>),
        "should not support too much whitespace before underline (2)"
    ),
    ok.

-spec test_heading_setext_case_16(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_16(_Config) ->
    ?assertMatch(
        {ok, <<"<p>Foo\n= =</p>"/utf8>>},
        markdown:to_html(<<"Foo\n= ="/utf8>>),
        "should not support whitespace in the underline (1)"
    ),
    ok.

-spec test_heading_setext_case_17(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_17(_Config) ->
    ?assertMatch(
        {ok, <<"<p>Foo</p>\n<hr />"/utf8>>},
        markdown:to_html(<<"Foo\n--- -"/utf8>>),
        "should not support whitespace in the underline (2)"
    ),
    ok.

-spec test_heading_setext_case_18(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_18(_Config) ->
    ?assertMatch(
        {ok, <<"<h2>Foo</h2>"/utf8>>},
        markdown:to_html(<<"Foo  \n-----"/utf8>>),
        "should not support a hard break w/ spaces at the end"
    ),
    ok.

-spec test_heading_setext_case_19(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_19(_Config) ->
    ?assertMatch(
        {ok, <<"<h2>Foo\\</h2>"/utf8>>},
        markdown:to_html(<<"Foo\\\n-----"/utf8>>),
        "should not support a hard break w/ backslash at the end"
    ),
    ok.

-spec test_heading_setext_case_20(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_20(_Config) ->
    ?assertMatch(
        {ok, <<"<h2>`Foo</h2>\n<p>`</p>"/utf8>>},
        markdown:to_html(<<"`Foo\n----\n`"/utf8>>),
        "should precede over inline constructs (1)"
    ),
    ok.

-spec test_heading_setext_case_21(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_21(_Config) ->
    ?assertMatch(
        {ok, <<"<h2>&lt;a title=&quot;a lot</h2>\n<p>of dashes&quot;/&gt;</p>"/utf8>>},
        markdown:to_html(<<"<a title=\"a lot\n---\nof dashes\"/>"/utf8>>),
        "should precede over inline constructs (2)"
    ),
    ok.

-spec test_heading_setext_case_22(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_22(_Config) ->
    ?assertMatch(
        {ok, <<"<blockquote>\n<p>Foo</p>\n</blockquote>\n<hr />"/utf8>>},
        markdown:to_html(<<"> Foo\n---"/utf8>>),
        "should not allow underline to be lazy (1)"
    ),
    ok.

-spec test_heading_setext_case_23(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_23(_Config) ->
    ?assertMatch(
        {ok, <<"<blockquote>\n<p>foo\nbar\n===</p>\n</blockquote>"/utf8>>},
        markdown:to_html(<<"> foo\nbar\n==="/utf8>>),
        "should not allow underline to be lazy (2)"
    ),
    ok.

-spec test_heading_setext_case_24(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_24(_Config) ->
    ?assertMatch(
        {ok, <<"<ul>\n<li>Foo</li>\n</ul>\n<hr />"/utf8>>},
        markdown:to_html(<<"- Foo\n---"/utf8>>),
        "should not allow underline to be lazy (3)"
    ),
    ok.

-spec test_heading_setext_case_25(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_25(_Config) ->
    ?assertMatch(
        {ok, <<"<h2>Foo\nBar</h2>"/utf8>>},
        markdown:to_html(<<"Foo\nBar\n---"/utf8>>),
        "should support line endings in setext headings"
    ),
    ok.

-spec test_heading_setext_case_26(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_26(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />\n<h2>Foo</h2>\n<h2>Bar</h2>\n<p>Baz</p>"/utf8>>},
        markdown:to_html(<<"---\nFoo\n---\nBar\n---\nBaz"/utf8>>),
        "should support adjacent setext headings"
    ),
    ok.

-spec test_heading_setext_case_27(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_27(_Config) ->
    ?assertMatch(
        {ok, <<"<p>====</p>"/utf8>>},
        markdown:to_html(<<"\n===="/utf8>>),
        "should not support empty setext headings"
    ),
    ok.

-spec test_heading_setext_case_28(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_28(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />\n<hr />"/utf8>>},
        markdown:to_html(<<"---\n---"/utf8>>),
        "should prefer other constructs over setext headings (1)"
    ),
    ok.

-spec test_heading_setext_case_29(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_29(_Config) ->
    ?assertMatch(
        {ok, <<"<ul>\n<li>foo</li>\n</ul>\n<hr />"/utf8>>},
        markdown:to_html(<<"- foo\n-----"/utf8>>),
        "should prefer other constructs over setext headings (2)"
    ),
    ok.

-spec test_heading_setext_case_30(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_30(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code>foo\n</code></pre>\n<hr />"/utf8>>},
        markdown:to_html(<<"    foo\n---"/utf8>>),
        "should prefer other constructs over setext headings (3)"
    ),
    ok.

-spec test_heading_setext_case_31(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_31(_Config) ->
    ?assertMatch(
        {ok, <<"<blockquote>\n<p>foo</p>\n</blockquote>\n<hr />"/utf8>>},
        markdown:to_html(<<"> foo\n-----"/utf8>>),
        "should prefer other constructs over setext headings (4)"
    ),
    ok.

-spec test_heading_setext_case_32(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_32(_Config) ->
    ?assertMatch(
        {ok, <<"<h2>&gt; foo</h2>"/utf8>>},
        markdown:to_html(<<"\\> foo\n------"/utf8>>),
        "should support starting w/ character escapes"
    ),
    ok.

-spec test_heading_setext_case_33(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_33(_Config) ->
    ?assertMatch(
        {ok, <<"<h2>Foo\nbar</h2>\n<p>baz</p>"/utf8>>},
        markdown:to_html(<<"Foo\nbar\n---\nbaz"/utf8>>),
        "paragraph and heading interplay (1)"
    ),
    ok.

-spec test_heading_setext_case_34(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_34(_Config) ->
    ?assertMatch(
        {ok, <<"<p>Foo</p>\n<h2>bar</h2>\n<p>baz</p>"/utf8>>},
        markdown:to_html(<<"Foo\n\nbar\n---\nbaz"/utf8>>),
        "paragraph and heading interplay (2)"
    ),
    ok.

-spec test_heading_setext_case_35(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_35(_Config) ->
    ?assertMatch(
        {ok, <<"<p>Foo\nbar</p>\n<hr />\n<p>baz</p>"/utf8>>},
        markdown:to_html(<<"Foo\nbar\n\n---\n\nbaz"/utf8>>),
        "paragraph and heading interplay (3)"
    ),
    ok.

-spec test_heading_setext_case_36(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_36(_Config) ->
    ?assertMatch(
        {ok, <<"<p>Foo\nbar</p>\n<hr />\n<p>baz</p>"/utf8>>},
        markdown:to_html(<<"Foo\nbar\n* * *\nbaz"/utf8>>),
        "paragraph and heading interplay (4)"
    ),
    ok.

-spec test_heading_setext_case_37(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_37(_Config) ->
    ?assertMatch(
        {ok, <<"<p>Foo\nbar\n---\nbaz</p>"/utf8>>},
        markdown:to_html(<<"Foo\nbar\n\\---\nbaz"/utf8>>),
        "paragraph and heading interplay (5)"
    ),
    ok.

-spec test_heading_setext_case_38(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_38(_Config) ->
    %% Extra:
    ?assertMatch(
        {ok, <<"<h2>Foo<br />\nbar</h2>"/utf8>>},
        markdown:to_html(<<"Foo  \nbar\n-----"/utf8>>),
        "should support a hard break w/ spaces in between"
    ),
    ok.

-spec test_heading_setext_case_39(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_39(_Config) ->
    ?assertMatch(
        {ok, <<"<h2>Foo<br />\nbar</h2>"/utf8>>},
        markdown:to_html(<<"Foo\\\nbar\n-----"/utf8>>),
        "should support a hard break w/ backslash in between"
    ),
    ok.

-spec test_heading_setext_case_40(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_40(_Config) ->
    ?assertMatch(
        {ok, <<"<h2>a</h2>\n<p>b</p>"/utf8>>},
        markdown:to_html(<<"a\n-\nb"/utf8>>),
        "should prefer a setext heading over an interrupting list"
    ),
    ok.

-spec test_heading_setext_case_41(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_41(_Config) ->
    ?assertMatch(
        {ok, <<"<h1>=</h1>"/utf8>>},
        markdown:to_html(<<"[a]: b\n=\n="/utf8>>),
        "should support a two setext heading underlines after a definition, as a setext heading"
    ),
    ok.

-spec test_heading_setext_case_42(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_42(_Config) ->
    ?assertMatch(
        {ok, <<"<blockquote>\n<p>===\na</p>\n</blockquote>"/utf8>>},
        markdown:to_html(<<"> ===\na"/utf8>>),
        "should not support lazyness (1)"
    ),
    ok.

-spec test_heading_setext_case_43(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_43(_Config) ->
    ?assertMatch(
        {ok, <<"<blockquote>\n<p>a\n===</p>\n</blockquote>"/utf8>>},
        markdown:to_html(<<"> a\n==="/utf8>>),
        "should not support lazyness (2)"
    ),
    ok.

-spec test_heading_setext_case_44(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_44(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a</p>\n<ul>\n<li>===</li>\n</ul>"/utf8>>},
        markdown:to_html(<<"a\n- ==="/utf8>>),
        "should not support piercing (1)"
    ),
    ok.

-spec test_heading_setext_case_45(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_45(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a</p>\n<ul>\n<li>\n<hr />\n</li>\n</ul>"/utf8>>},
        markdown:to_html(<<"a\n* ---"/utf8>>),
        "should not support piercing (2)"
    ),
    ok.

-spec test_heading_setext_case_46(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_46(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a\n-</p>"/utf8>>},
        markdown:to_html_with_options(
            <<"a\n-"/utf8>>, markdown_options:default(#{parse => #{constructs => #{heading_setext => false}}})
        ),
        "should support turning off setext underlines"
    ),
    ok.

-spec test_heading_setext_case_47(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_setext_case_47(_Config) ->
    ?assertEqual(
        {ok,
            markdown_mdast_node:root(#markdown_mdast_root{
                children = ?'vec!'([
                    markdown_mdast_node:heading(#markdown_mdast_heading{
                        depth = 1,
                        children = ?'vec!'([
                            markdown_mdast_node:text(#markdown_mdast_text{
                                value = <<"alpha\nbravo">>,
                                position = {some, markdown_unist_position:new(1, 1, 0, 2, 6, 11)}
                            })
                        ]),
                        position = {some, markdown_unist_position:new(1, 1, 0, 3, 3, 14)}
                    })
                ]),
                position = {some, markdown_unist_position:new(1, 1, 0, 3, 3, 14)}
            })},
        markdown:to_mdast(<<"alpha\nbravo\n=="/utf8>>, markdown_parse_options:default()),
        "should support heading (atx) as `Heading`s in mdast"
    ),
    ok.
