%%% % DO NOT EDIT: this file was generated by 'just codegen'
%%% % @generated SignedSource<<ee54db57b616fdd0496d8ca965896451>>
%%%-----------------------------------------------------------------------------
%%% %CopyrightBegin%
%%%
%%% SPDX-License-Identifier: Apache-2.0
%%%
%%% Copyright (c) Meta Platforms, Inc. and affiliates.
%%% Copyright (c) WhatsApp LLC
%%%
%%% Licensed under the Apache License, Version 2.0 (the "License");
%%% you may not use this file except in compliance with the License.
%%% You may obtain a copy of the License at
%%%
%%%     http://www.apache.org/licenses/LICENSE-2.0
%%%
%%% Unless required by applicable law or agreed to in writing, software
%%% distributed under the License is distributed on an "AS IS" BASIS,
%%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%%% See the License for the specific language governing permissions and
%%% limitations under the License.
%%%
%%% %CopyrightEnd%
%%%-----------------------------------------------------------------------------
%%% % @format
-module(markdown_misc_zero_SUITE).
-moduledoc """

""".
-moduledoc #{author => ["Andrew Bennett <potatosaladx@meta.com>"]}.
-moduledoc #{created => "2025-10-28", modified => "2025-10-28"}.
-moduledoc #{copyright => "Meta Platforms, Inc. and affiliates."}.
-compile(warn_missing_spec_all).
-oncall("whatsapp_clr").

-include_lib("markdown/include/markdown_mdast.hrl").
-include_lib("markdown/include/markdown_util.hrl").
-include_lib("stdlib/include/assert.hrl").

-behaviour(ct_suite).

%% ct_suite callbacks
-export([
    all/0,
    groups/0,
    init_per_suite/1,
    end_per_suite/1,
    init_per_group/2,
    end_per_group/2
]).

%% Test Cases
-export([
    test_misc_zero_case_1/1,
    test_misc_zero_case_2/1,
    test_misc_zero_case_3/1,
    %% This doesn’t make sense in markdown, as character escapes only work on

    %% ascii punctuation, but it’s good to demonstrate the behavior.
    test_misc_zero_case_4/1,
    test_misc_zero_case_5/1
]).

%%%=============================================================================
%%% ct_suite callbacks
%%%=============================================================================

-spec all() -> markdown_test:all().
all() ->
    [
        {group, static}
    ].

-spec groups() -> markdown_test:groups().
groups() ->
    [
        {static, [parallel], [
            test_misc_zero_case_1,
            test_misc_zero_case_2,
            test_misc_zero_case_3,
            %% This doesn’t make sense in markdown, as character escapes only work on

            %% ascii punctuation, but it’s good to demonstrate the behavior.
            test_misc_zero_case_4,
            test_misc_zero_case_5
        ]}
    ].

-spec init_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:init_per_suite().
init_per_suite(Config) ->
    Config.

-spec end_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:end_per_suite().
end_per_suite(_Config) ->
    ok.

-spec init_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:init_per_group().
init_per_group(_Group, Config) ->
    Config.

-spec end_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:end_per_group().
end_per_group(_Group, _Config) ->
    ok.

%%%=============================================================================
%%% Test Cases
%%%=============================================================================

-spec test_misc_zero_case_1(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_zero_case_1(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html(<<""/utf8>>),
        "should support no markdown"
    ),
    ok.

-spec test_misc_zero_case_2(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_zero_case_2(_Config) ->
    ?assertMatch(
        {ok, <<"<p>asd�asd</p>"/utf8>>},
        markdown:to_html(<<"asd\x00asd"/utf8>>),
        "should replace `\\0` w/ a replacement characters (`�`)"
    ),
    ok.

-spec test_misc_zero_case_3(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_zero_case_3(_Config) ->
    ?assertMatch(
        {ok, <<"<p>�</p>"/utf8>>},
        markdown:to_html(<<"&#0;"/utf8>>),
        "should replace NUL in a character reference"
    ),
    ok.

-spec test_misc_zero_case_4(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_zero_case_4(_Config) ->
    %% This doesn’t make sense in markdown, as character escapes only work on
    %% ascii punctuation, but it’s good to demonstrate the behavior.
    ?assertMatch(
        {ok, <<"<p>\\0</p>"/utf8>>},
        markdown:to_html(<<"\\0"/utf8>>),
        "should not support NUL in a character escape"
    ),
    ok.

-spec test_misc_zero_case_5(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_zero_case_5(_Config) ->
    ?assertEqual(
        {ok,
            markdown_mdast_node:root(#markdown_mdast_root{
                children = ?'vec!'([]),
                position = {some, markdown_unist_position:new(1, 1, 0, 1, 1, 0)}
            })},
        markdown:to_mdast(<<""/utf8>>, markdown_parse_options:new(#{})),
        "should support no markdown (ast)"
    ),
    ok.
