%%% % DO NOT EDIT: this file was generated by 'just codegen'
%%% % @generated SignedSource<<6d6bd09ae41d15ddb3b5faa47d272ba4>>
%%%-----------------------------------------------------------------------------
%%% %CopyrightBegin%
%%%
%%% SPDX-License-Identifier: Apache-2.0
%%%
%%% Copyright (c) Meta Platforms, Inc. and affiliates.
%%% Copyright (c) WhatsApp LLC
%%%
%%% Licensed under the Apache License, Version 2.0 (the "License");
%%% you may not use this file except in compliance with the License.
%%% You may obtain a copy of the License at
%%%
%%%     http://www.apache.org/licenses/LICENSE-2.0
%%%
%%% Unless required by applicable law or agreed to in writing, software
%%% distributed under the License is distributed on an "AS IS" BASIS,
%%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%%% See the License for the specific language governing permissions and
%%% limitations under the License.
%%%
%%% %CopyrightEnd%
%%%-----------------------------------------------------------------------------
%%% % @format
-module(markdown_mdx_expression_text_SUITE).
-moduledoc """

""".
-moduledoc #{author => ["Andrew Bennett <potatosaladx@meta.com>"]}.
-moduledoc #{created => "2025-10-29", modified => "2025-10-29"}.
-moduledoc #{copyright => "Meta Platforms, Inc. and affiliates."}.
-compile(warn_missing_spec_all).
-oncall("whatsapp_clr").

-include_lib("markdown/include/markdown_mdast.hrl").
-include_lib("markdown/include/markdown_util.hrl").
-include_lib("stdlib/include/assert.hrl").

-behaviour(ct_suite).

%% ct_suite callbacks
-export([
    all/0,
    groups/0,
    init_per_suite/1,
    end_per_suite/1,
    init_per_group/2,
    end_per_group/2
]).

%% Test Cases
-export([
    test_mdx_expression_text_case_1/1,
    test_mdx_expression_text_case_2/1,
    test_mdx_expression_text_case_3/1,
    test_mdx_expression_text_case_4/1,
    test_mdx_expression_text_case_5/1,
    test_mdx_expression_text_case_6/1,
    test_mdx_expression_text_case_7/1,
    test_mdx_expression_text_case_8/1,
    test_mdx_expression_text_case_9/1,
    test_mdx_expression_text_case_10/1,
    test_mdx_expression_text_case_11/1,
    test_mdx_expression_text_case_12/1,
    test_mdx_expression_text_case_13/1,
    test_mdx_expression_text_case_14/1,
    test_mdx_expression_text_case_15/1,
    test_mdx_expression_text_case_16/1,
    test_mdx_expression_text_case_17/1,
    test_mdx_expression_text_case_18/1,
    test_mdx_expression_text_case_19/1,
    test_mdx_expression_text_case_20/1,
    test_mdx_expression_text_case_21/1,
    test_mdx_expression_text_case_22/1,
    test_mdx_expression_text_case_23/1,
    test_mdx_expression_text_case_24/1,
    test_mdx_expression_text_case_25/1,
    test_mdx_expression_text_case_26/1,
    test_mdx_expression_text_case_27/1,
    test_mdx_expression_text_case_28/1,
    test_mdx_expression_text_case_29/1,
    test_mdx_expression_text_case_30/1,
    test_mdx_expression_text_case_31/1,
    test_mdx_expression_text_case_32/1,
    test_mdx_expression_text_case_33/1,
    test_mdx_expression_text_case_34/1,
    test_mdx_expression_text_case_35/1,
    test_mdx_expression_text_case_36/1,
    test_mdx_expression_text_case_37/1,
    test_mdx_expression_text_case_38/1,
    test_mdx_expression_text_case_39/1
]).

%% Macros
-define(mdx, markdown_options:mdx(#{})).
-define(swc,
    markdown_options:mdx(#{
        parse => #{
            mdx_expression_parse => {some, fun markdown_test_utils_swc:parse_expression/2},
            mdx_esm_parse => {some, fun markdown_test_utils_swc:parse_esm/1}
        }
    })
).
-define(mdx_parse, markdown_parse_options:mdx(#{})).
-define(swc_parse,
    markdown_parse_options:mdx(#{
        mdx_expression_parse => {some, fun markdown_test_utils_swc:parse_expression/2},
        mdx_esm_parse => {some, fun markdown_test_utils_swc:parse_esm/1}
    })
).

%%%=============================================================================
%%% ct_suite callbacks
%%%=============================================================================

-spec all() -> markdown_test:all().
all() ->
    [
        {group, static}
    ].

-spec groups() -> markdown_test:groups().
groups() ->
    [
        {static, [parallel], [
            test_mdx_expression_text_case_1,
            test_mdx_expression_text_case_2,
            test_mdx_expression_text_case_3,
            test_mdx_expression_text_case_4,
            test_mdx_expression_text_case_5,
            test_mdx_expression_text_case_6,
            test_mdx_expression_text_case_7,
            test_mdx_expression_text_case_8,
            test_mdx_expression_text_case_9,
            test_mdx_expression_text_case_10,
            test_mdx_expression_text_case_11,
            test_mdx_expression_text_case_12,
            test_mdx_expression_text_case_13,
            test_mdx_expression_text_case_14,
            test_mdx_expression_text_case_15,
            test_mdx_expression_text_case_16,
            test_mdx_expression_text_case_17,
            test_mdx_expression_text_case_18,
            test_mdx_expression_text_case_19,
            test_mdx_expression_text_case_20,
            test_mdx_expression_text_case_21,
            test_mdx_expression_text_case_22,
            test_mdx_expression_text_case_23,
            test_mdx_expression_text_case_24,
            test_mdx_expression_text_case_25,
            test_mdx_expression_text_case_26,
            test_mdx_expression_text_case_27,
            test_mdx_expression_text_case_28,
            test_mdx_expression_text_case_29,
            test_mdx_expression_text_case_30,
            test_mdx_expression_text_case_31,
            test_mdx_expression_text_case_32,
            test_mdx_expression_text_case_33,
            test_mdx_expression_text_case_34,
            test_mdx_expression_text_case_35,
            test_mdx_expression_text_case_36,
            test_mdx_expression_text_case_37,
            test_mdx_expression_text_case_38,
            test_mdx_expression_text_case_39
        ]}
    ].

-spec init_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:init_per_suite().
init_per_suite(Config) ->
    Config.

-spec end_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:end_per_suite().
end_per_suite(_Config) ->
    ok.

-spec init_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:init_per_group().
init_per_group(_Group, Config) ->
    Config.

-spec end_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:end_per_group().
end_per_group(_Group, _Config) ->
    ok.

%%%=============================================================================
%%% Test Cases
%%%=============================================================================

-spec test_mdx_expression_text_case_1(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_1(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a  b</p>"/utf8>>},
        markdown:to_html_with_options(<<"a {} b"/utf8>>, ?swc),
        "should support an empty expression (1)"
    ),
    ok.

-spec test_mdx_expression_text_case_2(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_2(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a  b</p>"/utf8>>},
        markdown:to_html_with_options(<<"a { \t\r\n} b"/utf8>>, ?swc),
        "should support an empty expression (2)"
    ),
    ok.

-spec test_mdx_expression_text_case_3(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_3(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a  b</p>"/utf8>>},
        markdown:to_html_with_options(<<"a {/**/} b"/utf8>>, ?swc),
        "should support a multiline comment (1)"
    ),
    ok.

-spec test_mdx_expression_text_case_4(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_4(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a  b</p>"/utf8>>},
        markdown:to_html_with_options(<<"a {  /*\n*/\t} b"/utf8>>, ?swc),
        "should support a multiline comment (2)"
    ),
    ok.

-spec test_mdx_expression_text_case_5(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_5(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a  d</p>"/utf8>>},
        markdown:to_html_with_options(<<"a {/*b*//*c*/} d"/utf8>>, ?swc),
        "should support a multiline comment (3)"
    ),
    ok.

-spec test_mdx_expression_text_case_6(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_6(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a  d</p>"/utf8>>},
        markdown:to_html_with_options(<<"a {b/*c*/} d"/utf8>>, ?swc),
        "should support a multiline comment (4)"
    ),
    ok.

-spec test_mdx_expression_text_case_7(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_7(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a  d</p>"/utf8>>},
        markdown:to_html_with_options(<<"a {/*b*/c} d"/utf8>>, ?swc),
        "should support a multiline comment (5)"
    ),
    ok.

-spec test_mdx_expression_text_case_8(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_8(_Config) ->
    ?assertMatch(
        {ok, <<"1:9: Could not parse expression with swc: Unexpected eof (mdx:swc)"/utf8>>},
        markdown:to_html_with_options(<<"a {//} b"/utf8>>, ?swc),
        "should crash on an incorrect line comment (1)"
    ),
    ok.

-spec test_mdx_expression_text_case_9(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_9(_Config) ->
    ?assertMatch(
        {ok, <<"1:13: Could not parse expression with swc: Unexpected eof (mdx:swc)"/utf8>>},
        markdown:to_html_with_options(<<"a { // b } c"/utf8>>, ?swc),
        "should crash on an incorrect line comment (2)"
    ),
    ok.

-spec test_mdx_expression_text_case_10(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_10(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a  b</p>"/utf8>>},
        markdown:to_html_with_options(<<"a {//\n} b"/utf8>>, ?swc),
        "should support a line comment followed by a line ending"
    ),
    ok.

-spec test_mdx_expression_text_case_11(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_11(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a  d</p>"/utf8>>},
        markdown:to_html_with_options(<<"a {// b\nc} d"/utf8>>, ?swc),
        "should support a line comment followed by a line ending and an expression"
    ),
    ok.

-spec test_mdx_expression_text_case_12(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_12(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a  d</p>"/utf8>>},
        markdown:to_html_with_options(<<"a {b// c\n} d"/utf8>>, ?swc),
        "should support an expression followed by a line comment and a line ending"
    ),
    ok.

-spec test_mdx_expression_text_case_13(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_13(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a  d</p>"/utf8>>},
        markdown:to_html_with_options(<<"a {/*b*/ // c\n} d"/utf8>>, ?swc),
        "should support comments"
    ),
    ok.

-spec test_mdx_expression_text_case_14(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_14(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a  d</p>"/utf8>>},
        markdown:to_html_with_options(<<"a {b.c} d"/utf8>>, ?swc),
        "should support expression statements (1)"
    ),
    ok.

-spec test_mdx_expression_text_case_15(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_15(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a  b</p>"/utf8>>},
        markdown:to_html_with_options(<<"a {1 + 1} b"/utf8>>, ?swc),
        "should support expression statements (2)"
    ),
    ok.

-spec test_mdx_expression_text_case_16(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_16(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a  b</p>"/utf8>>},
        markdown:to_html_with_options(<<"a {function () {}} b"/utf8>>, ?swc),
        "should support expression statements (3)"
    ),
    ok.

-spec test_mdx_expression_text_case_17(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_17(_Config) ->
    ?assertMatch(
        {ok, <<"1:4: Could not parse expression with swc: Expression expected (mdx:swc)"/utf8>>},
        markdown:to_html_with_options(<<"a {var b = \"c\"} d"/utf8>>, ?swc),
        "should crash on non-expressions"
    ),
    ok.

-spec test_mdx_expression_text_case_18(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_18(_Config) ->
    ?assertMatch(
        {ok, <<"<blockquote>\n<p>a  c</p>\n</blockquote>"/utf8>>},
        markdown:to_html_with_options(<<"> a {\n> b} c"/utf8>>, ?swc),
        "should support expressions in containers"
    ),
    ok.

-spec test_mdx_expression_text_case_19(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_19(_Config) ->
    ?assertMatch(
        {ok, <<"2:8: Could not parse expression with swc: Unexpected eof (mdx:swc)"/utf8>>},
        markdown:to_html_with_options(<<"> a {\n> b<} c"/utf8>>, ?swc),
        "should crash on incorrect expressions in containers (1)"
    ),
    ok.

-spec test_mdx_expression_text_case_20(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_20(_Config) ->
    ?assertMatch(
        {ok, <<"3:7: Could not parse expression with swc: Unexpected content after expression (mdx:swc)"/utf8>>},
        markdown:to_html_with_options(<<"> a {\n> b\n> c} d"/utf8>>, ?swc),
        "should crash on incorrect expressions in containers (2)"
    ),
    ok.

-spec test_mdx_expression_text_case_21(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_21(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a  c</p>"/utf8>>},
        markdown:to_html_with_options(<<"a {b} c"/utf8>>, ?mdx),
        "should support an expression"
    ),
    ok.

-spec test_mdx_expression_text_case_22(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_22(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a  b</p>"/utf8>>},
        markdown:to_html_with_options(<<"a {} b"/utf8>>, ?mdx),
        "should support an empty expression"
    ),
    ok.

-spec test_mdx_expression_text_case_23(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_23(_Config) ->
    ?assertMatch(
        {ok,
            <<"1:7: Unexpected end of file in expression, expected a corresponding closing brace for `{` (erlang-markdown:unexpected-eof)"/utf8>>},
        markdown:to_html_with_options(<<"a {b c"/utf8>>, ?mdx),
        "should crash if no closing brace is found (1)"
    ),
    ok.

-spec test_mdx_expression_text_case_24(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_24(_Config) ->
    ?assertMatch(
        {ok,
            <<"1:13: Unexpected end of file in expression, expected a corresponding closing brace for `{` (erlang-markdown:unexpected-eof)"/utf8>>},
        markdown:to_html_with_options(<<"a {b { c } d"/utf8>>, ?mdx),
        "should crash if no closing brace is found (2)"
    ),
    ok.

-spec test_mdx_expression_text_case_25(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_25(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a  b</p>"/utf8>>},
        markdown:to_html_with_options(<<"a {\n} b"/utf8>>, ?mdx),
        "should support a line ending in an expression"
    ),
    ok.

-spec test_mdx_expression_text_case_26(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_26(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a } b</p>"/utf8>>},
        markdown:to_html_with_options(<<"a } b"/utf8>>, ?mdx),
        "should support just a closing brace"
    ),
    ok.

-spec test_mdx_expression_text_case_27(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_27(_Config) ->
    ?assertMatch(
        {ok, <<"<p> b</p>"/utf8>>},
        markdown:to_html_with_options(<<"{ a } b"/utf8>>, ?mdx),
        "should support expressions as the first thing when following by other things"
    ),
    ok.

-spec test_mdx_expression_text_case_28(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_28(_Config) ->
    ?assertEqual(
        {ok,
            markdown_mdast_node:root(#markdown_mdast_root{
                children = ?'vec!'([
                    markdown_mdast_node:paragraph(#markdown_mdast_paragraph{
                        children = ?'vec!'([
                            markdown_mdast_node:text(#markdown_mdast_text{
                                value = <<"a ">>,
                                position = {some, markdown_unist_position:new(1, 1, 0, 1, 3, 2)}
                            }),
                            markdown_mdast_node:mdx_text_expression(#markdown_mdast_mdx_text_expression{
                                value = <<"alpha">>,
                                position = {some, markdown_unist_position:new(1, 3, 2, 1, 10, 9)},
                                stops = ?'vec!'([markdown_mdast_stop:new(0, 3)])
                            }),
                            markdown_mdast_node:text(#markdown_mdast_text{
                                value = <<" b.">>,
                                position = {some, markdown_unist_position:new(1, 10, 9, 1, 13, 12)}
                            })
                        ]),
                        position = {some, markdown_unist_position:new(1, 1, 0, 1, 13, 12)}
                    })
                ]),
                position = {some, markdown_unist_position:new(1, 1, 0, 1, 13, 12)}
            })},
        markdown:to_mdast(<<"a {alpha} b."/utf8>>, ?mdx_parse),
        "should support mdx expressions (text) as `MdxTextExpression`s in mdast"
    ),
    ok.

-spec test_mdx_expression_text_case_29(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_29(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a  c</p>"/utf8>>},
        markdown:to_html_with_options(<<"a {b} c"/utf8>>, ?swc),
        "should support an expression"
    ),
    ok.

-spec test_mdx_expression_text_case_30(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_30(_Config) ->
    ?assertMatch(
        {ok, <<"1:9: Could not parse expression with swc: Unexpected eof (mdx:swc)"/utf8>>},
        markdown:to_html_with_options(<<"a {??} b"/utf8>>, ?swc),
        "should crash on an incorrect expression"
    ),
    ok.

-spec test_mdx_expression_text_case_31(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_31(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a  b</p>"/utf8>>},
        markdown:to_html_with_options(<<"a {} b"/utf8>>, ?swc),
        "should support an empty expression"
    ),
    ok.

-spec test_mdx_expression_text_case_32(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_32(_Config) ->
    ?assertMatch(
        {ok,
            <<"1:7: Unexpected end of file in expression, expected a corresponding closing brace for `{` (erlang-markdown:unexpected-eof)"/utf8>>},
        markdown:to_html_with_options(<<"a {b c"/utf8>>, ?swc),
        "should crash if no closing brace is found (1)"
    ),
    ok.

-spec test_mdx_expression_text_case_33(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_33(_Config) ->
    ?assertMatch(
        {ok, <<"1:13: Could not parse expression with swc: Unexpected content after expression (mdx:swc)"/utf8>>},
        markdown:to_html_with_options(<<"a {b { c } d"/utf8>>, ?swc),
        "should crash if no closing brace is found (2)"
    ),
    ok.

-spec test_mdx_expression_text_case_34(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_34(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a  b</p>"/utf8>>},
        markdown:to_html_with_options(<<"a {\n} b"/utf8>>, ?swc),
        "should support a line ending in an expression"
    ),
    ok.

-spec test_mdx_expression_text_case_35(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_35(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a } b</p>"/utf8>>},
        markdown:to_html_with_options(<<"a } b"/utf8>>, ?swc),
        "should support just a closing brace"
    ),
    ok.

-spec test_mdx_expression_text_case_36(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_36(_Config) ->
    ?assertMatch(
        {ok, <<"<p> b</p>"/utf8>>},
        markdown:to_html_with_options(<<"{ a } b"/utf8>>, ?swc),
        "should support expressions as the first thing when following by other things"
    ),
    ok.

-spec test_mdx_expression_text_case_37(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_37(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a  b</p>"/utf8>>},
        markdown:to_html_with_options(<<"a { /* { */ } b"/utf8>>, ?swc),
        "should support an unbalanced opening brace (if JS permits)"
    ),
    ok.

-spec test_mdx_expression_text_case_38(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_38(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a  b</p>"/utf8>>},
        markdown:to_html_with_options(<<"a { /* } */ } b"/utf8>>, ?swc),
        "should support an unbalanced closing brace (if JS permits)"
    ),
    ok.

-spec test_mdx_expression_text_case_39(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_text_case_39(_Config) ->
    ?assertEqual(
        {ok,
            markdown_mdast_node:root(#markdown_mdast_root{
                children = ?'vec!'([
                    markdown_mdast_node:blockquote(#markdown_mdast_blockquote{
                        children = ?'vec!'([
                            markdown_mdast_node:paragraph(#markdown_mdast_paragraph{
                                children = ?'vec!'([
                                    markdown_mdast_node:text(#markdown_mdast_text{
                                        value = <<"alpha ">>,
                                        position = {some, markdown_unist_position:new(1, 3, 2, 1, 9, 8)}
                                    }),
                                    markdown_mdast_node:mdx_text_expression(#markdown_mdast_mdx_text_expression{
                                        value = <<"`\nbravo\ncharlie\ndelta\n echo\n`">>,
                                        position = {some, markdown_unist_position:new(1, 9, 8, 6, 5, 54)},
                                        stops = ?'vec!'([
                                            markdown_mdast_stop:new(0, 9),
                                            markdown_mdast_stop:new(1, 10),
                                            markdown_mdast_stop:new(2, 13),
                                            markdown_mdast_stop:new(7, 18),
                                            markdown_mdast_stop:new(8, 22),
                                            markdown_mdast_stop:new(15, 29),
                                            markdown_mdast_stop:new(16, 34),
                                            markdown_mdast_stop:new(21, 39),
                                            markdown_mdast_stop:new(22, 44),
                                            markdown_mdast_stop:new(27, 49),
                                            markdown_mdast_stop:new(28, 52)
                                        ])
                                    }),
                                    markdown_mdast_node:text(#markdown_mdast_text{
                                        value = <<" foxtrot.">>,
                                        position = {some, markdown_unist_position:new(6, 5, 54, 6, 14, 63)}
                                    })
                                ]),
                                position = {some, markdown_unist_position:new(1, 3, 2, 6, 14, 63)}
                            })
                        ]),
                        position = {some, markdown_unist_position:new(1, 1, 0, 6, 14, 63)}
                    })
                ]),
                position = {some, markdown_unist_position:new(1, 1, 0, 6, 14, 63)}
            })},
        markdown:to_mdast(<<"> alpha {`\n> bravo\n>  charlie\n>   delta\n>    echo\n> `} foxtrot."/utf8>>, ?swc_parse),
        "should keep the correct number of spaces in a blockquote (text)"
    ),
    ok.
