%%% % DO NOT EDIT: this file was generated by 'just codegen'
%%% % @generated SignedSource<<c155614cb6953e656601bbfeca409c1c>>
%%%-----------------------------------------------------------------------------
%%% %CopyrightBegin%
%%%
%%% SPDX-License-Identifier: Apache-2.0
%%%
%%% Copyright (c) Meta Platforms, Inc. and affiliates.
%%% Copyright (c) WhatsApp LLC
%%%
%%% Licensed under the Apache License, Version 2.0 (the "License");
%%% you may not use this file except in compliance with the License.
%%% You may obtain a copy of the License at
%%%
%%%     http://www.apache.org/licenses/LICENSE-2.0
%%%
%%% Unless required by applicable law or agreed to in writing, software
%%% distributed under the License is distributed on an "AS IS" BASIS,
%%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%%% See the License for the specific language governing permissions and
%%% limitations under the License.
%%%
%%% %CopyrightEnd%
%%%-----------------------------------------------------------------------------
%%% % @format
-module(markdown_misc_tabs_SUITE).
-moduledoc """

""".
-moduledoc #{author => ["Andrew Bennett <potatosaladx@meta.com>"]}.
-moduledoc #{created => "", modified => ""}.
-moduledoc #{copyright => "Meta Platforms, Inc. and affiliates."}.
-compile(warn_missing_spec_all).
-oncall("whatsapp_clr").

-include_lib("markdown/include/markdown_mdast.hrl").
-include_lib("markdown/include/markdown_util.hrl").
-include_lib("stdlib/include/assert.hrl").

-behaviour(ct_suite).

%% ct_suite callbacks
-export([
    all/0,
    groups/0,
    init_per_suite/1,
    end_per_suite/1,
    init_per_group/2,
    end_per_group/2
]).

%% Test Cases
-export([
    test_misc_tabs_case_1/1,
    test_misc_tabs_case_2/1,
    test_misc_tabs_case_3/1,
    test_misc_tabs_case_4/1,
    test_misc_tabs_case_5/1,
    test_misc_tabs_case_6/1,
    test_misc_tabs_case_7/1,
    test_misc_tabs_case_8/1,
    test_misc_tabs_case_9/1,
    test_misc_tabs_case_10/1,
    test_misc_tabs_case_11/1,
    test_misc_tabs_case_12/1,
    test_misc_tabs_case_13/1,
    test_misc_tabs_case_14/1,
    test_misc_tabs_case_15/1,
    test_misc_tabs_case_16/1,
    test_misc_tabs_case_17/1,
    test_misc_tabs_case_18/1,
    test_misc_tabs_case_19/1,
    test_misc_tabs_case_20/1,
    test_misc_tabs_case_21/1,
    test_misc_tabs_case_22/1,
    test_misc_tabs_case_23/1,
    test_misc_tabs_case_24/1,
    test_misc_tabs_case_25/1,
    test_misc_tabs_case_26/1,
    test_misc_tabs_case_27/1,
    test_misc_tabs_case_28/1,
    test_misc_tabs_case_29/1,
    test_misc_tabs_case_30/1,
    test_misc_tabs_case_31/1,
    test_misc_tabs_case_32/1,
    test_misc_tabs_case_33/1,
    test_misc_tabs_case_34/1,
    test_misc_tabs_case_35/1,
    test_misc_tabs_case_36/1,
    test_misc_tabs_case_37/1,
    test_misc_tabs_case_38/1,
    test_misc_tabs_case_39/1,
    test_misc_tabs_case_40/1,
    test_misc_tabs_case_41/1,
    test_misc_tabs_case_42/1,
    test_misc_tabs_case_43/1,
    test_misc_tabs_case_44/1
]).

%% Macros
-define(danger, markdown_options:new(#{compile => #{allow_dangerous_html => true, allow_dangerous_protocol => true}})).

%%%=============================================================================
%%% ct_suite callbacks
%%%=============================================================================

-spec all() -> markdown_test:all().
all() ->
    [
        {group, static}
    ].

-spec groups() -> markdown_test:groups().
groups() ->
    [
        {static, [parallel], [
            test_misc_tabs_case_1,
            test_misc_tabs_case_2,
            test_misc_tabs_case_3,
            test_misc_tabs_case_4,
            test_misc_tabs_case_5,
            test_misc_tabs_case_6,
            test_misc_tabs_case_7,
            test_misc_tabs_case_8,
            test_misc_tabs_case_9,
            test_misc_tabs_case_10,
            test_misc_tabs_case_11,
            test_misc_tabs_case_12,
            test_misc_tabs_case_13,
            test_misc_tabs_case_14,
            test_misc_tabs_case_15,
            test_misc_tabs_case_16,
            test_misc_tabs_case_17,
            test_misc_tabs_case_18,
            test_misc_tabs_case_19,
            test_misc_tabs_case_20,
            test_misc_tabs_case_21,
            test_misc_tabs_case_22,
            test_misc_tabs_case_23,
            test_misc_tabs_case_24,
            test_misc_tabs_case_25,
            test_misc_tabs_case_26,
            test_misc_tabs_case_27,
            test_misc_tabs_case_28,
            test_misc_tabs_case_29,
            test_misc_tabs_case_30,
            test_misc_tabs_case_31,
            test_misc_tabs_case_32,
            test_misc_tabs_case_33,
            test_misc_tabs_case_34,
            test_misc_tabs_case_35,
            test_misc_tabs_case_36,
            test_misc_tabs_case_37,
            test_misc_tabs_case_38,
            test_misc_tabs_case_39,
            test_misc_tabs_case_40,
            test_misc_tabs_case_41,
            test_misc_tabs_case_42,
            test_misc_tabs_case_43,
            test_misc_tabs_case_44
        ]}
    ].

-spec init_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:init_per_suite().
init_per_suite(Config) ->
    Config.

-spec end_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:end_per_suite().
end_per_suite(_Config) ->
    ok.

-spec init_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:init_per_group().
init_per_group(_Group, Config) ->
    Config.

-spec end_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:end_per_group().
end_per_group(_Group, _Config) ->
    ok.

%%%=============================================================================
%%% Test Cases
%%%=============================================================================

-spec test_misc_tabs_case_1(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_1(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code>x\n</code></pre>"/utf8>>},
        markdown:to_html(<<"    x"/utf8>>),
        "should support a 4*SP to start code"
    ),
    ok.

-spec test_misc_tabs_case_2(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_2(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code>x\n</code></pre>"/utf8>>},
        markdown:to_html(<<"\tx"/utf8>>),
        "should support a HT to start code"
    ),
    ok.

-spec test_misc_tabs_case_3(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_3(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code>x\n</code></pre>"/utf8>>},
        markdown:to_html(<<" \tx"/utf8>>),
        "should support a SP + HT to start code"
    ),
    ok.

-spec test_misc_tabs_case_4(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_4(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code>x\n</code></pre>"/utf8>>},
        markdown:to_html(<<"  \tx"/utf8>>),
        "should support a 2*SP + HT to start code"
    ),
    ok.

-spec test_misc_tabs_case_5(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_5(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code>x\n</code></pre>"/utf8>>},
        markdown:to_html(<<"   \tx"/utf8>>),
        "should support a 3*SP + HT to start code"
    ),
    ok.

-spec test_misc_tabs_case_6(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_6(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code>\tx\n</code></pre>"/utf8>>},
        markdown:to_html(<<"    \tx"/utf8>>),
        "should support a 4*SP to start code, and leave the next HT as code data"
    ),
    ok.

-spec test_misc_tabs_case_7(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_7(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code># x\n</code></pre>"/utf8>>},
        markdown:to_html(<<"   \t# x"/utf8>>),
        "should not support a 3*SP + HT to start an ATX heading"
    ),
    ok.

-spec test_misc_tabs_case_8(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_8(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code>&gt; x\n</code></pre>"/utf8>>},
        markdown:to_html(<<"   \t> x"/utf8>>),
        "should not support a 3*SP + HT to start a block quote"
    ),
    ok.

-spec test_misc_tabs_case_9(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_9(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code>- x\n</code></pre>"/utf8>>},
        markdown:to_html(<<"   \t- x"/utf8>>),
        "should not support a 3*SP + HT to start a list item"
    ),
    ok.

-spec test_misc_tabs_case_10(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_10(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code>---\n</code></pre>"/utf8>>},
        markdown:to_html(<<"   \t---"/utf8>>),
        "should not support a 3*SP + HT to start a thematic break"
    ),
    ok.

-spec test_misc_tabs_case_11(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_11(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code>```\n</code></pre>"/utf8>>},
        markdown:to_html(<<"   \t```"/utf8>>),
        "should not support a 3*SP + HT to start a fenced code"
    ),
    ok.

-spec test_misc_tabs_case_12(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_12(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code>&lt;div&gt;\n</code></pre>"/utf8>>},
        markdown:to_html(<<"   \t<div>"/utf8>>),
        "should not support a 3*SP + HT to start HTML"
    ),
    ok.

-spec test_misc_tabs_case_13(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_13(_Config) ->
    ?assertMatch(
        {ok, <<"<h1>x</h1>"/utf8>>},
        markdown:to_html(<<"#\tx\t#\t"/utf8>>),
        "should support tabs around ATX heading sequences"
    ),
    ok.

-spec test_misc_tabs_case_14(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_14(_Config) ->
    ?assertMatch(
        {ok, <<"<h1>x</h1>"/utf8>>},
        markdown:to_html(<<"#\t\tx\t\t#\t\t"/utf8>>),
        "should support arbitrary tabs around ATX heading sequences"
    ),
    ok.

-spec test_misc_tabs_case_15(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_15(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code class=\"language-x\"></code></pre>"/utf8>>},
        markdown:to_html(<<"```\tx\ty\t\n```\t"/utf8>>),
        "should support tabs around fenced code fences, info, and meta"
    ),
    ok.

-spec test_misc_tabs_case_16(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_16(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code class=\"language-x\"></code></pre>"/utf8>>},
        markdown:to_html(<<"```\t\tx\t\ty\t\t\n```\t\t"/utf8>>),
        "should support arbitrary tabs around fenced code fences, info, and meta"
    ),
    ok.

-spec test_misc_tabs_case_17(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_17(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code class=\"language-x\">\t```\n</code></pre>\n"/utf8>>},
        markdown:to_html(<<"```x\n\t```"/utf8>>),
        "should not support tabs before fenced code closing fences"
    ),
    ok.

-spec test_misc_tabs_case_18(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_18(_Config) ->
    ?assertMatch(
        {ok, <<"<x\ty\tz\t=\t\"\tx\t\">"/utf8>>},
        markdown:to_html_with_options(<<"<x\ty\tz\t=\t\"\tx\t\">"/utf8>>, ?danger),
        "should support tabs in HTML (if whitespace is allowed)"
    ),
    ok.

-spec test_misc_tabs_case_19(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_19(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />"/utf8>>},
        markdown:to_html(<<"*\t*\t*\t"/utf8>>),
        "should support tabs in thematic breaks"
    ),
    ok.

-spec test_misc_tabs_case_20(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_20(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />"/utf8>>},
        markdown:to_html(<<"*\t\t*\t\t*\t\t"/utf8>>),
        "should support arbitrary tabs in thematic breaks"
    ),
    ok.

-spec test_misc_tabs_case_21(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_21(_Config) ->
    ?assertMatch(
        {ok, <<"<p>&lt;http:\t&gt;</p>"/utf8>>},
        markdown:to_html(<<"<http:\t>"/utf8>>),
        "should not support a tab to start an autolink w/ protocol’s rest"
    ),
    ok.

-spec test_misc_tabs_case_22(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_22(_Config) ->
    ?assertMatch(
        {ok, <<"<p>&lt;http:x\t&gt;</p>"/utf8>>},
        markdown:to_html(<<"<http:x\t>"/utf8>>),
        "should not support a tab in an autolink w/ protocol’s rest"
    ),
    ok.

-spec test_misc_tabs_case_23(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_23(_Config) ->
    ?assertMatch(
        {ok, <<"<p>&lt;example\t@x.com&gt;</p>"/utf8>>},
        markdown:to_html(<<"<example\t@x.com>"/utf8>>),
        "should not support a tab in an email autolink’s local part"
    ),
    ok.

-spec test_misc_tabs_case_24(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_24(_Config) ->
    ?assertMatch(
        {ok, <<"<p>&lt;example@x\ty.com&gt;</p>"/utf8>>},
        markdown:to_html(<<"<example@x\ty.com>"/utf8>>),
        "should not support a tab in an email autolink’s label"
    ),
    ok.

-spec test_misc_tabs_case_25(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_25(_Config) ->
    ?assertMatch(
        {ok, <<"<p>\\\tx</p>"/utf8>>},
        markdown:to_html(<<"\\\tx"/utf8>>),
        "should not support character escaped tab"
    ),
    ok.

-spec test_misc_tabs_case_26(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_26(_Config) ->
    ?assertMatch(
        {ok, <<"<p>\t</p>"/utf8>>},
        markdown:to_html(<<"&#9;"/utf8>>),
        "should support character reference resolving to a tab"
    ),
    ok.

-spec test_misc_tabs_case_27(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_27(_Config) ->
    ?assertMatch(
        {ok, <<"<p><code>\tx</code></p>"/utf8>>},
        markdown:to_html(<<"`\tx`"/utf8>>),
        "should support a tab starting code"
    ),
    ok.

-spec test_misc_tabs_case_28(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_28(_Config) ->
    ?assertMatch(
        {ok, <<"<p><code>x\t</code></p>"/utf8>>},
        markdown:to_html(<<"`x\t`"/utf8>>),
        "should support a tab ending code"
    ),
    ok.

-spec test_misc_tabs_case_29(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_29(_Config) ->
    ?assertMatch(
        {ok, <<"<p><code>\tx\t</code></p>"/utf8>>},
        markdown:to_html(<<"`\tx\t`"/utf8>>),
        "should support tabs around code"
    ),
    ok.

-spec test_misc_tabs_case_30(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_30(_Config) ->
    ?assertMatch(
        {ok, <<"<p><code>\tx </code></p>"/utf8>>},
        markdown:to_html(<<"`\tx `"/utf8>>),
        "should support a tab starting, and a space ending, code"
    ),
    ok.

-spec test_misc_tabs_case_31(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_31(_Config) ->
    ?assertMatch(
        {ok, <<"<p><code> x\t</code></p>"/utf8>>},
        markdown:to_html(<<"` x\t`"/utf8>>),
        "should support a space starting, and a tab ending, code"
    ),
    ok.

-spec test_misc_tabs_case_32(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_32(_Config) ->
    %% Note: CM does not strip it in this case. However, that should be a bug there: makes more sense to remove it like trailing spaces.
    ?assertMatch(
        {ok, <<"<p>x\ny</p>"/utf8>>},
        markdown:to_html(<<"x\t\ny"/utf8>>),
        "should support a trailing tab at a line ending in a paragraph"
    ),
    ok.

-spec test_misc_tabs_case_33(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_33(_Config) ->
    ?assertMatch(
        {ok, <<"<p>x\ny</p>"/utf8>>},
        markdown:to_html(<<"x\n\ty"/utf8>>),
        "should support an initial tab after a line ending in a paragraph"
    ),
    ok.

-spec test_misc_tabs_case_34(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_34(_Config) ->
    ?assertMatch(
        {ok, <<"<p>x<a href=\"z\">\ty</a></p>"/utf8>>},
        markdown:to_html(<<"x[\ty](z)"/utf8>>),
        "should support an initial tab in a link label"
    ),
    ok.

-spec test_misc_tabs_case_35(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_35(_Config) ->
    ?assertMatch(
        {ok, <<"<p>x<a href=\"z\">y\t</a></p>"/utf8>>},
        markdown:to_html(<<"x[y\t](z)"/utf8>>),
        "should support a final tab in a link label"
    ),
    ok.

-spec test_misc_tabs_case_36(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_36(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"z\">x\ty</a></p>"/utf8>>},
        markdown:to_html(<<"[x\ty](z)"/utf8>>),
        "should support a tab in a link label"
    ),
    ok.

-spec test_misc_tabs_case_37(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_37(_Config) ->
    %% Note: CM.js bug, see: <https://github.com/commonmark/commonmark.js/issues/191>
    ?assertMatch(
        {ok, <<"<p><a href=\"y\">x</a></p>"/utf8>>},
        markdown:to_html(<<"[x](\ty)"/utf8>>),
        "should support a tab starting a link resource"
    ),
    ok.

-spec test_misc_tabs_case_38(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_38(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"y\">x</a></p>"/utf8>>},
        markdown:to_html(<<"[x](y\t)"/utf8>>),
        "should support a tab ending a link resource"
    ),
    ok.

-spec test_misc_tabs_case_39(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_39(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"y\" title=\"z\">x</a></p>"/utf8>>},
        markdown:to_html(<<"[x](y\t\"z\")"/utf8>>),
        "should support a tab between a link destination and title"
    ),
    ok.

-spec test_misc_tabs_case_40(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_40(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code>\tx\n</code></pre>\n"/utf8>>},
        markdown:to_html(<<"```\n\tx"/utf8>>),
        "should support a tab in fenced code"
    ),
    ok.

-spec test_misc_tabs_case_41(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_41(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code>   x\n</code></pre>\n"/utf8>>},
        markdown:to_html(<<" ```\n\tx"/utf8>>),
        "should strip 1 space from an initial tab in fenced code if the opening fence is indented as such"
    ),
    ok.

-spec test_misc_tabs_case_42(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_42(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code>  x\n</code></pre>\n"/utf8>>},
        markdown:to_html(<<"  ```\n\tx"/utf8>>),
        "should strip 2 spaces from an initial tab in fenced code if the opening fence is indented as such"
    ),
    ok.

-spec test_misc_tabs_case_43(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_43(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code> x\n</code></pre>\n"/utf8>>},
        markdown:to_html(<<"   ```\n\tx"/utf8>>),
        "should strip 3 spaces from an initial tab in fenced code if the opening fence is indented as such"
    ),
    ok.

-spec test_misc_tabs_case_44(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_tabs_case_44(_Config) ->
    %% To do: CM.js does not output the tab before `b`. See if that makes sense?
    %% "<ul>\n<li>\n<p>a</p>\n<p>b</p>\n</li>\n</ul>"
    ?assertMatch(
        {ok, <<"<ul>\n<li>\n<p>a</p>\n<p>\tb</p>\n</li>\n</ul>"/utf8>>},
        markdown:to_html(<<"-\ta\n\n\tb"/utf8>>),
        "should support a part of a tab as a container, and the rest of a tab as flow"
    ),
    ok.
