%%% % DO NOT EDIT: this file was generated by 'just codegen'
%%% % @generated SignedSource<<cb842c9185173253f81947a3ced87b29>>
%%%-----------------------------------------------------------------------------
%%% %CopyrightBegin%
%%%
%%% SPDX-License-Identifier: Apache-2.0
%%%
%%% Copyright (c) Meta Platforms, Inc. and affiliates.
%%% Copyright (c) WhatsApp LLC
%%%
%%% Licensed under the Apache License, Version 2.0 (the "License");
%%% you may not use this file except in compliance with the License.
%%% You may obtain a copy of the License at
%%%
%%%     http://www.apache.org/licenses/LICENSE-2.0
%%%
%%% Unless required by applicable law or agreed to in writing, software
%%% distributed under the License is distributed on an "AS IS" BASIS,
%%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%%% See the License for the specific language governing permissions and
%%% limitations under the License.
%%%
%%% %CopyrightEnd%
%%%-----------------------------------------------------------------------------
%%% % @format
-module(markdown_misc_default_line_ending_SUITE).
-moduledoc """

""".
-moduledoc #{author => ["Andrew Bennett <potatosaladx@meta.com>"]}.
-moduledoc #{created => "", modified => ""}.
-moduledoc #{copyright => "Meta Platforms, Inc. and affiliates."}.
-compile(warn_missing_spec_all).
-oncall("whatsapp_clr").

-include_lib("markdown/include/markdown_mdast.hrl").
-include_lib("markdown/include/markdown_util.hrl").
-include_lib("stdlib/include/assert.hrl").

-behaviour(ct_suite).

%% ct_suite callbacks
-export([
    all/0,
    groups/0,
    init_per_suite/1,
    end_per_suite/1,
    init_per_group/2,
    end_per_group/2
]).

%% Test Cases
-export([
    test_misc_default_line_ending_case_1/1,
    test_misc_default_line_ending_case_2/1,
    test_misc_default_line_ending_case_3/1,
    test_misc_default_line_ending_case_4/1,
    test_misc_default_line_ending_case_5/1,
    test_misc_default_line_ending_case_6/1
]).

%%%=============================================================================
%%% ct_suite callbacks
%%%=============================================================================

-spec all() -> markdown_test:all().
all() ->
    [
        {group, static}
    ].

-spec groups() -> markdown_test:groups().
groups() ->
    [
        {static, [parallel], [
            test_misc_default_line_ending_case_1,
            test_misc_default_line_ending_case_2,
            test_misc_default_line_ending_case_3,
            test_misc_default_line_ending_case_4,
            test_misc_default_line_ending_case_5,
            test_misc_default_line_ending_case_6
        ]}
    ].

-spec init_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:init_per_suite().
init_per_suite(Config) ->
    Config.

-spec end_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:end_per_suite().
end_per_suite(_Config) ->
    ok.

-spec init_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:init_per_group().
init_per_group(_Group, Config) ->
    Config.

-spec end_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:end_per_group().
end_per_group(_Group, _Config) ->
    ok.

%%%=============================================================================
%%% Test Cases
%%%=============================================================================

-spec test_misc_default_line_ending_case_1(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_default_line_ending_case_1(_Config) ->
    ?assertMatch(
        {ok, <<"<blockquote>\n<p>a</p>\n</blockquote>"/utf8>>},
        markdown:to_html(<<"> a"/utf8>>),
        "should use `\\n` default"
    ),
    ok.

-spec test_misc_default_line_ending_case_2(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_default_line_ending_case_2(_Config) ->
    ?assertMatch(
        {ok, <<"<blockquote>\n<p>a</p>\n</blockquote>\n"/utf8>>},
        markdown:to_html(<<"> a\n"/utf8>>),
        "should infer the first line ending (1)"
    ),
    ok.

-spec test_misc_default_line_ending_case_3(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_default_line_ending_case_3(_Config) ->
    ?assertMatch(
        {ok, <<"<blockquote>\r<p>a</p>\r</blockquote>\r"/utf8>>},
        markdown:to_html(<<"> a\r"/utf8>>),
        "should infer the first line ending (2)"
    ),
    ok.

-spec test_misc_default_line_ending_case_4(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_default_line_ending_case_4(_Config) ->
    ?assertMatch(
        {ok, <<"<blockquote>\r\n<p>a</p>\r\n</blockquote>\r\n"/utf8>>},
        markdown:to_html(<<"> a\r\n"/utf8>>),
        "should infer the first line ending (3)"
    ),
    ok.

-spec test_misc_default_line_ending_case_5(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_default_line_ending_case_5(_Config) ->
    ?assertMatch(
        {ok, <<"<blockquote>\r<p>a</p>\r</blockquote>"/utf8>>},
        markdown:to_html_with_options(
            <<"> a"/utf8>>, markdown_options:default(#{compile => #{default_line_ending => carriage_return}})
        ),
        "should support the given line ending"
    ),
    ok.

-spec test_misc_default_line_ending_case_6(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_default_line_ending_case_6(_Config) ->
    ?assertMatch(
        {ok, <<"<blockquote>\n<p>a</p>\n</blockquote>\n"/utf8>>},
        markdown:to_html_with_options(
            <<"> a\n"/utf8>>, markdown_options:default(#{compile => #{default_line_ending => carriage_return}})
        ),
        "should support the given line ending, even if line endings exist"
    ),
    ok.
