%%% % DO NOT EDIT: this file was generated by 'just codegen'
%%% % @generated SignedSource<<b30ea846d7c04c08e1eeb2b062f326f1>>
%%%-----------------------------------------------------------------------------
%%% %CopyrightBegin%
%%%
%%% SPDX-License-Identifier: Apache-2.0
%%%
%%% Copyright (c) Meta Platforms, Inc. and affiliates.
%%% Copyright (c) WhatsApp LLC
%%%
%%% Licensed under the Apache License, Version 2.0 (the "License");
%%% you may not use this file except in compliance with the License.
%%% You may obtain a copy of the License at
%%%
%%%     http://www.apache.org/licenses/LICENSE-2.0
%%%
%%% Unless required by applicable law or agreed to in writing, software
%%% distributed under the License is distributed on an "AS IS" BASIS,
%%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%%% See the License for the specific language governing permissions and
%%% limitations under the License.
%%%
%%% %CopyrightEnd%
%%%-----------------------------------------------------------------------------
%%% % @format
-module(markdown_autolink_SUITE).
-moduledoc """

""".
-moduledoc #{author => ["Andrew Bennett <potatosaladx@meta.com>"]}.
-moduledoc #{created => "", modified => ""}.
-moduledoc #{copyright => "Meta Platforms, Inc. and affiliates."}.
-compile(warn_missing_spec_all).
-oncall("whatsapp_clr").

-include_lib("markdown/include/markdown_mdast.hrl").
-include_lib("markdown/include/markdown_util.hrl").
-include_lib("stdlib/include/assert.hrl").

-behaviour(ct_suite).

%% ct_suite callbacks
-export([
    all/0,
    groups/0,
    init_per_suite/1,
    end_per_suite/1,
    init_per_group/2,
    end_per_group/2
]).

%% Test Cases
-export([
    test_autolink_case_1/1,
    test_autolink_case_2/1,
    test_autolink_case_3/1,
    test_autolink_case_4/1,
    test_autolink_case_5/1,
    test_autolink_case_6/1,
    test_autolink_case_7/1,
    test_autolink_case_8/1,
    test_autolink_case_9/1,
    test_autolink_case_10/1,
    test_autolink_case_11/1,
    test_autolink_case_12/1,
    test_autolink_case_13/1,
    test_autolink_case_14/1,
    test_autolink_case_15/1,
    test_autolink_case_16/1,
    test_autolink_case_17/1,
    test_autolink_case_18/1,
    test_autolink_case_19/1,
    test_autolink_case_20/1,
    test_autolink_case_21/1,
    test_autolink_case_22/1,
    test_autolink_case_23/1,
    test_autolink_case_24/1,
    test_autolink_case_25/1,
    test_autolink_case_26/1,
    test_autolink_case_27/1,
    test_autolink_case_28/1,
    test_autolink_case_29/1,
    test_autolink_case_30/1,
    test_autolink_case_31/1,
    test_autolink_case_32/1,
    test_autolink_case_33/1,
    test_autolink_case_34/1,
    test_autolink_case_35/1,
    test_autolink_case_36/1,
    test_autolink_case_37/1,
    test_autolink_case_38/1,
    test_autolink_case_39/1,
    test_autolink_case_40/1,
    test_autolink_case_41/1,
    test_autolink_case_42/1
]).

%% Macros
-define(danger, markdown_options:new(#{compile => #{allow_dangerous_html => true, allow_dangerous_protocol => true}})).

%%%=============================================================================
%%% ct_suite callbacks
%%%=============================================================================

-spec all() -> markdown_test:all().
all() ->
    [
        {group, static}
    ].

-spec groups() -> markdown_test:groups().
groups() ->
    [
        {static, [parallel], [
            test_autolink_case_1,
            test_autolink_case_2,
            test_autolink_case_3,
            test_autolink_case_4,
            test_autolink_case_5,
            test_autolink_case_6,
            test_autolink_case_7,
            test_autolink_case_8,
            test_autolink_case_9,
            test_autolink_case_10,
            test_autolink_case_11,
            test_autolink_case_12,
            test_autolink_case_13,
            test_autolink_case_14,
            test_autolink_case_15,
            test_autolink_case_16,
            test_autolink_case_17,
            test_autolink_case_18,
            test_autolink_case_19,
            test_autolink_case_20,
            test_autolink_case_21,
            test_autolink_case_22,
            test_autolink_case_23,
            test_autolink_case_24,
            test_autolink_case_25,
            test_autolink_case_26,
            test_autolink_case_27,
            test_autolink_case_28,
            test_autolink_case_29,
            test_autolink_case_30,
            test_autolink_case_31,
            test_autolink_case_32,
            test_autolink_case_33,
            test_autolink_case_34,
            test_autolink_case_35,
            test_autolink_case_36,
            test_autolink_case_37,
            test_autolink_case_38,
            test_autolink_case_39,
            test_autolink_case_40,
            test_autolink_case_41,
            test_autolink_case_42
        ]}
    ].

-spec init_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:init_per_suite().
init_per_suite(Config) ->
    Config.

-spec end_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:end_per_suite().
end_per_suite(_Config) ->
    ok.

-spec init_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:init_per_group().
init_per_group(_Group, Config) ->
    Config.

-spec end_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:end_per_group().
end_per_group(_Group, _Config) ->
    ok.

%%%=============================================================================
%%% Test Cases
%%%=============================================================================

-spec test_autolink_case_1(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_1(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"http://foo.bar.baz\">http://foo.bar.baz</a></p>"/utf8>>},
        markdown:to_html(<<"<http://foo.bar.baz>"/utf8>>),
        "should support protocol autolinks (1)"
    ),
    ok.

-spec test_autolink_case_2(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_2(_Config) ->
    ?assertMatch(
        {ok,
            <<"<p><a href=\"http://foo.bar.baz/test?q=hello&amp;id=22&amp;boolean\">http://foo.bar.baz/test?q=hello&amp;id=22&amp;boolean</a></p>"/utf8>>},
        markdown:to_html(<<"<http://foo.bar.baz/test?q=hello&id=22&boolean>"/utf8>>),
        "should support protocol autolinks (2)"
    ),
    ok.

-spec test_autolink_case_3(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_3(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"irc://foo.bar:2233/baz\">irc://foo.bar:2233/baz</a></p>"/utf8>>},
        markdown:to_html(<<"<irc://foo.bar:2233/baz>"/utf8>>),
        "should support protocol autolinks w/ non-HTTP schemes"
    ),
    ok.

-spec test_autolink_case_4(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_4(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"MAILTO:FOO@BAR.BAZ\">MAILTO:FOO@BAR.BAZ</a></p>"/utf8>>},
        markdown:to_html(<<"<MAILTO:FOO@BAR.BAZ>"/utf8>>),
        "should support protocol autolinks in uppercase"
    ),
    ok.

-spec test_autolink_case_5(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_5(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"\">a+b+c:d</a></p>"/utf8>>},
        markdown:to_html(<<"<a+b+c:d>"/utf8>>),
        "should support protocol autolinks w/ incorrect URIs (1, default)"
    ),
    ok.

-spec test_autolink_case_6(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_6(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"a+b+c:d\">a+b+c:d</a></p>"/utf8>>},
        markdown:to_html_with_options(<<"<a+b+c:d>"/utf8>>, ?danger),
        "should support protocol autolinks w/ incorrect URIs (1, danger)"
    ),
    ok.

-spec test_autolink_case_7(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_7(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"\">made-up-scheme://foo,bar</a></p>"/utf8>>},
        markdown:to_html(<<"<made-up-scheme://foo,bar>"/utf8>>),
        "should support protocol autolinks w/ incorrect URIs (2, default)"
    ),
    ok.

-spec test_autolink_case_8(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_8(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"made-up-scheme://foo,bar\">made-up-scheme://foo,bar</a></p>"/utf8>>},
        markdown:to_html_with_options(<<"<made-up-scheme://foo,bar>"/utf8>>, ?danger),
        "should support protocol autolinks w/ incorrect URIs (2, danger)"
    ),
    ok.

-spec test_autolink_case_9(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_9(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"http://../\">http://../</a></p>"/utf8>>},
        markdown:to_html(<<"<http://../>"/utf8>>),
        "should support protocol autolinks w/ incorrect URIs (3)"
    ),
    ok.

-spec test_autolink_case_10(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_10(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"localhost:5001/foo\">localhost:5001/foo</a></p>"/utf8>>},
        markdown:to_html_with_options(<<"<localhost:5001/foo>"/utf8>>, ?danger),
        "should support protocol autolinks w/ incorrect URIs (4)"
    ),
    ok.

-spec test_autolink_case_11(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_11(_Config) ->
    ?assertMatch(
        {ok, <<"<p>&lt;http://foo.bar/baz bim&gt;</p>"/utf8>>},
        markdown:to_html(<<"<http://foo.bar/baz bim>"/utf8>>),
        "should not support protocol autolinks w/ spaces"
    ),
    ok.

-spec test_autolink_case_12(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_12(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"http://example.com/%5C%5B%5C\">http://example.com/\\[\\</a></p>"/utf8>>},
        markdown:to_html(<<"<http://example.com/\\[\\>"/utf8>>),
        "should not support character escapes in protocol autolinks"
    ),
    ok.

-spec test_autolink_case_13(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_13(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"mailto:foo@bar.example.com\">foo@bar.example.com</a></p>"/utf8>>},
        markdown:to_html(<<"<foo@bar.example.com>"/utf8>>),
        "should support email autolinks (1)"
    ),
    ok.

-spec test_autolink_case_14(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_14(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"mailto:foo+special@Bar.baz-bar0.com\">foo+special@Bar.baz-bar0.com</a></p>"/utf8>>},
        markdown:to_html(<<"<foo+special@Bar.baz-bar0.com>"/utf8>>),
        "should support email autolinks (2)"
    ),
    ok.

-spec test_autolink_case_15(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_15(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"mailto:a@b.c\">a@b.c</a></p>"/utf8>>},
        markdown:to_html(<<"<a@b.c>"/utf8>>),
        "should support email autolinks (3)"
    ),
    ok.

-spec test_autolink_case_16(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_16(_Config) ->
    ?assertMatch(
        {ok, <<"<p>&lt;foo+@bar.example.com&gt;</p>"/utf8>>},
        markdown:to_html(<<"<foo\\+@bar.example.com>"/utf8>>),
        "should not support character escapes in email autolinks"
    ),
    ok.

-spec test_autolink_case_17(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_17(_Config) ->
    ?assertMatch(
        {ok, <<"<p>&lt;&gt;</p>"/utf8>>},
        markdown:to_html(<<"<>"/utf8>>),
        "should not support empty autolinks"
    ),
    ok.

-spec test_autolink_case_18(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_18(_Config) ->
    ?assertMatch(
        {ok, <<"<p>&lt; http://foo.bar &gt;</p>"/utf8>>},
        markdown:to_html(<<"< http://foo.bar >"/utf8>>),
        "should not support autolinks w/ space"
    ),
    ok.

-spec test_autolink_case_19(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_19(_Config) ->
    ?assertMatch(
        {ok, <<"<p>&lt;m:abc&gt;</p>"/utf8>>},
        markdown:to_html(<<"<m:abc>"/utf8>>),
        "should not support autolinks w/ a single character for a scheme"
    ),
    ok.

-spec test_autolink_case_20(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_20(_Config) ->
    ?assertMatch(
        {ok, <<"<p>&lt;foo.bar.baz&gt;</p>"/utf8>>},
        markdown:to_html(<<"<foo.bar.baz>"/utf8>>),
        "should not support autolinks w/o a colon or at sign"
    ),
    ok.

-spec test_autolink_case_21(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_21(_Config) ->
    ?assertMatch(
        {ok, <<"<p>http://example.com</p>"/utf8>>},
        markdown:to_html(<<"http://example.com"/utf8>>),
        "should not support protocol autolinks w/o angle brackets"
    ),
    ok.

-spec test_autolink_case_22(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_22(_Config) ->
    ?assertMatch(
        {ok, <<"<p>foo@bar.example.com</p>"/utf8>>},
        markdown:to_html(<<"foo@bar.example.com"/utf8>>),
        "should not support email autolinks w/o angle brackets"
    ),
    ok.

-spec test_autolink_case_23(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_23(_Config) ->
    %% Extra:
    ?assertMatch(
        {ok, <<"<p><a href=\"mailto:*@example.com\">*@example.com</a></p>"/utf8>>},
        markdown:to_html(<<"<*@example.com>"/utf8>>),
        "should support autolinks w/ atext (1)"
    ),
    ok.

-spec test_autolink_case_24(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_24(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"mailto:a*@example.com\">a*@example.com</a></p>"/utf8>>},
        markdown:to_html(<<"<a*@example.com>"/utf8>>),
        "should support autolinks w/ atext (2)"
    ),
    ok.

-spec test_autolink_case_25(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_25(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"mailto:aa*@example.com\">aa*@example.com</a></p>"/utf8>>},
        markdown:to_html(<<"<aa*@example.com>"/utf8>>),
        "should support autolinks w/ atext (3)"
    ),
    ok.

-spec test_autolink_case_26(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_26(_Config) ->
    ?assertMatch(
        {ok, <<"<p>&lt;aaa©@example.com&gt;</p>"/utf8>>},
        markdown:to_html(<<"<aaa©@example.com>"/utf8>>),
        "should support non-atext in email autolinks local part (1)"
    ),
    ok.

-spec test_autolink_case_27(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_27(_Config) ->
    ?assertMatch(
        {ok, <<"<p>&lt;a*a©@example.com&gt;</p>"/utf8>>},
        markdown:to_html(<<"<a*a©@example.com>"/utf8>>),
        "should support non-atext in email autolinks local part (2)"
    ),
    ok.

-spec test_autolink_case_28(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_28(_Config) ->
    ?assertMatch(
        {ok, <<"<p>&lt;asd@.example.com&gt;</p>"/utf8>>},
        markdown:to_html(<<"<asd@.example.com>"/utf8>>),
        "should not support a dot after an at sign in email autolinks"
    ),
    ok.

-spec test_autolink_case_29(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_29(_Config) ->
    ?assertMatch(
        {ok, <<"<p>&lt;asd@e..xample.com&gt;</p>"/utf8>>},
        markdown:to_html(<<"<asd@e..xample.com>"/utf8>>),
        "should not support a dot after another dot in email autolinks"
    ),
    ok.

-spec test_autolink_case_30(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_30(_Config) ->
    ?assertMatch(
        {ok,
            <<"<p><a href=\"mailto:asd@012345678901234567890123456789012345678901234567890123456789012\">asd@012345678901234567890123456789012345678901234567890123456789012</a></p>"/utf8>>},
        markdown:to_html(<<"<asd@012345678901234567890123456789012345678901234567890123456789012>"/utf8>>),
        "should support 63 character in email autolinks domains"
    ),
    ok.

-spec test_autolink_case_31(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_31(_Config) ->
    ?assertMatch(
        {ok, <<"<p>&lt;asd@0123456789012345678901234567890123456789012345678901234567890123&gt;</p>"/utf8>>},
        markdown:to_html(<<"<asd@0123456789012345678901234567890123456789012345678901234567890123>"/utf8>>),
        "should not support 64 character in email autolinks domains"
    ),
    ok.

-spec test_autolink_case_32(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_32(_Config) ->
    ?assertMatch(
        {ok,
            <<"<p><a href=\"mailto:asd@012345678901234567890123456789012345678901234567890123456789012.a\">asd@012345678901234567890123456789012345678901234567890123456789012.a</a></p>"/utf8>>},
        markdown:to_html(<<"<asd@012345678901234567890123456789012345678901234567890123456789012.a>"/utf8>>),
        "should support a TLD after a 63 character domain in email autolinks"
    ),
    ok.

-spec test_autolink_case_33(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_33(_Config) ->
    ?assertMatch(
        {ok, <<"<p>&lt;asd@0123456789012345678901234567890123456789012345678901234567890123.a&gt;</p>"/utf8>>},
        markdown:to_html(<<"<asd@0123456789012345678901234567890123456789012345678901234567890123.a>"/utf8>>),
        "should not support a TLD after a 64 character domain in email autolinks"
    ),
    ok.

-spec test_autolink_case_34(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_34(_Config) ->
    ?assertMatch(
        {ok,
            <<"<p><a href=\"mailto:asd@a.012345678901234567890123456789012345678901234567890123456789012\">asd@a.012345678901234567890123456789012345678901234567890123456789012</a></p>"/utf8>>},
        markdown:to_html(<<"<asd@a.012345678901234567890123456789012345678901234567890123456789012>"/utf8>>),
        "should support a 63 character TLD in email autolinks"
    ),
    ok.

-spec test_autolink_case_35(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_35(_Config) ->
    ?assertMatch(
        {ok, <<"<p>&lt;asd@a.0123456789012345678901234567890123456789012345678901234567890123&gt;</p>"/utf8>>},
        markdown:to_html(<<"<asd@a.0123456789012345678901234567890123456789012345678901234567890123>"/utf8>>),
        "should not support a 64 character TLD in email autolinks"
    ),
    ok.

-spec test_autolink_case_36(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_36(_Config) ->
    ?assertMatch(
        {ok, <<"<p>&lt;asd@-example.com&gt;</p>"/utf8>>},
        markdown:to_html(<<"<asd@-example.com>"/utf8>>),
        "should not support a dash after `@` in email autolinks"
    ),
    ok.

-spec test_autolink_case_37(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_37(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"mailto:asd@e-xample.com\">asd@e-xample.com</a></p>"/utf8>>},
        markdown:to_html(<<"<asd@e-xample.com>"/utf8>>),
        "should support a dash after other domain characters in email autolinks"
    ),
    ok.

-spec test_autolink_case_38(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_38(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"mailto:asd@e--xample.com\">asd@e--xample.com</a></p>"/utf8>>},
        markdown:to_html(<<"<asd@e--xample.com>"/utf8>>),
        "should support a dash after another dash in email autolinks"
    ),
    ok.

-spec test_autolink_case_39(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_39(_Config) ->
    ?assertMatch(
        {ok, <<"<p>&lt;asd@example-.com&gt;</p>"/utf8>>},
        markdown:to_html(<<"<asd@example-.com>"/utf8>>),
        "should not support a dash before a dot in email autolinks"
    ),
    ok.

-spec test_autolink_case_40(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_40(_Config) ->
    ?assertMatch(
        {ok, <<"<p>&lt;@example.com&gt;</p>"/utf8>>},
        markdown:to_html(<<"<@example.com>"/utf8>>),
        "should not support an at sign at the start of email autolinks"
    ),
    ok.

-spec test_autolink_case_41(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_41(_Config) ->
    ?assertMatch(
        {ok, <<"<p>&lt;a@b.co&gt;</p>"/utf8>>},
        markdown:to_html_with_options(
            <<"<a@b.co>"/utf8>>, markdown_options:new(#{parse => #{constructs => #{autolink => false}}})
        ),
        "should support turning off autolinks"
    ),
    ok.

-spec test_autolink_case_42(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_autolink_case_42(_Config) ->
    ?assertEqual(
        {ok,
            markdown_mdast_node:root(#markdown_mdast_root{
                children = ?'vec!'([
                    markdown_mdast_node:paragraph(#markdown_mdast_paragraph{
                        children = ?'vec!'([
                            markdown_mdast_node:text(#markdown_mdast_text{
                                value = <<"a ">>,
                                position = {some, markdown_unist_position:new(1, 1, 0, 1, 3, 2)}
                            }),
                            markdown_mdast_node:link(#markdown_mdast_link{
                                url = <<"https://alpha.com">>,
                                title = none,
                                children = ?'vec!'([
                                    markdown_mdast_node:text(#markdown_mdast_text{
                                        value = <<"https://alpha.com">>,
                                        position = {some, markdown_unist_position:new(1, 4, 3, 1, 21, 20)}
                                    })
                                ]),
                                position = {some, markdown_unist_position:new(1, 3, 2, 1, 22, 21)}
                            }),
                            markdown_mdast_node:text(#markdown_mdast_text{
                                value = <<" b ">>,
                                position = {some, markdown_unist_position:new(1, 22, 21, 1, 25, 24)}
                            }),
                            markdown_mdast_node:link(#markdown_mdast_link{
                                url = <<"mailto:bravo@charlie.com">>,
                                title = none,
                                children = ?'vec!'([
                                    markdown_mdast_node:text(#markdown_mdast_text{
                                        value = <<"bravo@charlie.com">>,
                                        position = {some, markdown_unist_position:new(1, 26, 25, 1, 43, 42)}
                                    })
                                ]),
                                position = {some, markdown_unist_position:new(1, 25, 24, 1, 44, 43)}
                            }),
                            markdown_mdast_node:text(#markdown_mdast_text{
                                value = <<" c.">>,
                                position = {some, markdown_unist_position:new(1, 44, 43, 1, 47, 46)}
                            })
                        ]),
                        position = {some, markdown_unist_position:new(1, 1, 0, 1, 47, 46)}
                    })
                ]),
                position = {some, markdown_unist_position:new(1, 1, 0, 1, 47, 46)}
            })},
        markdown:to_mdast(<<"a <https://alpha.com> b <bravo@charlie.com> c."/utf8>>, markdown_parse_options:new(#{})),
        "should support autolinks as `Link`s in mdast"
    ),
    ok.
