%%% % DO NOT EDIT: this file was generated by 'just codegen'
%%% % @generated SignedSource<<502eb4ff7369ce9183fcd0088db7e812>>
%%%-----------------------------------------------------------------------------
%%% Copyright (c) Meta Platforms, Inc. and affiliates.
%%% Copyright (c) WhatsApp LLC
%%%
%%% This source code is licensed under the MIT license found in the
%%% LICENSE.md file in the root directory of this source tree.
%%%-----------------------------------------------------------------------------
%%% % @format
-module(markdown_misc_line_ending_SUITE).
-moduledoc """

""".
-moduledoc #{author => ["Andrew Bennett <potatosaladx@meta.com>"]}.
-moduledoc #{created => "", modified => ""}.
-moduledoc #{copyright => "Meta Platforms, Inc. and affiliates."}.
-compile(warn_missing_spec_all).
-oncall("whatsapp_clr").

-include_lib("markdown/include/markdown_mdast.hrl").
-include_lib("markdown/include/markdown_util.hrl").
-include_lib("stdlib/include/assert.hrl").

-behaviour(ct_suite).

%% ct_suite callbacks
-export([
    all/0,
    groups/0,
    init_per_suite/1,
    end_per_suite/1,
    init_per_group/2,
    end_per_group/2
]).

%% Test Cases
-export([
    test_misc_line_ending_case_1/1,
    test_misc_line_ending_case_2/1,
    test_misc_line_ending_case_3/1,
    test_misc_line_ending_case_4/1,
    test_misc_line_ending_case_5/1,
    test_misc_line_ending_case_6/1,
    test_misc_line_ending_case_7/1,
    test_misc_line_ending_case_8/1,
    test_misc_line_ending_case_9/1,
    test_misc_line_ending_case_10/1,
    test_misc_line_ending_case_11/1,
    test_misc_line_ending_case_12/1,
    test_misc_line_ending_case_13/1,
    test_misc_line_ending_case_14/1,
    test_misc_line_ending_case_15/1,
    test_misc_line_ending_case_16/1,
    test_misc_line_ending_case_17/1,
    test_misc_line_ending_case_18/1,
    test_misc_line_ending_case_19/1,
    test_misc_line_ending_case_20/1,
    test_misc_line_ending_case_21/1,
    test_misc_line_ending_case_22/1,
    test_misc_line_ending_case_23/1,
    test_misc_line_ending_case_24/1,
    test_misc_line_ending_case_25/1,
    test_misc_line_ending_case_26/1,
    test_misc_line_ending_case_27/1,
    test_misc_line_ending_case_28/1,
    test_misc_line_ending_case_29/1,
    test_misc_line_ending_case_30/1,
    test_misc_line_ending_case_31/1
]).

%% Macros
-define(danger, markdown_options:new(#{compile => #{allow_dangerous_html => true, allow_dangerous_protocol => true}})).

%%%=============================================================================
%%% ct_suite callbacks
%%%=============================================================================

-spec all() -> markdown_test:all().
all() ->
    [
        {group, static}
    ].

-spec groups() -> markdown_test:groups().
groups() ->
    [
        {static, [parallel], [
            test_misc_line_ending_case_1,
            test_misc_line_ending_case_2,
            test_misc_line_ending_case_3,
            test_misc_line_ending_case_4,
            test_misc_line_ending_case_5,
            test_misc_line_ending_case_6,
            test_misc_line_ending_case_7,
            test_misc_line_ending_case_8,
            test_misc_line_ending_case_9,
            test_misc_line_ending_case_10,
            test_misc_line_ending_case_11,
            test_misc_line_ending_case_12,
            test_misc_line_ending_case_13,
            test_misc_line_ending_case_14,
            test_misc_line_ending_case_15,
            test_misc_line_ending_case_16,
            test_misc_line_ending_case_17,
            test_misc_line_ending_case_18,
            test_misc_line_ending_case_19,
            test_misc_line_ending_case_20,
            test_misc_line_ending_case_21,
            test_misc_line_ending_case_22,
            test_misc_line_ending_case_23,
            test_misc_line_ending_case_24,
            test_misc_line_ending_case_25,
            test_misc_line_ending_case_26,
            test_misc_line_ending_case_27,
            test_misc_line_ending_case_28,
            test_misc_line_ending_case_29,
            test_misc_line_ending_case_30,
            test_misc_line_ending_case_31
        ]}
    ].

-spec init_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:init_per_suite().
init_per_suite(Config) ->
    Config.

-spec end_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:end_per_suite().
end_per_suite(_Config) ->
    ok.

-spec init_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:init_per_group().
init_per_group(_Group, Config) ->
    Config.

-spec end_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:end_per_group().
end_per_group(_Group, _Config) ->
    ok.

%%%=============================================================================
%%% Test Cases
%%%=============================================================================

-spec test_misc_line_ending_case_1(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_1(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html(<<"\n"/utf8>>),
        "should support just a line feed"
    ),
    ok.

-spec test_misc_line_ending_case_2(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_2(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html(<<"\r"/utf8>>),
        "should support just a carriage return"
    ),
    ok.

-spec test_misc_line_ending_case_3(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_3(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html(<<"\r\n"/utf8>>),
        "should support just a carriage return + line feed"
    ),
    ok.

-spec test_misc_line_ending_case_4(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_4(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html(<<"\n\n"/utf8>>),
        "should support just two line feeds"
    ),
    ok.

-spec test_misc_line_ending_case_5(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_5(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html(<<"\r\r"/utf8>>),
        "should support just two carriage return"
    ),
    ok.

-spec test_misc_line_ending_case_6(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_6(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html(<<"\r\n\r\n"/utf8>>),
        "should support just two carriage return + line feeds"
    ),
    ok.

-spec test_misc_line_ending_case_7(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_7(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a\nb</p>"/utf8>>},
        markdown:to_html(<<"a\nb"/utf8>>),
        "should support a line feed for a line ending inside a paragraph"
    ),
    ok.

-spec test_misc_line_ending_case_8(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_8(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a\rb</p>"/utf8>>},
        markdown:to_html(<<"a\rb"/utf8>>),
        "should support a carriage return for a line ending inside a paragraph"
    ),
    ok.

-spec test_misc_line_ending_case_9(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_9(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a\r\nb</p>"/utf8>>},
        markdown:to_html(<<"a\r\nb"/utf8>>),
        "should support a carriage return + line feed for a line ending inside a paragraph"
    ),
    ok.

-spec test_misc_line_ending_case_10(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_10(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code>a\nb\n</code></pre>"/utf8>>},
        markdown:to_html(<<"\ta\n\tb"/utf8>>),
        "should support a line feed in indented code (and prefer it)"
    ),
    ok.

-spec test_misc_line_ending_case_11(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_11(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code>a\rb\r</code></pre>"/utf8>>},
        markdown:to_html(<<"\ta\r\tb"/utf8>>),
        "should support a carriage return in indented code (and prefer it)"
    ),
    ok.

-spec test_misc_line_ending_case_12(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_12(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code>a\r\nb\r\n</code></pre>"/utf8>>},
        markdown:to_html(<<"\ta\r\n\tb"/utf8>>),
        "should support a carriage return + line feed in indented code (and prefer it)"
    ),
    ok.

-spec test_misc_line_ending_case_13(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_13(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />\n<h3>Heading</h3>"/utf8>>},
        markdown:to_html(<<"***\n### Heading"/utf8>>),
        "should support a line feed between flow"
    ),
    ok.

-spec test_misc_line_ending_case_14(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_14(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />\r<h3>Heading</h3>"/utf8>>},
        markdown:to_html(<<"***\r### Heading"/utf8>>),
        "should support a carriage return between flow"
    ),
    ok.

-spec test_misc_line_ending_case_15(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_15(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />\r\n<h3>Heading</h3>"/utf8>>},
        markdown:to_html(<<"***\r\n### Heading"/utf8>>),
        "should support a carriage return + line feed between flow"
    ),
    ok.

-spec test_misc_line_ending_case_16(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_16(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />\n<h3>Heading</h3>\n"/utf8>>},
        markdown:to_html(<<"***\n\n\n### Heading\n"/utf8>>),
        "should support several line feeds between flow"
    ),
    ok.

-spec test_misc_line_ending_case_17(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_17(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />\r<h3>Heading</h3>\r"/utf8>>},
        markdown:to_html(<<"***\r\r\r### Heading\r"/utf8>>),
        "should support several carriage returns between flow"
    ),
    ok.

-spec test_misc_line_ending_case_18(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_18(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />\r\n<h3>Heading</h3>\r\n"/utf8>>},
        markdown:to_html(<<"***\r\n\r\n\r\n### Heading\r\n"/utf8>>),
        "should support several carriage return + line feeds between flow"
    ),
    ok.

-spec test_misc_line_ending_case_19(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_19(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code class=\"language-x\">\n\ny\n\n\n</code></pre>\n"/utf8>>},
        markdown:to_html(<<"```x\n\n\ny\n\n\n```\n\n\n"/utf8>>),
        "should support several line feeds in fenced code"
    ),
    ok.

-spec test_misc_line_ending_case_20(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_20(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code class=\"language-x\">\r\ry\r\r\r</code></pre>\r"/utf8>>},
        markdown:to_html(<<"```x\r\r\ry\r\r\r```\r\r\r"/utf8>>),
        "should support several carriage returns in fenced code"
    ),
    ok.

-spec test_misc_line_ending_case_21(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_21(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code class=\"language-x\">\r\n\r\ny\r\n\r\n\r\n</code></pre>\r\n"/utf8>>},
        markdown:to_html(<<"```x\r\n\r\n\r\ny\r\n\r\n\r\n```\r\n\r\n\r\n"/utf8>>),
        "should support several carriage return + line feeds in fenced code"
    ),
    ok.

-spec test_misc_line_ending_case_22(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_22(_Config) ->
    ?assertMatch(
        {ok, <<"<h2>A\r\nB</h2>\r\n<p>C</p>"/utf8>>},
        markdown:to_html(<<"A\r\nB\r\n-\r\nC"/utf8>>),
        "should support a carriage return + line feed in content"
    ),
    ok.

-spec test_misc_line_ending_case_23(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_23(_Config) ->
    ?assertMatch(
        {ok, <<"<div\n"/utf8>>},
        markdown:to_html_with_options(<<"<div\n"/utf8>>, ?danger),
        "should support a line feed after html"
    ),
    ok.

-spec test_misc_line_ending_case_24(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_24(_Config) ->
    ?assertMatch(
        {ok, <<"<div\r"/utf8>>},
        markdown:to_html_with_options(<<"<div\r"/utf8>>, ?danger),
        "should support a carriage return after html"
    ),
    ok.

-spec test_misc_line_ending_case_25(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_25(_Config) ->
    ?assertMatch(
        {ok, <<"<div\r\n"/utf8>>},
        markdown:to_html_with_options(<<"<div\r\n"/utf8>>, ?danger),
        "should support a carriage return + line feed after html"
    ),
    ok.

-spec test_misc_line_ending_case_26(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_26(_Config) ->
    ?assertMatch(
        {ok, <<"<div>\n<p>x</p>"/utf8>>},
        markdown:to_html_with_options(<<"<div>\n\nx"/utf8>>, ?danger),
        "should support a blank line w/ line feeds after html"
    ),
    ok.

-spec test_misc_line_ending_case_27(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_27(_Config) ->
    ?assertMatch(
        {ok, <<"<div>\r<p>x</p>"/utf8>>},
        markdown:to_html_with_options(<<"<div>\r\rx"/utf8>>, ?danger),
        "should support a blank line w/ carriage returns after html"
    ),
    ok.

-spec test_misc_line_ending_case_28(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_28(_Config) ->
    ?assertMatch(
        {ok, <<"<div>\r\n<p>x</p>"/utf8>>},
        markdown:to_html_with_options(<<"<div>\r\n\r\nx"/utf8>>, ?danger),
        "should support a blank line w/ carriage return + line feeds after html"
    ),
    ok.

-spec test_misc_line_ending_case_29(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_29(_Config) ->
    ?assertMatch(
        {ok, <<"<div>\nx"/utf8>>},
        markdown:to_html_with_options(<<"<div>\nx"/utf8>>, ?danger),
        "should support a non-blank line w/ line feed in html"
    ),
    ok.

-spec test_misc_line_ending_case_30(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_30(_Config) ->
    ?assertMatch(
        {ok, <<"<div>\rx"/utf8>>},
        markdown:to_html_with_options(<<"<div>\rx"/utf8>>, ?danger),
        "should support a non-blank line w/ carriage return in html"
    ),
    ok.

-spec test_misc_line_ending_case_31(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_line_ending_case_31(_Config) ->
    ?assertMatch(
        {ok, <<"<div>\r\nx"/utf8>>},
        markdown:to_html_with_options(<<"<div>\r\nx"/utf8>>, ?danger),
        "should support a non-blank line w/ carriage return + line feed in html"
    ),
    ok.
