%%% % DO NOT EDIT: this file was generated by 'just codegen'
%%% % @generated <<SignedSource::*O*zOeWoEQle#+L!plEphiEmie@IsG>>
%%% % @format
%%%-----------------------------------------------------------------------------
%%% Copyright (c) Meta Platforms, Inc. and affiliates.
%%% Copyright (c) WhatsApp LLC
%%%
%%% This source code is licensed under the MIT license found in the
%%% LICENSE.md file in the root directory of this source tree.
%%%-----------------------------------------------------------------------------
-module(markdown_gfm_strikethrough_SUITE).
-moduledoc """

""".
-moduledoc #{author => ["Andrew Bennett <potatosaladx@meta.com>"]}.
-moduledoc #{created => "", modified => ""}.
-moduledoc #{copyright => "Meta Platforms, Inc. and affiliates."}.
-compile(warn_missing_spec_all).
-oncall("whatsapp_clr").

-include_lib("markdown/include/markdown_mdast.hrl").
-include_lib("markdown/include/markdown_util.hrl").
-include_lib("stdlib/include/assert.hrl").

-behaviour(ct_suite).

%% ct_suite callbacks
-export([
    all/0,
    groups/0,
    init_per_suite/1,
    end_per_suite/1,
    init_per_group/2,
    end_per_group/2
]).

%% Test Cases
-export([
    test_gfm_strikethrough_case_1/1,
    test_gfm_strikethrough_case_2/1,
    test_gfm_strikethrough_case_3/1,
    test_gfm_strikethrough_case_4/1,
    test_gfm_strikethrough_case_5/1,
    test_gfm_strikethrough_case_6/1,
    test_gfm_strikethrough_case_7/1,
    test_gfm_strikethrough_case_8/1,
    test_gfm_strikethrough_case_9/1,
    test_gfm_strikethrough_case_10/1,
    test_gfm_strikethrough_case_11/1,
    test_gfm_strikethrough_case_12/1,
    test_gfm_strikethrough_case_13/1,
    test_gfm_strikethrough_case_14/1,
    test_gfm_strikethrough_case_15/1,
    test_gfm_strikethrough_case_16/1,
    test_gfm_strikethrough_case_17/1
]).

%%%=============================================================================
%%% ct_suite callbacks
%%%=============================================================================

-spec all() -> markdown_test:all().
all() ->
    [
        {group, static}
    ].

-spec groups() -> markdown_test:groups().
groups() ->
    [
        {static, [parallel], [
            test_gfm_strikethrough_case_1,
            test_gfm_strikethrough_case_2,
            test_gfm_strikethrough_case_3,
            test_gfm_strikethrough_case_4,
            test_gfm_strikethrough_case_5,
            test_gfm_strikethrough_case_6,
            test_gfm_strikethrough_case_7,
            test_gfm_strikethrough_case_8,
            test_gfm_strikethrough_case_9,
            test_gfm_strikethrough_case_10,
            test_gfm_strikethrough_case_11,
            test_gfm_strikethrough_case_12,
            test_gfm_strikethrough_case_13,
            test_gfm_strikethrough_case_14,
            test_gfm_strikethrough_case_15,
            test_gfm_strikethrough_case_16,
            test_gfm_strikethrough_case_17
        ]}
    ].

-spec init_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:init_per_suite().
init_per_suite(Config) ->
    Config.

-spec end_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:end_per_suite().
end_per_suite(_Config) ->
    ok.

-spec init_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:init_per_group().
init_per_group(_Group, Config) ->
    Config.

-spec end_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:end_per_group().
end_per_group(_Group, _Config) ->
    ok.

%%%=============================================================================
%%% Test Cases
%%%=============================================================================

-spec test_gfm_strikethrough_case_1(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_strikethrough_case_1(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a ~b~ c</p>"/utf8>>},
        markdown:to_html(<<"a ~b~ c"/utf8>>),
        "should ignore strikethrough by default"
    ),
    ok.

-spec test_gfm_strikethrough_case_2(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_strikethrough_case_2(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a <del>b</del></p>"/utf8>>},
        markdown:to_html_with_options(<<"a ~b~"/utf8>>, markdown_options:gfm()),
        "should support strikethrough w/ one tilde"
    ),
    ok.

-spec test_gfm_strikethrough_case_3(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_strikethrough_case_3(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a <del>b</del></p>"/utf8>>},
        markdown:to_html_with_options(<<"a ~~b~~"/utf8>>, markdown_options:gfm()),
        "should support strikethrough w/ two tildes"
    ),
    ok.

-spec test_gfm_strikethrough_case_4(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_strikethrough_case_4(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a ~~~b~~~</p>"/utf8>>},
        markdown:to_html_with_options(<<"a ~~~b~~~"/utf8>>, markdown_options:gfm()),
        "should not support strikethrough w/ three tildes"
    ),
    ok.

-spec test_gfm_strikethrough_case_5(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_strikethrough_case_5(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a ~<del>b</del> c</p>"/utf8>>},
        markdown:to_html_with_options(<<"a \\~~~b~~ c"/utf8>>, markdown_options:gfm()),
        "should support strikethrough after an escaped tilde"
    ),
    ok.

-spec test_gfm_strikethrough_case_6(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_strikethrough_case_6(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a <del>b <del>c</del> d</del> e</p>"/utf8>>},
        markdown:to_html_with_options(<<"a ~~b ~~c~~ d~~ e"/utf8>>, markdown_options:gfm()),
        "should support nested strikethrough"
    ),
    ok.

-spec test_gfm_strikethrough_case_7(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_strikethrough_case_7(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a <del>-1</del> b</p>"/utf8>>},
        markdown:to_html_with_options(<<"a ~-1~ b"/utf8>>, markdown_options:gfm()),
        "should open if preceded by whitespace and followed by punctuation"
    ),
    ok.

-spec test_gfm_strikethrough_case_8(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_strikethrough_case_8(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a <del>b.</del> c</p>"/utf8>>},
        markdown:to_html_with_options(<<"a ~b.~ c"/utf8>>, markdown_options:gfm()),
        "should close if preceded by punctuation and followed by whitespace"
    ),
    ok.

-spec test_gfm_strikethrough_case_9(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_strikethrough_case_9(_Config) ->
    ?assertMatch(
        {ok, <<"<p><del>b.</del>.</p>"/utf8>>},
        markdown:to_html_with_options(<<"~b.~."/utf8>>, markdown_options:gfm()),
        "should close if preceded and followed by punctuation"
    ),
    ok.

-spec test_gfm_strikethrough_case_10(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_strikethrough_case_10(_Config) ->
    ?assertMatch(
        {ok, <<"""
        <h1>Balanced</h1>
        <p>a <del>one</del> b</p>
        <p>a <del>two</del> b</p>
        <p>a ~~~three~~~ b</p>
        <p>a ~~~~four~~~~ b</p>
        <h1>Unbalanced</h1>
        <p>a ~one/two~~ b</p>
        <p>a ~one/three~~~ b</p>
        <p>a ~one/four~~~~ b</p>
        <hr />
        <p>a ~~two/one~ b</p>
        <p>a ~~two/three~~~ b</p>
        <p>a ~~two/four~~~~ b</p>
        <hr />
        <p>a ~~~three/one~ b</p>
        <p>a ~~~three/two~~ b</p>
        <p>a ~~~three/four~~~~ b</p>
        <hr />
        <p>a ~~~~four/one~ b</p>
        <p>a ~~~~four/two~~ b</p>
        <p>a ~~~~four/three~~~ b</p>
        <h2>Multiple</h2>
        <p>a <del>one b one</del> c one~ d</p>
        <p>a <del>one b two~~ c one</del> d</p>
        <p>a <del>one b one</del> c two~~ d</p>
        <p>a <del>two b two</del> c two~~ d</p>
        <p>a <del>two b one~ c two</del> d</p>
        <p>a <del>two b two</del> c one~ d</p>

        """/utf8>>},
        markdown:to_html_with_options(<<"""

        # Balanced

        a ~one~ b

        a ~~two~~ b

        a ~~~three~~~ b

        a ~~~~four~~~~ b

        # Unbalanced

        a ~one/two~~ b

        a ~one/three~~~ b

        a ~one/four~~~~ b

        ***

        a ~~two/one~ b

        a ~~two/three~~~ b

        a ~~two/four~~~~ b

        ***

        a ~~~three/one~ b

        a ~~~three/two~~ b

        a ~~~three/four~~~~ b

        ***

        a ~~~~four/one~ b

        a ~~~~four/two~~ b

        a ~~~~four/three~~~ b

        ## Multiple

        a ~one b one~ c one~ d

        a ~one b two~~ c one~ d

        a ~one b one~ c two~~ d

        a ~~two b two~~ c two~~ d

        a ~~two b one~ c two~~ d

        a ~~two b two~~ c one~ d

        """/utf8>>, markdown_options:gfm()),
        "should handle balance like GitHub"
    ),
    ok.

-spec test_gfm_strikethrough_case_11(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_strikethrough_case_11(_Config) ->
    ?assertMatch(
        {ok, <<"""
        <h1>Flank</h1>
        <p>a oneRight~ b oneRight~ c oneRight~ d</p>
        <p>a oneRight~ b oneRight~ c ~oneLeft d</p>
        <p>a oneRight~ b <del>oneLeft c oneRight</del> d</p>
        <p>a <del>oneLeft b oneRight</del> c oneRight~ d</p>
        <p>a <del>oneLeft b oneRight</del> c ~oneLeft d</p>
        <p>a ~oneLeft b <del>oneLeft c oneRight</del> d</p>
        <p>a ~oneLeft b ~oneLeft c ~oneLeft d</p>
        <hr />
        <p>a twoRight~~ b twoRight~~ c twoRight~~ d</p>
        <p>a twoRight~~ b twoRight~~ c ~~twoLeft d</p>
        <p>a twoRight~~ b <del>twoLeft c twoRight</del> d</p>
        <p>a <del>twoLeft b twoRight</del> c twoRight~~ d</p>
        <p>a <del>twoLeft b twoRight</del> c ~~twoLeft d</p>
        <p>a ~~twoLeft b <del>twoLeft c twoRight</del> d</p>
        <p>a ~~twoLeft b ~~twoLeft c ~~twoLeft d</p>

        """/utf8>>},
        markdown:to_html_with_options(<<"""

        # Flank

        a oneRight~ b oneRight~ c oneRight~ d

        a oneRight~ b oneRight~ c ~oneLeft d

        a oneRight~ b ~oneLeft c oneRight~ d

        a ~oneLeft b oneRight~ c oneRight~ d

        a ~oneLeft b oneRight~ c ~oneLeft d

        a ~oneLeft b ~oneLeft c oneRight~ d

        a ~oneLeft b ~oneLeft c ~oneLeft d

        ***

        a twoRight~~ b twoRight~~ c twoRight~~ d

        a twoRight~~ b twoRight~~ c ~~twoLeft d

        a twoRight~~ b ~~twoLeft c twoRight~~ d

        a ~~twoLeft b twoRight~~ c twoRight~~ d

        a ~~twoLeft b twoRight~~ c ~~twoLeft d

        a ~~twoLeft b ~~twoLeft c twoRight~~ d

        a ~~twoLeft b ~~twoLeft c ~~twoLeft d

        """/utf8>>, markdown_options:gfm()),
        "should handle flanking like GitHub"
    ),
    ok.

-spec test_gfm_strikethrough_case_12(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_strikethrough_case_12(_Config) ->
    ?assertMatch(
        {ok, <<"""
        <h1>Interlpay</h1>
        <h2>Interleave with attention</h2>
        <p>a <del>two <em>emphasis</em> two</del> b</p>
        <p>a <del>two <strong>strong</strong> two</del> b</p>
        <p>a <em>marker ~~two marker</em> two~~ b</p>
        <p>a <del>two *marker two</del> marker* b</p>
        <h2>Interleave with links</h2>
        <p>a <del>two <a href="#">resource</a> two</del> b</p>
        <p>a <del>two <a href="#">reference</a> two</del> b</p>
        <p>a <a href="#">label start ~~two label end</a> two~~ b</p>
        <p>a ~~two <a href="#">label start two~~ label end</a> b</p>
        <p>a <del>two <a href="#">label start <del>one one</del> label end</a> two</del> b</p>
        <p>a <del>one <a href="#">label start <del>two two</del> label end</a> one</del> b</p>
        <p>a <del>one <a href="#">label start <del>one one</del> label end</a> one</del> b</p>
        <p>a <del>two <a href="#">label start <del>two two</del> label end</a> two</del> b</p>
        <h2>Interleave with code (text)</h2>
        <p>a <del>two <code>code</code> two</del> b</p>
        <p>a ~~two <code>code two~~</code> b</p>
        <p>a <code>code start ~~two code end</code> two~~ b</p>
        <p>a ~~two <code>code start two~~ code end</code> b</p>
        <p>a <del>two <code>code start ~one one~ code end</code> two</del> b</p>
        <p>a <del>one <code>code start ~~two two~~ code end</code> one</del> b</p>
        <p>a <del>one <code>code start ~one one~ code end</code> one</del> b</p>
        <p>a <del>two <code>code start ~~two two~~ code end</code> two</del> b</p>
        <h2>Emphasis/strong/strikethrough interplay</h2>
        <p>a <em><strong><del>xxx</del></strong></em> zzz</p>
        <p>b <em><strong>xxx</strong></em>zzz</p>
        <p>c <strong>xxx</strong>zzz</p>
        <p>d <em>xxx</em>zzz</p>
        <p>e <em><strong><del>xxx</del></strong></em>yyy</p>
        <p>f <strong><del>xxx</del></strong>yyy</p>
        <p>g <em><del>xxx</del></em>yyy</p>
        <p>h <em><strong><del>xxx</del></strong></em> zzz</p>
        <p>i <strong><del>xxx</del></strong> zzz</p>
        <p>j <em><del>xxx</del></em> zzz</p>
        <p>k ~~~<strong>xxx</strong>~~~ zzz</p>
        <p>l ~~~xxx~~~zzz</p>
        <p>m <del>xxx</del>zzz</p>
        <p>n <del>xxx</del>zzz</p>
        <p>o ~~~<strong>xxx</strong>~~~yyy</p>
        <p>p ~~<strong>xxx</strong>~~yyy</p>
        <p>r ~<strong>xxx</strong>~yyy</p>
        <p>s ~~~<strong>xxx</strong>~~~ zzz</p>
        <p>t <del><strong>xxx</strong></del> zzz</p>
        <p>u <del><strong>xxx</strong></del> zzz</p>

        """/utf8>>},
        markdown:to_html_with_options(<<"""

        # Interlpay

        ## Interleave with attention

        a ~~two *emphasis* two~~ b

        a ~~two **strong** two~~ b

        a *marker ~~two marker* two~~ b

        a ~~two *marker two~~ marker* b

        ## Interleave with links

        a ~~two [resource](#) two~~ b

        a ~~two [reference][#] two~~ b

        a [label start ~~two label end](#) two~~ b

        a ~~two [label start two~~ label end](#) b

        a ~~two [label start ~one one~ label end](#) two~~ b

        a ~one [label start ~~two two~~ label end](#) one~ b

        a ~one [label start ~one one~ label end](#) one~ b

        a ~~two [label start ~~two two~~ label end](#) two~~ b

        [#]: #

        ## Interleave with code (text)

        a ~~two `code` two~~ b

        a ~~two `code two~~` b

        a `code start ~~two code end` two~~ b

        a ~~two `code start two~~ code end` b

        a ~~two `code start ~one one~ code end` two~~ b

        a ~one `code start ~~two two~~ code end` one~ b

        a ~one `code start ~one one~ code end` one~ b

        a ~~two `code start ~~two two~~ code end` two~~ b

        ## Emphasis/strong/strikethrough interplay

        a ***~~xxx~~*** zzz

        b ***xxx***zzz

        c **xxx**zzz

        d *xxx*zzz

        e ***~~xxx~~***yyy

        f **~~xxx~~**yyy

        g *~~xxx~~*yyy

        h ***~~xxx~~*** zzz

        i **~~xxx~~** zzz

        j *~~xxx~~* zzz

        k ~~~**xxx**~~~ zzz

        l ~~~xxx~~~zzz

        m ~~xxx~~zzz

        n ~xxx~zzz

        o ~~~**xxx**~~~yyy

        p ~~**xxx**~~yyy

        r ~**xxx**~yyy

        s ~~~**xxx**~~~ zzz

        t ~~**xxx**~~ zzz

        u ~**xxx**~ zzz

        """/utf8>>, markdown_options:gfm()),
        "should handle interplay like GitHub"
    ),
    ok.

-spec test_gfm_strikethrough_case_13(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_strikethrough_case_13(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a<em><del>b</del></em>c</p>\n<p>a*.b.*c</p>"/utf8>>},
        markdown:to_html_with_options(<<"a*~b~*c\n\na*.b.*c"/utf8>>, markdown_options:gfm()),
        "should handle interplay w/ other attention markers (GFM)"
    ),
    ok.

-spec test_gfm_strikethrough_case_14(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_strikethrough_case_14(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a*~b~*c</p>\n<p>a*.b.*c</p>"/utf8>>},
        markdown:to_html(<<"a*~b~*c\n\na*.b.*c"/utf8>>),
        "should handle interplay w/ other attention markers (CM reference)"
    ),
    ok.

-spec test_gfm_strikethrough_case_15(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_strikethrough_case_15(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a ~b~ <del>c</del> d</p>"/utf8>>},
        markdown:to_html_with_options(
            <<"a ~b~ ~~c~~ d"/utf8>>, markdown_options:gfm(#{parse => #{gfm_strikethrough_single_tilde => false}})
        ),
        "should not support strikethrough w/ one tilde if `singleTilde: false`"
    ),
    ok.

-spec test_gfm_strikethrough_case_16(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_strikethrough_case_16(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a <del>b</del> <del>c</del> d</p>"/utf8>>},
        markdown:to_html_with_options(
            <<"a ~b~ ~~c~~ d"/utf8>>, markdown_options:gfm(#{parse => #{gfm_strikethrough_single_tilde => true}})
        ),
        "should support strikethrough w/ one tilde if `singleTilde: true`"
    ),
    ok.

-spec test_gfm_strikethrough_case_17(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_strikethrough_case_17(_Config) ->
    ?assertEqual(
        {ok,
            markdown_mdast_node:root(#markdown_mdast_root{
                children = ?'vec!'([
                    markdown_mdast_node:paragraph(#markdown_mdast_paragraph{
                        children = ?'vec!'([
                            markdown_mdast_node:text(#markdown_mdast_text{
                                value = <<"a ">>,
                                position = {some, markdown_unist_position:new(1, 1, 0, 1, 3, 2)}
                            }),
                            markdown_mdast_node:delete(#markdown_mdast_delete{
                                children = ?'vec!'([
                                    markdown_mdast_node:text(#markdown_mdast_text{
                                        value = <<"alpha">>,
                                        position = {some, markdown_unist_position:new(1, 5, 4, 1, 10, 9)}
                                    })
                                ]),
                                position = {some, markdown_unist_position:new(1, 3, 2, 1, 12, 11)}
                            }),
                            markdown_mdast_node:text(#markdown_mdast_text{
                                value = <<" b.">>,
                                position = {some, markdown_unist_position:new(1, 12, 11, 1, 15, 14)}
                            })
                        ]),
                        position = {some, markdown_unist_position:new(1, 1, 0, 1, 15, 14)}
                    })
                ]),
                position = {some, markdown_unist_position:new(1, 1, 0, 1, 15, 14)}
            })},
        markdown:to_mdast(<<"a ~~alpha~~ b."/utf8>>, markdown_parse_options:gfm()),
        "should support GFM strikethrough as `Delete`s in mdast"
    ),
    ok.
