%%% % DO NOT EDIT: this file was generated by 'just codegen'
%%% % @generated SignedSource<<d03297e2ae36a9e809f272314e29d9bd>>
%%%-----------------------------------------------------------------------------
%%% %CopyrightBegin%
%%%
%%% SPDX-License-Identifier: Apache-2.0
%%%
%%% Copyright (c) Meta Platforms, Inc. and affiliates.
%%% Copyright (c) WhatsApp LLC
%%%
%%% Licensed under the Apache License, Version 2.0 (the "License");
%%% you may not use this file except in compliance with the License.
%%% You may obtain a copy of the License at
%%%
%%%     http://www.apache.org/licenses/LICENSE-2.0
%%%
%%% Unless required by applicable law or agreed to in writing, software
%%% distributed under the License is distributed on an "AS IS" BASIS,
%%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%%% See the License for the specific language governing permissions and
%%% limitations under the License.
%%%
%%% %CopyrightEnd%
%%%-----------------------------------------------------------------------------
%%% % @format
-module(markdown_link_resource_SUITE).
-moduledoc """

""".
-moduledoc #{author => ["Andrew Bennett <potatosaladx@meta.com>"]}.
-moduledoc #{created => "", modified => ""}.
-moduledoc #{copyright => "Meta Platforms, Inc. and affiliates."}.
-compile(warn_missing_spec_all).
-oncall("whatsapp_clr").

-include_lib("markdown/include/markdown_mdast.hrl").
-include_lib("markdown/include/markdown_util.hrl").
-include_lib("stdlib/include/assert.hrl").

-behaviour(ct_suite).

%% ct_suite callbacks
-export([
    all/0,
    groups/0,
    init_per_suite/1,
    end_per_suite/1,
    init_per_group/2,
    end_per_group/2
]).

%% Test Cases
-export([
    test_link_resource_case_1/1,
    test_link_resource_case_2/1,
    test_link_resource_case_3/1,
    test_link_resource_case_4/1,
    test_link_resource_case_5/1,
    test_link_resource_case_6/1,
    test_link_resource_case_7/1,
    test_link_resource_case_8/1,
    test_link_resource_case_9/1,
    test_link_resource_case_10/1,
    test_link_resource_case_11/1,
    test_link_resource_case_12/1,
    test_link_resource_case_13/1,
    test_link_resource_case_14/1,
    test_link_resource_case_15/1,
    test_link_resource_case_16/1,
    test_link_resource_case_17/1,
    test_link_resource_case_18/1,
    test_link_resource_case_19/1,
    test_link_resource_case_20/1,
    test_link_resource_case_21/1,
    test_link_resource_case_22/1,
    test_link_resource_case_23/1,
    test_link_resource_case_24/1,
    test_link_resource_case_25/1,
    test_link_resource_case_26/1,
    test_link_resource_case_27/1,
    test_link_resource_case_28/1,
    test_link_resource_case_29/1,
    test_link_resource_case_30/1,
    test_link_resource_case_31/1,
    test_link_resource_case_32/1,
    test_link_resource_case_33/1,
    test_link_resource_case_34/1,
    test_link_resource_case_35/1,
    test_link_resource_case_36/1,
    test_link_resource_case_37/1,
    test_link_resource_case_38/1,
    test_link_resource_case_39/1,
    test_link_resource_case_40/1,
    test_link_resource_case_41/1,
    test_link_resource_case_42/1,
    test_link_resource_case_43/1,
    test_link_resource_case_44/1,
    test_link_resource_case_45/1,
    test_link_resource_case_46/1,
    test_link_resource_case_47/1,
    test_link_resource_case_48/1,
    test_link_resource_case_49/1,
    test_link_resource_case_50/1,
    test_link_resource_case_51/1,
    test_link_resource_case_52/1,
    test_link_resource_case_53/1,
    test_link_resource_case_54/1,
    test_link_resource_case_55/1,
    test_link_resource_case_56/1,
    test_link_resource_case_57/1,
    test_link_resource_case_58/1,
    test_link_resource_case_59/1,
    test_link_resource_case_60/1,
    test_link_resource_case_61/1,
    test_link_resource_case_62/1,
    test_link_resource_case_63/1,
    test_link_resource_case_64/1,
    test_link_resource_case_65/1,
    test_link_resource_case_66/1,
    test_link_resource_case_67/1,
    test_link_resource_case_68/1,
    test_link_resource_case_69/1,
    test_link_resource_case_70/1,
    test_link_resource_case_71/1,
    test_link_resource_case_72/1,
    test_link_resource_case_73/1,
    test_link_resource_case_74/1,
    test_link_resource_case_75/1,
    test_link_resource_case_76/1
]).

%% Macros
-define(danger, markdown_options:new(#{compile => #{allow_dangerous_html => true, allow_dangerous_protocol => true}})).

%%%=============================================================================
%%% ct_suite callbacks
%%%=============================================================================

-spec all() -> markdown_test:all().
all() ->
    [
        {group, static}
    ].

-spec groups() -> markdown_test:groups().
groups() ->
    [
        {static, [parallel], [
            test_link_resource_case_1,
            test_link_resource_case_2,
            test_link_resource_case_3,
            test_link_resource_case_4,
            test_link_resource_case_5,
            test_link_resource_case_6,
            test_link_resource_case_7,
            test_link_resource_case_8,
            test_link_resource_case_9,
            test_link_resource_case_10,
            test_link_resource_case_11,
            test_link_resource_case_12,
            test_link_resource_case_13,
            test_link_resource_case_14,
            test_link_resource_case_15,
            test_link_resource_case_16,
            test_link_resource_case_17,
            test_link_resource_case_18,
            test_link_resource_case_19,
            test_link_resource_case_20,
            test_link_resource_case_21,
            test_link_resource_case_22,
            test_link_resource_case_23,
            test_link_resource_case_24,
            test_link_resource_case_25,
            test_link_resource_case_26,
            test_link_resource_case_27,
            test_link_resource_case_28,
            test_link_resource_case_29,
            test_link_resource_case_30,
            test_link_resource_case_31,
            test_link_resource_case_32,
            test_link_resource_case_33,
            test_link_resource_case_34,
            test_link_resource_case_35,
            test_link_resource_case_36,
            test_link_resource_case_37,
            test_link_resource_case_38,
            test_link_resource_case_39,
            test_link_resource_case_40,
            test_link_resource_case_41,
            test_link_resource_case_42,
            test_link_resource_case_43,
            test_link_resource_case_44,
            test_link_resource_case_45,
            test_link_resource_case_46,
            test_link_resource_case_47,
            test_link_resource_case_48,
            test_link_resource_case_49,
            test_link_resource_case_50,
            test_link_resource_case_51,
            test_link_resource_case_52,
            test_link_resource_case_53,
            test_link_resource_case_54,
            test_link_resource_case_55,
            test_link_resource_case_56,
            test_link_resource_case_57,
            test_link_resource_case_58,
            test_link_resource_case_59,
            test_link_resource_case_60,
            test_link_resource_case_61,
            test_link_resource_case_62,
            test_link_resource_case_63,
            test_link_resource_case_64,
            test_link_resource_case_65,
            test_link_resource_case_66,
            test_link_resource_case_67,
            test_link_resource_case_68,
            test_link_resource_case_69,
            test_link_resource_case_70,
            test_link_resource_case_71,
            test_link_resource_case_72,
            test_link_resource_case_73,
            test_link_resource_case_74,
            test_link_resource_case_75,
            test_link_resource_case_76
        ]}
    ].

-spec init_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:init_per_suite().
init_per_suite(Config) ->
    Config.

-spec end_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:end_per_suite().
end_per_suite(_Config) ->
    ok.

-spec init_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:init_per_group().
init_per_group(_Group, Config) ->
    Config.

-spec end_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:end_per_group().
end_per_group(_Group, _Config) ->
    ok.

%%%=============================================================================
%%% Test Cases
%%%=============================================================================

-spec test_link_resource_case_1(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_1(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"/uri\" title=\"title\">link</a></p>"/utf8>>},
        markdown:to_html(<<"[link](/uri \"title\")"/utf8>>),
        "should support links"
    ),
    ok.

-spec test_link_resource_case_2(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_2(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"/uri\">link</a></p>"/utf8>>},
        markdown:to_html(<<"[link](/uri)"/utf8>>),
        "should support links w/o title"
    ),
    ok.

-spec test_link_resource_case_3(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_3(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"\">link</a></p>"/utf8>>},
        markdown:to_html(<<"[link]()"/utf8>>),
        "should support links w/o destination"
    ),
    ok.

-spec test_link_resource_case_4(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_4(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"\">link</a></p>"/utf8>>},
        markdown:to_html(<<"[link](<>)"/utf8>>),
        "should support links w/ empty enclosed destination"
    ),
    ok.

-spec test_link_resource_case_5(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_5(_Config) ->
    ?assertMatch(
        {ok, <<"<p>[link](/my uri)</p>"/utf8>>},
        markdown:to_html(<<"[link](/my uri)"/utf8>>),
        "should not support links w/ spaces in destination"
    ),
    ok.

-spec test_link_resource_case_6(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_6(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"/my%20uri\">link</a></p>"/utf8>>},
        markdown:to_html(<<"[link](</my uri>)"/utf8>>),
        "should support links w/ spaces in enclosed destination"
    ),
    ok.

-spec test_link_resource_case_7(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_7(_Config) ->
    ?assertMatch(
        {ok, <<"<p>[link](foo\nbar)</p>"/utf8>>},
        markdown:to_html(<<"[link](foo\nbar)"/utf8>>),
        "should not support links w/ line endings in destination"
    ),
    ok.

-spec test_link_resource_case_8(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_8(_Config) ->
    ?assertMatch(
        {ok, <<"<p>[link](<foo\nbar>)</p>"/utf8>>},
        markdown:to_html_with_options(<<"[link](<foo\nbar>)"/utf8>>, ?danger),
        "should not support links w/ line endings in enclosed destination"
    ),
    ok.

-spec test_link_resource_case_9(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_9(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"b)c\">a</a></p>"/utf8>>},
        markdown:to_html(<<"[a](<b)c>)"/utf8>>),
        "should support links w/ closing parens in destination"
    ),
    ok.

-spec test_link_resource_case_10(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_10(_Config) ->
    ?assertMatch(
        {ok, <<"<p>[link](&lt;foo&gt;)</p>"/utf8>>},
        markdown:to_html(<<"[link](<foo\\>)"/utf8>>),
        "should not support links w/ enclosed destinations w/o end"
    ),
    ok.

-spec test_link_resource_case_11(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_11(_Config) ->
    ?assertMatch(
        {ok, <<"<p>[a](&lt;b)c\n[a](&lt;b)c&gt;\n[a](<b>c)</p>"/utf8>>},
        markdown:to_html_with_options(<<"[a](<b)c\n[a](<b)c>\n[a](<b>c)"/utf8>>, ?danger),
        "should not support links w/ unmatched enclosed destinations"
    ),
    ok.

-spec test_link_resource_case_12(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_12(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"(foo)\">link</a></p>"/utf8>>},
        markdown:to_html(<<"[link](\\(foo\\))"/utf8>>),
        "should support links w/ destinations w/ escaped parens"
    ),
    ok.

-spec test_link_resource_case_13(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_13(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"foo(and(bar))\">link</a></p>"/utf8>>},
        markdown:to_html(<<"[link](foo(and(bar)))"/utf8>>),
        "should support links w/ destinations w/ balanced parens"
    ),
    ok.

-spec test_link_resource_case_14(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_14(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"foo(and(bar)\">link</a></p>"/utf8>>},
        markdown:to_html(<<"[link](foo\\(and\\(bar\\))"/utf8>>),
        "should support links w/ destinations w/ escaped parens"
    ),
    ok.

-spec test_link_resource_case_15(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_15(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"foo(and(bar)\">link</a></p>"/utf8>>},
        markdown:to_html(<<"[link](<foo(and(bar)>)"/utf8>>),
        "should support links w/ enclosed destinations w/ parens"
    ),
    ok.

-spec test_link_resource_case_16(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_16(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"foo):\">link</a></p>"/utf8>>},
        markdown:to_html_with_options(<<"[link](foo\\)\\:)"/utf8>>, ?danger),
        "should support links w/ escapes in destinations"
    ),
    ok.

-spec test_link_resource_case_17(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_17(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"#fragment\">link</a></p>"/utf8>>},
        markdown:to_html(<<"[link](#fragment)"/utf8>>),
        "should support links w/ destinations to fragments"
    ),
    ok.

-spec test_link_resource_case_18(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_18(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"http://example.com#fragment\">link</a></p>"/utf8>>},
        markdown:to_html(<<"[link](http://example.com#fragment)"/utf8>>),
        "should support links w/ destinations to URLs w/ fragments"
    ),
    ok.

-spec test_link_resource_case_19(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_19(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"http://example.com?foo=3#frag\">link</a></p>"/utf8>>},
        markdown:to_html(<<"[link](http://example.com?foo=3#frag)"/utf8>>),
        "should support links w/ destinations to URLs w/ search and fragments"
    ),
    ok.

-spec test_link_resource_case_20(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_20(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"foo%5Cbar\">link</a></p>"/utf8>>},
        markdown:to_html(<<"[link](foo\\bar)"/utf8>>),
        "should not support non-punctuation character escapes in links"
    ),
    ok.

-spec test_link_resource_case_21(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_21(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"foo%20b%C3%A4\">link</a></p>"/utf8>>},
        markdown:to_html(<<"[link](foo%20b&auml;)"/utf8>>),
        "should support character references in links"
    ),
    ok.

-spec test_link_resource_case_22(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_22(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"%22title%22\">link</a></p>"/utf8>>},
        markdown:to_html(<<"[link](\"title\")"/utf8>>),
        "should not support links w/ only a title"
    ),
    ok.

-spec test_link_resource_case_23(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_23(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"/url\" title=\"title\">link</a></p>"/utf8>>},
        markdown:to_html(<<"[link](/url \"title\")"/utf8>>),
        "should support titles w/ double quotes"
    ),
    ok.

-spec test_link_resource_case_24(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_24(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"/url\" title=\"title\">link</a></p>"/utf8>>},
        markdown:to_html(<<"[link](/url 'title')"/utf8>>),
        "should support titles w/ single quotes"
    ),
    ok.

-spec test_link_resource_case_25(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_25(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"/url\" title=\"title\">link</a></p>"/utf8>>},
        markdown:to_html(<<"[link](/url (title))"/utf8>>),
        "should support titles w/ parens"
    ),
    ok.

-spec test_link_resource_case_26(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_26(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"/url\" title=\"title &quot;&quot;\">link</a></p>"/utf8>>},
        markdown:to_html(<<"[link](/url \"title \\\"&quot;\")"/utf8>>),
        "should support character references and escapes in titles"
    ),
    ok.

-spec test_link_resource_case_27(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_27(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"/url%C2%A0%22title%22\">link</a></p>"/utf8>>},
        markdown:to_html(<<"[link](/url \"title\")"/utf8>>),
        "should not support unicode whitespace between destination and title"
    ),
    ok.

-spec test_link_resource_case_28(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_28(_Config) ->
    ?assertMatch(
        {ok, <<"<p>[link](/url &quot;title &quot;and&quot; title&quot;)</p>"/utf8>>},
        markdown:to_html(<<"[link](/url \"title \"and\" title\")"/utf8>>),
        "should not support nested balanced quotes in title"
    ),
    ok.

-spec test_link_resource_case_29(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_29(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"/url\" title=\"title &quot;and&quot; title\">link</a></p>"/utf8>>},
        markdown:to_html(<<"[link](/url 'title \"and\" title')"/utf8>>),
        "should support the other quotes in titles"
    ),
    ok.

-spec test_link_resource_case_30(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_30(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"/uri\" title=\"title\">link</a></p>"/utf8>>},
        markdown:to_html(<<"[link](   /uri\n  \"title\"  )"/utf8>>),
        "should support whitespace around destination and title (1)"
    ),
    ok.

-spec test_link_resource_case_31(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_31(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"/uri\" title=\"title\">link</a></p>"/utf8>>},
        markdown:to_html(<<"[link](\t\n/uri \"title\")"/utf8>>),
        "should support whitespace around destination and title (2)"
    ),
    ok.

-spec test_link_resource_case_32(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_32(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"/uri\" title=\"title\">link</a></p>"/utf8>>},
        markdown:to_html(<<"[link](/uri  \"title\"\t\n)"/utf8>>),
        "should support whitespace around destination and title (3)"
    ),
    ok.

-spec test_link_resource_case_33(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_33(_Config) ->
    ?assertMatch(
        {ok, <<"<p>[link] (/uri)</p>"/utf8>>},
        markdown:to_html(<<"[link] (/uri)"/utf8>>),
        "should not support whitespace between label and resource"
    ),
    ok.

-spec test_link_resource_case_34(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_34(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"/uri\">link [foo [bar]]</a></p>"/utf8>>},
        markdown:to_html(<<"[link [foo [bar]]](/uri)"/utf8>>),
        "should support balanced brackets"
    ),
    ok.

-spec test_link_resource_case_35(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_35(_Config) ->
    ?assertMatch(
        {ok, <<"<p>[link] bar](/uri)</p>"/utf8>>},
        markdown:to_html(<<"[link] bar](/uri)"/utf8>>),
        "should not support unbalanced brackets (1)"
    ),
    ok.

-spec test_link_resource_case_36(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_36(_Config) ->
    ?assertMatch(
        {ok, <<"<p>[link <a href=\"/uri\">bar</a></p>"/utf8>>},
        markdown:to_html(<<"[link [bar](/uri)"/utf8>>),
        "should not support unbalanced brackets (2)"
    ),
    ok.

-spec test_link_resource_case_37(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_37(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"/uri\">link [bar</a></p>"/utf8>>},
        markdown:to_html(<<"[link \\[bar](/uri)"/utf8>>),
        "should support characer escapes"
    ),
    ok.

-spec test_link_resource_case_38(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_38(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"/uri\">link <em>foo <strong>bar</strong> <code>#</code></em></a></p>"/utf8>>},
        markdown:to_html(<<"[link *foo **bar** `#`*](/uri)"/utf8>>),
        "should support content"
    ),
    ok.

-spec test_link_resource_case_39(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_39(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"/uri\"><img src=\"moon.jpg\" alt=\"moon\" /></a></p>"/utf8>>},
        markdown:to_html(<<"[![moon](moon.jpg)](/uri)"/utf8>>),
        "should support an image as content"
    ),
    ok.

-spec test_link_resource_case_40(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_40(_Config) ->
    ?assertMatch(
        {ok, <<"<p>[foo <a href=\"/uri\">bar</a>](/uri)</p>"/utf8>>},
        markdown:to_html(<<"[foo [bar](/uri)](/uri)"/utf8>>),
        "should not support links in links (1)"
    ),
    ok.

-spec test_link_resource_case_41(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_41(_Config) ->
    ?assertMatch(
        {ok, <<"<p>[foo <em>[bar <a href=\"/uri\">baz</a>](/uri)</em>](/uri)</p>"/utf8>>},
        markdown:to_html(<<"[foo *[bar [baz](/uri)](/uri)*](/uri)"/utf8>>),
        "should not support links in links (2)"
    ),
    ok.

-spec test_link_resource_case_42(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_42(_Config) ->
    ?assertMatch(
        {ok, <<"<p><img src=\"uri3\" alt=\"[foo](uri2)\" /></p>"/utf8>>},
        markdown:to_html(<<"![[[foo](uri1)](uri2)](uri3)"/utf8>>),
        "should not support links in links (3)"
    ),
    ok.

-spec test_link_resource_case_43(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_43(_Config) ->
    ?assertMatch(
        {ok, <<"<p>*<a href=\"/uri\">foo*</a></p>"/utf8>>},
        markdown:to_html(<<"*[foo*](/uri)"/utf8>>),
        "should prefer links over emphasis (1)"
    ),
    ok.

-spec test_link_resource_case_44(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_44(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"baz*\">foo *bar</a></p>"/utf8>>},
        markdown:to_html(<<"[foo *bar](baz*)"/utf8>>),
        "should prefer links over emphasis (2)"
    ),
    ok.

-spec test_link_resource_case_45(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_45(_Config) ->
    ?assertMatch(
        {ok, <<"<p>[foo <bar attr=\"](baz)\"></p>"/utf8>>},
        markdown:to_html_with_options(<<"[foo <bar attr=\"](baz)\">"/utf8>>, ?danger),
        "should prefer HTML over links"
    ),
    ok.

-spec test_link_resource_case_46(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_46(_Config) ->
    ?assertMatch(
        {ok, <<"<p>[foo<code>](/uri)</code></p>"/utf8>>},
        markdown:to_html(<<"[foo`](/uri)`"/utf8>>),
        "should prefer code over links"
    ),
    ok.

-spec test_link_resource_case_47(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_47(_Config) ->
    ?assertMatch(
        {ok,
            <<"<p>[foo<a href=\"http://example.com/?search=%5D(uri)\">http://example.com/?search=](uri)</a></p>"/utf8>>},
        markdown:to_html(<<"[foo<http://example.com/?search=](uri)>"/utf8>>),
        "should prefer autolinks over links"
    ),
    ok.

-spec test_link_resource_case_48(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_48(_Config) ->
    ?assertMatch(
        {ok,
            <<"<p>[foo<a href=\"http://example.com/?search=%5D(uri)\">http://example.com/?search=](uri)</a></p>"/utf8>>},
        markdown:to_html(<<"[foo<http://example.com/?search=](uri)>"/utf8>>),
        "should prefer autolinks over links"
    ),
    ok.

-spec test_link_resource_case_49(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_49(_Config) ->
    %% Extra
    ?assertMatch(
        {ok, <<"<p><a href=\"\"></a></p>"/utf8>>},
        markdown:to_html(<<"[]()"/utf8>>),
        "should support an empty link"
    ),
    ok.

-spec test_link_resource_case_50(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_50(_Config) ->
    %% See: <https://github.com/commonmark/commonmark.js/issues/192>
    ?assertMatch(
        {ok, <<"<p><a href=\"\"></a></p>"/utf8>>},
        markdown:to_html(<<"[](<> \"\")"/utf8>>),
        "should ignore an empty title"
    ),
    ok.

-spec test_link_resource_case_51(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_51(_Config) ->
    ?assertMatch(
        {ok, <<"<p>[a](<b>&quot;c&quot;)</p>"/utf8>>},
        markdown:to_html_with_options(<<"[a](<b>\"c\")"/utf8>>, ?danger),
        "should require whitespace between enclosed destination and title"
    ),
    ok.

-spec test_link_resource_case_52(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_52(_Config) ->
    ?assertMatch(
        {ok, <<"<p>[](&lt;</p>"/utf8>>},
        markdown:to_html(<<"[](<"/utf8>>),
        "should not support an unclosed enclosed destination"
    ),
    ok.

-spec test_link_resource_case_53(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_53(_Config) ->
    ?assertMatch(
        {ok, <<"<p>[](</p>"/utf8>>},
        markdown:to_html(<<"[]("/utf8>>),
        "should not support an unclosed destination"
    ),
    ok.

-spec test_link_resource_case_54(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_54(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"%3C\"></a></p>"/utf8>>},
        markdown:to_html(<<"[](\\<)"/utf8>>),
        "should support unenclosed link destination starting w/ escapes"
    ),
    ok.

-spec test_link_resource_case_55(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_55(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"%3C\"></a></p>"/utf8>>},
        markdown:to_html(<<"[](<\\<>)"/utf8>>),
        "should support enclosed link destination starting w/ escapes"
    ),
    ok.

-spec test_link_resource_case_56(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_56(_Config) ->
    ?assertMatch(
        {ok, <<"<p>[](\\</p>"/utf8>>},
        markdown:to_html(<<"[](\\"/utf8>>),
        "should not support unenclosed link destination starting w/ an incorrect escape"
    ),
    ok.

-spec test_link_resource_case_57(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_57(_Config) ->
    ?assertMatch(
        {ok, <<"<p>[](&lt;\\</p>"/utf8>>},
        markdown:to_html(<<"[](<\\"/utf8>>),
        "should not support enclosed link destination starting w/ an incorrect escape"
    ),
    ok.

-spec test_link_resource_case_58(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_58(_Config) ->
    ?assertMatch(
        {ok, <<"<p>[](a &quot;</p>"/utf8>>},
        markdown:to_html(<<"[](a \""/utf8>>),
        "should not support an eof in a link title (1)"
    ),
    ok.

-spec test_link_resource_case_59(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_59(_Config) ->
    ?assertMatch(
        {ok, <<"<p>[](a '</p>"/utf8>>},
        markdown:to_html(<<"[](a '"/utf8>>),
        "should not support an eof in a link title (2)"
    ),
    ok.

-spec test_link_resource_case_60(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_60(_Config) ->
    ?assertMatch(
        {ok, <<"<p>[](a (</p>"/utf8>>},
        markdown:to_html(<<"[](a ("/utf8>>),
        "should not support an eof in a link title (3)"
    ),
    ok.

-spec test_link_resource_case_61(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_61(_Config) ->
    ?assertMatch(
        {ok, <<"<p>[](a &quot;\\</p>"/utf8>>},
        markdown:to_html(<<"[](a \"\\"/utf8>>),
        "should not support an eof in a link title escape (1)"
    ),
    ok.

-spec test_link_resource_case_62(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_62(_Config) ->
    ?assertMatch(
        {ok, <<"<p>[](a '\\</p>"/utf8>>},
        markdown:to_html(<<"[](a '\\"/utf8>>),
        "should not support an eof in a link title escape (2)"
    ),
    ok.

-spec test_link_resource_case_63(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_63(_Config) ->
    ?assertMatch(
        {ok, <<"<p>[](a (\\</p>"/utf8>>},
        markdown:to_html(<<"[](a (\\"/utf8>>),
        "should not support an eof in a link title escape (3)"
    ),
    ok.

-spec test_link_resource_case_64(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_64(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"a\" title=\"&quot;\"></a></p>"/utf8>>},
        markdown:to_html(<<"[](a \"\\\"\")"/utf8>>),
        "should support a character escape to start a link title (1)"
    ),
    ok.

-spec test_link_resource_case_65(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_65(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"a\" title=\"'\"></a></p>"/utf8>>},
        markdown:to_html(<<"[](a '\\'')"/utf8>>),
        "should support a character escape to start a link title (2)"
    ),
    ok.

-spec test_link_resource_case_66(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_66(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"a\" title=\")\"></a></p>"/utf8>>},
        markdown:to_html(<<"[](a (\\)))"/utf8>>),
        "should support a character escape to start a link title (3)"
    ),
    ok.

-spec test_link_resource_case_67(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_67(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"example.com/&amp;%C2%A9&amp;\" title=\"&amp;©&amp;\">&amp;©&amp;</a></p>"/utf8>>},
        markdown:to_html(<<"[&amp;&copy;&](example.com/&amp;&copy;& \"&amp;&copy;&\")"/utf8>>),
        "should support character references in links"
    ),
    ok.

-spec test_link_resource_case_68(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_68(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"1()\">a</a></p>"/utf8>>},
        markdown:to_html(<<"[a](1())"/utf8>>),
        "should support 1 set of parens"
    ),
    ok.

-spec test_link_resource_case_69(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_69(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"1(2())\">a</a></p>"/utf8>>},
        markdown:to_html(<<"[a](1(2()))"/utf8>>),
        "should support 2 sets of parens"
    ),
    ok.

-spec test_link_resource_case_70(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_70(_Config) ->
    ?assertMatch(
        {ok,
            <<"<p><a href=\"1(2(3(4(5(6(7(8(9(10(11(12(13(14(15(16(17(18(19(20(21(22(23(24(25(26(27(28(29(30(31(32())))))))))))))))))))))))))))))))\">a</a></p>"/utf8>>},
        markdown:to_html(
            <<"[a](1(2(3(4(5(6(7(8(9(10(11(12(13(14(15(16(17(18(19(20(21(22(23(24(25(26(27(28(29(30(31(32()))))))))))))))))))))))))))))))))"/utf8>>
        ),
        "should support 32 sets of parens"
    ),
    ok.

-spec test_link_resource_case_71(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_71(_Config) ->
    ?assertMatch(
        {ok,
            <<"<p>[a](1(2(3(4(5(6(7(8(9(10(11(12(13(14(15(16(17(18(19(20(21(22(23(24(25(26(27(28(29(30(31(32(33())))))))))))))))))))))))))))))))))</p>"/utf8>>},
        markdown:to_html(
            <<"[a](1(2(3(4(5(6(7(8(9(10(11(12(13(14(15(16(17(18(19(20(21(22(23(24(25(26(27(28(29(30(31(32(33())))))))))))))))))))))))))))))))))"/utf8>>
        ),
        "should not support 33 or more sets of parens"
    ),
    ok.

-spec test_link_resource_case_72(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_72(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"b\" title=\"\nc\">a</a></p>"/utf8>>},
        markdown:to_html(<<"[a](b \"\n c\")"/utf8>>),
        "should support an eol at the start of a title"
    ),
    ok.

-spec test_link_resource_case_73(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_73(_Config) ->
    ?assertMatch(
        {ok, <<"<p>[a](b( &quot;c&quot;)</p>"/utf8>>},
        markdown:to_html(<<"[a](b( \"c\")"/utf8>>),
        "should not support whitespace when unbalanced in a raw destination"
    ),
    ok.

-spec test_link_resource_case_74(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_74(_Config) ->
    ?assertMatch(
        {ok, <<"<p><a href=\"%EF%BF%BD\">a</a></p>"/utf8>>},
        markdown:to_html(<<"[a]( )"/utf8>>),
        "should support a single NUL character as a link resource"
    ),
    ok.

-spec test_link_resource_case_75(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_75(_Config) ->
    ?assertEqual(
        {ok,
            markdown_mdast_node:root(#markdown_mdast_root{
                children = ?'vec!'([
                    markdown_mdast_node:paragraph(#markdown_mdast_paragraph{
                        children = ?'vec!'([
                            markdown_mdast_node:text(#markdown_mdast_text{
                                value = <<"a ">>,
                                position = {some, markdown_unist_position:new(1, 1, 0, 1, 3, 2)}
                            }),
                            markdown_mdast_node:link(#markdown_mdast_link{
                                url = <<"">>,
                                title = none,
                                children = ?'vec!'([
                                    markdown_mdast_node:text(#markdown_mdast_text{
                                        value = <<"alpha">>,
                                        position = {some, markdown_unist_position:new(1, 4, 3, 1, 9, 8)}
                                    })
                                ]),
                                position = {some, markdown_unist_position:new(1, 3, 2, 1, 12, 11)}
                            }),
                            markdown_mdast_node:text(#markdown_mdast_text{
                                value = <<" b ">>,
                                position = {some, markdown_unist_position:new(1, 12, 11, 1, 15, 14)}
                            }),
                            markdown_mdast_node:link(#markdown_mdast_link{
                                url = <<"charlie">>,
                                title = {some, <<"delta">>},
                                children = ?'vec!'([
                                    markdown_mdast_node:text(#markdown_mdast_text{
                                        value = <<"bravo">>,
                                        position = {some, markdown_unist_position:new(1, 16, 15, 1, 21, 20)}
                                    })
                                ]),
                                position = {some, markdown_unist_position:new(1, 15, 14, 1, 39, 38)}
                            }),
                            markdown_mdast_node:text(#markdown_mdast_text{
                                value = <<" c.">>,
                                position = {some, markdown_unist_position:new(1, 39, 38, 1, 42, 41)}
                            })
                        ]),
                        position = {some, markdown_unist_position:new(1, 1, 0, 1, 42, 41)}
                    })
                ]),
                position = {some, markdown_unist_position:new(1, 1, 0, 1, 42, 41)}
            })},
        markdown:to_mdast(<<"a [alpha]() b [bravo](charlie 'delta') c."/utf8>>, markdown_parse_options:default()),
        "should support link (resource) as `Link`s in mdast"
    ),
    ok.

-spec test_link_resource_case_76(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_link_resource_case_76(_Config) ->
    ?assertEqual(
        {ok,
            markdown_mdast_node:root(#markdown_mdast_root{
                children = ?'vec!'([
                    markdown_mdast_node:paragraph(#markdown_mdast_paragraph{
                        children = ?'vec!'([
                            markdown_mdast_node:link(#markdown_mdast_link{
                                children = ?'vec!'([
                                    markdown_mdast_node:image(#markdown_mdast_image{
                                        alt = <<"name">>,
                                        url = <<"image">>,
                                        title = none,
                                        position = {some, markdown_unist_position:new(1, 2, 1, 1, 16, 15)}
                                    })
                                ]),
                                url = <<"url">>,
                                title = none,
                                position = {some, markdown_unist_position:new(1, 1, 0, 1, 22, 21)}
                            })
                        ]),
                        position = {some, markdown_unist_position:new(1, 1, 0, 1, 22, 21)}
                    })
                ]),
                position = {some, markdown_unist_position:new(1, 1, 0, 1, 22, 21)}
            })},
        markdown:to_mdast(<<"[![name](image)](url)"/utf8>>, markdown_parse_options:default()),
        "should support nested links in mdast"
    ),
    ok.
