%%% % DO NOT EDIT: this file was generated by 'just codegen'
%%% % @generated SignedSource<<f9e49eeb3a11b3ea39719638bb1e05a8>>
%%%-----------------------------------------------------------------------------
%%% Copyright (c) Meta Platforms, Inc. and affiliates.
%%% Copyright (c) WhatsApp LLC
%%%
%%% This source code is licensed under the MIT license found in the
%%% LICENSE.md file in the root directory of this source tree.
%%%-----------------------------------------------------------------------------
%%% % @format
-module(markdown_gfm_task_list_item_SUITE).
-moduledoc """

""".
-moduledoc #{author => ["Andrew Bennett <potatosaladx@meta.com>"]}.
-moduledoc #{created => "", modified => ""}.
-moduledoc #{copyright => "Meta Platforms, Inc. and affiliates."}.
-compile(warn_missing_spec_all).
-oncall("whatsapp_clr").

-include_lib("markdown/include/markdown_mdast.hrl").
-include_lib("markdown/include/markdown_util.hrl").
-include_lib("stdlib/include/assert.hrl").

-behaviour(ct_suite).

%% ct_suite callbacks
-export([
    all/0,
    groups/0,
    init_per_suite/1,
    end_per_suite/1,
    init_per_group/2,
    end_per_group/2
]).

%% Test Cases
-export([
    test_gfm_task_list_item_case_1/1,
    test_gfm_task_list_item_case_2/1,
    test_gfm_task_list_item_case_3/1,
    test_gfm_task_list_item_case_4/1,
    test_gfm_task_list_item_case_5/1,
    test_gfm_task_list_item_case_6/1,
    test_gfm_task_list_item_case_7/1,
    test_gfm_task_list_item_case_8/1,
    test_gfm_task_list_item_case_9/1
]).

%%%=============================================================================
%%% ct_suite callbacks
%%%=============================================================================

-spec all() -> markdown_test:all().
all() ->
    [
        {group, static}
    ].

-spec groups() -> markdown_test:groups().
groups() ->
    [
        {static, [parallel], [
            test_gfm_task_list_item_case_1,
            test_gfm_task_list_item_case_2,
            test_gfm_task_list_item_case_3,
            test_gfm_task_list_item_case_4,
            test_gfm_task_list_item_case_5,
            test_gfm_task_list_item_case_6,
            test_gfm_task_list_item_case_7,
            test_gfm_task_list_item_case_8,
            test_gfm_task_list_item_case_9
        ]}
    ].

-spec init_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:init_per_suite().
init_per_suite(Config) ->
    Config.

-spec end_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:end_per_suite().
end_per_suite(_Config) ->
    ok.

-spec init_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:init_per_group().
init_per_group(_Group, Config) ->
    Config.

-spec end_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:end_per_group().
end_per_group(_Group, _Config) ->
    ok.

%%%=============================================================================
%%% Test Cases
%%%=============================================================================

-spec test_gfm_task_list_item_case_1(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_task_list_item_case_1(_Config) ->
    ?assertMatch(
        {ok, <<"<ul>\n<li>[x] y.</li>\n</ul>"/utf8>>},
        markdown:to_html(<<"* [x] y."/utf8>>),
        "should ignore task list item checks by default"
    ),
    ok.

-spec test_gfm_task_list_item_case_2(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_task_list_item_case_2(_Config) ->
    ?assertMatch(
        {ok, <<"<ul>\n<li><input type=\"checkbox\" disabled=\"\" checked=\"\" /> y.</li>\n</ul>"/utf8>>},
        markdown:to_html_with_options(<<"* [x] y."/utf8>>, markdown_options:gfm()),
        "should support task list item checks"
    ),
    ok.

-spec test_gfm_task_list_item_case_3(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_task_list_item_case_3(_Config) ->
    ?assertMatch(
        {ok, <<"<ul>\n<li><input type=\"checkbox\" disabled=\"\" /> z.</li>\n</ul>"/utf8>>},
        markdown:to_html_with_options(<<"* [ ] z."/utf8>>, markdown_options:gfm()),
        "should support unchecked task list item checks"
    ),
    ok.

-spec test_gfm_task_list_item_case_4(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_task_list_item_case_4(_Config) ->
    ?assertMatch(
        {ok, <<"<ul>\n<li><input type=\"checkbox\" checked=\"\" /> y.</li>\n</ul>"/utf8>>},
        markdown:to_html_with_options(
            <<"* [x] y."/utf8>>, markdown_options:gfm(#{compile => #{gfm_task_list_item_checkable => true}})
        ),
        "should support option for enabled (checkable) task list item checks"
    ),
    ok.

-spec test_gfm_task_list_item_case_5(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_task_list_item_case_5(_Config) ->
    ?assertMatch(
        {ok, <<"<ul>\n<li>[x]</li>\n</ul>"/utf8>>},
        markdown:to_html_with_options(<<"*\n    [x]"/utf8>>, markdown_options:gfm()),
        "should not support laziness (1)"
    ),
    ok.

-spec test_gfm_task_list_item_case_6(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_task_list_item_case_6(_Config) ->
    ?assertMatch(
        {ok, <<"<ul>\n<li></li>\n</ul>\n<p>[x]</p>"/utf8>>},
        markdown:to_html_with_options(<<"*\n[x]"/utf8>>, markdown_options:gfm()),
        "should not support laziness (2)"
    ),
    ok.

-spec test_gfm_task_list_item_case_7(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_task_list_item_case_7(_Config) ->
    ?assertMatch(
        {ok, <<"""
        <ul>
        <li><input type="checkbox" disabled="" /> foo</li>
        <li><input type="checkbox" disabled="" checked="" /> bar</li>
        </ul>
        <ul>
        <li><input type="checkbox" disabled="" checked="" /> foo
        <ul>
        <li><input type="checkbox" disabled="" /> bar</li>
        <li><input type="checkbox" disabled="" checked="" /> baz</li>
        </ul>
        </li>
        <li><input type="checkbox" disabled="" /> bim</li>
        </ul>
        <ul>
        <li><input type="checkbox" disabled="" /> Unchecked?</li>
        </ul>
        <ul>
        <li><input type="checkbox" disabled="" checked="" /> Checked?</li>
        </ul>
        <ul>
        <li>[y] What is this even?</li>
        </ul>
        <ul>
        <li><input type="checkbox" disabled="" /> After a definition</li>
        </ul>
        <ul>
        <li>
        <h1>[ ] In a setext heading</h1>
        </li>
        </ul>
        <ul>
        <li>
        <p>In the…</p>
        <p>[ ] Second paragraph</p>
        </li>
        </ul>
        <ul>
        <li><input type="checkbox" disabled="" /> With a tab</li>
        </ul>
        <ul>
        <li><input type="checkbox" disabled="" checked="" /> With an upper case <code>x</code></li>
        </ul>
        <ul>
        <li><input type="checkbox" disabled="" /> In a lazy line</li>
        </ul>
        <ul>
        <li>[  ] With two spaces</li>
        </ul>
        <ul>
        <li><input type="checkbox" disabled="" checked="" /> Two spaces indent</li>
        </ul>
        <ul>
        <li><input type="checkbox" disabled="" checked="" /> Three spaces indent</li>
        </ul>
        <ul>
        <li><input type="checkbox" disabled="" checked="" /> Four spaces indent</li>
        </ul>
        <ul>
        <li>
        <pre><code>[x] Five spaces indent
        </code></pre>
        </li>
        </ul>
        <p>[ ] here?</p>
        <ul>
        <li>
        <blockquote>
        <p>[ ] here?</p>
        </blockquote>
        </li>
        </ul>
        <ul>
        <li>[ ]No space?</li>
        </ul>
        <p>Empty?</p>
        <ul>
        <li>[ ]</li>
        </ul>
        <p>Space after:</p>
        <ul>
        <li>[ ]</li>
        </ul>
        <ul>
        <li><input type="checkbox" disabled="" /> Text.</li>
        </ul>
        <p>Tab after:</p>
        <ul>
        <li>[ ]</li>
        </ul>
        <ul>
        <li><input type="checkbox" disabled="" />	Text.</li>
        </ul>
        <p>EOL after:</p>
        <ul>
        <li>[ ]</li>
        </ul>
        <ul>
        <li><input type="checkbox" disabled="" />
        Text.</li>
        </ul>
        <ul>
        <li><input type="checkbox" disabled="" /> after blank?</li>
        </ul>
        <ul>
        <li>
        <h1>[ ] ATX Heading</h1>
        </li>
        </ul>
        <blockquote>
        <ul>
        <li><input type="checkbox" disabled="" checked="" /> In a list in a block quote</li>
        </ul>
        </blockquote>

        """/utf8>>},
        markdown:to_html_with_options(<<"""

        * [ ] foo
        * [x] bar

        - [x] foo
          - [ ] bar
          - [x] baz
        - [ ] bim

        + [ ] Unchecked?

        * [x] Checked?

        + [y] What is this even?

        - [n]: #
          [ ] After a definition

        + [ ] In a setext heading
          =======================

        * In the…

          [ ] Second paragraph

        - [	] With a tab

        + [X] With an upper case `x`

        * [
        ] In a lazy line

        - [  ] With two spaces

        +  [x] Two spaces indent

        *   [x] Three spaces indent

        -    [x] Four spaces indent

        +     [x] Five spaces indent

        [ ] here?

        * > [ ] here?

        - [ ]No space?

        Empty?

        + [ ]

        Space after:

        + [ ] 

        * [ ] Text.

        Tab after:

        + [ ]	

        * [ ]	Text.

        EOL after:

        + [ ]

        * [ ]
          Text.

        -
          [ ] after blank?

        + # [ ] ATX Heading

        > * [x] In a list in a block quote

        """/utf8>>, markdown_options:gfm()),
        "should handle things like GitHub"
    ),
    ok.

-spec test_gfm_task_list_item_case_8(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_task_list_item_case_8(_Config) ->
    ?assertEqual(
        {ok,
            markdown_mdast_node:root(#markdown_mdast_root{
                children = ?'vec!'([
                    markdown_mdast_node:list(#markdown_mdast_list{
                        ordered = false,
                        spread = false,
                        start = none,
                        children = ?'vec!'([
                            markdown_mdast_node:list_item(#markdown_mdast_list_item{
                                checked = {some, true},
                                spread = false,
                                children = ?'vec!'([
                                    markdown_mdast_node:paragraph(#markdown_mdast_paragraph{
                                        children = ?'vec!'([
                                            markdown_mdast_node:text(#markdown_mdast_text{
                                                value = <<"a">>,
                                                position = {some, markdown_unist_position:new(1, 7, 6, 1, 8, 7)}
                                            })
                                        ]),
                                        position = {some, markdown_unist_position:new(1, 7, 6, 1, 8, 7)}
                                    })
                                ]),
                                position = {some, markdown_unist_position:new(1, 1, 0, 1, 8, 7)}
                            }),
                            markdown_mdast_node:list_item(#markdown_mdast_list_item{
                                checked = {some, false},
                                spread = false,
                                children = ?'vec!'([
                                    markdown_mdast_node:paragraph(#markdown_mdast_paragraph{
                                        children = ?'vec!'([
                                            markdown_mdast_node:text(#markdown_mdast_text{
                                                value = <<"b">>,
                                                position = {some, markdown_unist_position:new(2, 7, 14, 2, 8, 15)}
                                            })
                                        ]),
                                        position = {some, markdown_unist_position:new(2, 7, 14, 2, 8, 15)}
                                    })
                                ]),
                                position = {some, markdown_unist_position:new(2, 1, 8, 2, 8, 15)}
                            }),
                            markdown_mdast_node:list_item(#markdown_mdast_list_item{
                                checked = none,
                                spread = false,
                                children = ?'vec!'([
                                    markdown_mdast_node:paragraph(#markdown_mdast_paragraph{
                                        children = ?'vec!'([
                                            markdown_mdast_node:text(#markdown_mdast_text{
                                                value = <<"c">>,
                                                position = {some, markdown_unist_position:new(3, 3, 18, 3, 4, 19)}
                                            })
                                        ]),
                                        position = {some, markdown_unist_position:new(3, 3, 18, 3, 4, 19)}
                                    })
                                ]),
                                position = {some, markdown_unist_position:new(3, 1, 16, 3, 4, 19)}
                            })
                        ]),
                        position = {some, markdown_unist_position:new(1, 1, 0, 3, 4, 19)}
                    })
                ]),
                position = {some, markdown_unist_position:new(1, 1, 0, 3, 4, 19)}
            })},
        markdown:to_mdast(<<"* [x] a\n* [ ] b\n* c"/utf8>>, markdown_parse_options:gfm()),
        "should support task list items as `checked` fields on `ListItem`s in mdast"
    ),
    ok.

-spec test_gfm_task_list_item_case_9(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_task_list_item_case_9(_Config) ->
    ?assertEqual(
        {ok,
            markdown_mdast_node:root(#markdown_mdast_root{
                children = ?'vec!'([
                    markdown_mdast_node:list(#markdown_mdast_list{
                        ordered = false,
                        spread = false,
                        start = none,
                        children = ?'vec!'([
                            markdown_mdast_node:list_item(#markdown_mdast_list_item{
                                checked = {some, true},
                                spread = false,
                                children = ?'vec!'([
                                    markdown_mdast_node:paragraph(#markdown_mdast_paragraph{
                                        children = ?'vec!'([
                                            markdown_mdast_node:text(#markdown_mdast_text{
                                                value = <<"a">>,
                                                position = {some, markdown_unist_position:new(2, 1, 7, 2, 4, 10)}
                                            })
                                        ]),
                                        position = {some, markdown_unist_position:new(2, 1, 7, 2, 4, 10)}
                                    })
                                ]),
                                position = {some, markdown_unist_position:new(1, 1, 0, 2, 4, 10)}
                            }),
                            markdown_mdast_node:list_item(#markdown_mdast_list_item{
                                checked = {some, false},
                                spread = false,
                                children = ?'vec!'([
                                    markdown_mdast_node:paragraph(#markdown_mdast_paragraph{
                                        children = ?'vec!'([
                                            markdown_mdast_node:text(#markdown_mdast_text{
                                                value = <<"  b">>,
                                                position = {some, markdown_unist_position:new(3, 7, 17, 3, 10, 20)}
                                            })
                                        ]),
                                        position = {some, markdown_unist_position:new(3, 7, 17, 3, 10, 20)}
                                    })
                                ]),
                                position = {some, markdown_unist_position:new(3, 1, 11, 3, 10, 20)}
                            }),
                            markdown_mdast_node:list_item(#markdown_mdast_list_item{
                                checked = {some, true},
                                spread = false,
                                children = ?'vec!'([
                                    markdown_mdast_node:paragraph(#markdown_mdast_paragraph{
                                        children = ?'vec!'([
                                            markdown_mdast_node:emphasis(#markdown_mdast_emphasis{
                                                children = ?'vec!'([
                                                    markdown_mdast_node:text(#markdown_mdast_text{
                                                        value = <<"c">>,
                                                        position =
                                                            {some, markdown_unist_position:new(5, 2, 30, 5, 3, 31)}
                                                    })
                                                ]),
                                                position = {some, markdown_unist_position:new(5, 1, 29, 5, 4, 32)}
                                            })
                                        ]),
                                        position = {some, markdown_unist_position:new(5, 1, 29, 5, 4, 32)}
                                    })
                                ]),
                                position = {some, markdown_unist_position:new(4, 1, 21, 5, 4, 32)}
                            })
                        ]),
                        position = {some, markdown_unist_position:new(1, 1, 0, 5, 4, 32)}
                    })
                ]),
                position = {some, markdown_unist_position:new(1, 1, 0, 5, 4, 32)}
            })},
        markdown:to_mdast(<<"* [x]\r\n  a\n* [ ]   b\n* [x]\t \r*c*"/utf8>>, markdown_parse_options:gfm()),
        "should handle lots of whitespace after checkbox, and non-text"
    ),
    ok.
