%%% % DO NOT EDIT: this file was generated by 'just codegen'
%%% % @generated SignedSource<<e3c854e540580640b866bd658eb4c533>>
%%%-----------------------------------------------------------------------------
%%% %CopyrightBegin%
%%%
%%% SPDX-License-Identifier: Apache-2.0
%%%
%%% Copyright (c) Meta Platforms, Inc. and affiliates.
%%% Copyright (c) WhatsApp LLC
%%%
%%% Licensed under the Apache License, Version 2.0 (the "License");
%%% you may not use this file except in compliance with the License.
%%% You may obtain a copy of the License at
%%%
%%%     http://www.apache.org/licenses/LICENSE-2.0
%%%
%%% Unless required by applicable law or agreed to in writing, software
%%% distributed under the License is distributed on an "AS IS" BASIS,
%%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%%% See the License for the specific language governing permissions and
%%% limitations under the License.
%%%
%%% %CopyrightEnd%
%%%-----------------------------------------------------------------------------
%%% % @format
-module(markdown_thematic_break_SUITE).
-moduledoc """

""".
-moduledoc #{author => ["Andrew Bennett <potatosaladx@meta.com>"]}.
-moduledoc #{created => "2025-10-28", modified => "2025-10-28"}.
-moduledoc #{copyright => "Meta Platforms, Inc. and affiliates."}.
-compile(warn_missing_spec_all).
-oncall("whatsapp_clr").

-include_lib("markdown/include/markdown_mdast.hrl").
-include_lib("markdown/include/markdown_util.hrl").
-include_lib("stdlib/include/assert.hrl").

-behaviour(ct_suite).

%% ct_suite callbacks
-export([
    all/0,
    groups/0,
    init_per_suite/1,
    end_per_suite/1,
    init_per_group/2,
    end_per_group/2
]).

%% Test Cases
-export([
    test_thematic_break_case_1/1,
    test_thematic_break_case_2/1,
    test_thematic_break_case_3/1,
    test_thematic_break_case_4/1,
    test_thematic_break_case_5/1,
    test_thematic_break_case_6/1,
    test_thematic_break_case_7/1,
    test_thematic_break_case_8/1,
    test_thematic_break_case_9/1,
    test_thematic_break_case_10/1,
    test_thematic_break_case_11/1,
    test_thematic_break_case_12/1,
    test_thematic_break_case_13/1,
    test_thematic_break_case_14/1,
    test_thematic_break_case_15/1,
    test_thematic_break_case_16/1,
    test_thematic_break_case_17/1,
    test_thematic_break_case_18/1,
    test_thematic_break_case_19/1,
    test_thematic_break_case_20/1,
    test_thematic_break_case_21/1,
    test_thematic_break_case_22/1,
    test_thematic_break_case_23/1,
    test_thematic_break_case_24/1,
    test_thematic_break_case_25/1,
    test_thematic_break_case_26/1,
    test_thematic_break_case_27/1,
    test_thematic_break_case_28/1,
    test_thematic_break_case_29/1
]).

%%%=============================================================================
%%% ct_suite callbacks
%%%=============================================================================

-spec all() -> markdown_test:all().
all() ->
    [
        {group, static}
    ].

-spec groups() -> markdown_test:groups().
groups() ->
    [
        {static, [parallel], [
            test_thematic_break_case_1,
            test_thematic_break_case_2,
            test_thematic_break_case_3,
            test_thematic_break_case_4,
            test_thematic_break_case_5,
            test_thematic_break_case_6,
            test_thematic_break_case_7,
            test_thematic_break_case_8,
            test_thematic_break_case_9,
            test_thematic_break_case_10,
            test_thematic_break_case_11,
            test_thematic_break_case_12,
            test_thematic_break_case_13,
            test_thematic_break_case_14,
            test_thematic_break_case_15,
            test_thematic_break_case_16,
            test_thematic_break_case_17,
            test_thematic_break_case_18,
            test_thematic_break_case_19,
            test_thematic_break_case_20,
            test_thematic_break_case_21,
            test_thematic_break_case_22,
            test_thematic_break_case_23,
            test_thematic_break_case_24,
            test_thematic_break_case_25,
            test_thematic_break_case_26,
            test_thematic_break_case_27,
            test_thematic_break_case_28,
            test_thematic_break_case_29
        ]}
    ].

-spec init_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:init_per_suite().
init_per_suite(Config) ->
    Config.

-spec end_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:end_per_suite().
end_per_suite(_Config) ->
    ok.

-spec init_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:init_per_group().
init_per_group(_Group, Config) ->
    Config.

-spec end_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:end_per_group().
end_per_group(_Group, _Config) ->
    ok.

%%%=============================================================================
%%% Test Cases
%%%=============================================================================

-spec test_thematic_break_case_1(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_1(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />\n<hr />\n<hr />"/utf8>>},
        markdown:to_html(<<"***\n---\n___"/utf8>>),
        "should support thematic breaks w/ asterisks, dashes, and underscores"
    ),
    ok.

-spec test_thematic_break_case_2(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_2(_Config) ->
    ?assertMatch(
        {ok, <<"<p>+++</p>"/utf8>>},
        markdown:to_html(<<"+++"/utf8>>),
        "should not support thematic breaks w/ plusses"
    ),
    ok.

-spec test_thematic_break_case_3(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_3(_Config) ->
    ?assertMatch(
        {ok, <<"<p>===</p>"/utf8>>},
        markdown:to_html(<<"==="/utf8>>),
        "should not support thematic breaks w/ equals"
    ),
    ok.

-spec test_thematic_break_case_4(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_4(_Config) ->
    ?assertMatch(
        {ok, <<"<p>--</p>"/utf8>>},
        markdown:to_html(<<"--"/utf8>>),
        "should not support thematic breaks w/ two dashes"
    ),
    ok.

-spec test_thematic_break_case_5(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_5(_Config) ->
    ?assertMatch(
        {ok, <<"<p>**</p>"/utf8>>},
        markdown:to_html(<<"**"/utf8>>),
        "should not support thematic breaks w/ two asterisks"
    ),
    ok.

-spec test_thematic_break_case_6(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_6(_Config) ->
    ?assertMatch(
        {ok, <<"<p>__</p>"/utf8>>},
        markdown:to_html(<<"__"/utf8>>),
        "should not support thematic breaks w/ two underscores"
    ),
    ok.

-spec test_thematic_break_case_7(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_7(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />"/utf8>>},
        markdown:to_html(<<" ***"/utf8>>),
        "should support thematic breaks w/ 1 space"
    ),
    ok.

-spec test_thematic_break_case_8(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_8(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />"/utf8>>},
        markdown:to_html(<<"  ***"/utf8>>),
        "should support thematic breaks w/ 2 spaces"
    ),
    ok.

-spec test_thematic_break_case_9(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_9(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />"/utf8>>},
        markdown:to_html(<<"   ***"/utf8>>),
        "should support thematic breaks w/ 3 spaces"
    ),
    ok.

-spec test_thematic_break_case_10(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_10(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code>***\n</code></pre>"/utf8>>},
        markdown:to_html(<<"    ***"/utf8>>),
        "should not support thematic breaks w/ 4 spaces"
    ),
    ok.

-spec test_thematic_break_case_11(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_11(_Config) ->
    ?assertMatch(
        {ok, <<"<p>Foo\n***</p>"/utf8>>},
        markdown:to_html(<<"Foo\n    ***"/utf8>>),
        "should not support thematic breaks w/ 4 spaces as paragraph continuation"
    ),
    ok.

-spec test_thematic_break_case_12(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_12(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />"/utf8>>},
        markdown:to_html(<<"_____________________________________"/utf8>>),
        "should support thematic breaks w/ many markers"
    ),
    ok.

-spec test_thematic_break_case_13(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_13(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />"/utf8>>},
        markdown:to_html(<<" - - -"/utf8>>),
        "should support thematic breaks w/ spaces (1)"
    ),
    ok.

-spec test_thematic_break_case_14(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_14(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />"/utf8>>},
        markdown:to_html(<<" **  * ** * ** * **"/utf8>>),
        "should support thematic breaks w/ spaces (2)"
    ),
    ok.

-spec test_thematic_break_case_15(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_15(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />"/utf8>>},
        markdown:to_html(<<"-     -      -      -"/utf8>>),
        "should support thematic breaks w/ spaces (3)"
    ),
    ok.

-spec test_thematic_break_case_16(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_16(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />"/utf8>>},
        markdown:to_html(<<"- - - -    "/utf8>>),
        "should support thematic breaks w/ trailing spaces"
    ),
    ok.

-spec test_thematic_break_case_17(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_17(_Config) ->
    ?assertMatch(
        {ok, <<"<p>_ _ _ _ a</p>"/utf8>>},
        markdown:to_html(<<"_ _ _ _ a"/utf8>>),
        "should not support thematic breaks w/ other characters (1)"
    ),
    ok.

-spec test_thematic_break_case_18(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_18(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a------</p>"/utf8>>},
        markdown:to_html(<<"a------"/utf8>>),
        "should not support thematic breaks w/ other characters (2)"
    ),
    ok.

-spec test_thematic_break_case_19(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_19(_Config) ->
    ?assertMatch(
        {ok, <<"<p>---a---</p>"/utf8>>},
        markdown:to_html(<<"---a---"/utf8>>),
        "should not support thematic breaks w/ other characters (3)"
    ),
    ok.

-spec test_thematic_break_case_20(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_20(_Config) ->
    ?assertMatch(
        {ok, <<"<p><em>-</em></p>"/utf8>>},
        markdown:to_html(<<" *-*"/utf8>>),
        "should not support thematic breaks w/ mixed markers"
    ),
    ok.

-spec test_thematic_break_case_21(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_21(_Config) ->
    ?assertMatch(
        {ok, <<"<ul>\n<li>foo</li>\n</ul>\n<hr />\n<ul>\n<li>bar</li>\n</ul>"/utf8>>},
        markdown:to_html(<<"- foo\n***\n- bar"/utf8>>),
        "should support thematic breaks mixed w/ lists (1)"
    ),
    ok.

-spec test_thematic_break_case_22(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_22(_Config) ->
    ?assertMatch(
        {ok, <<"<ul>\n<li>Foo</li>\n</ul>\n<hr />\n<ul>\n<li>Bar</li>\n</ul>"/utf8>>},
        markdown:to_html(<<"* Foo\n* * *\n* Bar"/utf8>>),
        "should support thematic breaks mixed w/ lists (2)"
    ),
    ok.

-spec test_thematic_break_case_23(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_23(_Config) ->
    ?assertMatch(
        {ok, <<"<p>Foo</p>\n<hr />\n<p>bar</p>"/utf8>>},
        markdown:to_html(<<"Foo\n***\nbar"/utf8>>),
        "should support thematic breaks interrupting paragraphs"
    ),
    ok.

-spec test_thematic_break_case_24(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_24(_Config) ->
    ?assertMatch(
        {ok, <<"<h2>Foo</h2>\n<p>bar</p>"/utf8>>},
        markdown:to_html(<<"Foo\n---\nbar"/utf8>>),
        "should not support thematic breaks w/ dashes interrupting paragraphs (setext heading)"
    ),
    ok.

-spec test_thematic_break_case_25(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_25(_Config) ->
    ?assertMatch(
        {ok, <<"<ul>\n<li>Foo</li>\n<li>\n<hr />\n</li>\n</ul>"/utf8>>},
        markdown:to_html(<<"- Foo\n- * * *"/utf8>>),
        "should support thematic breaks in lists"
    ),
    ok.

-spec test_thematic_break_case_26(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_26(_Config) ->
    ?assertMatch(
        {ok, <<"<blockquote>\n<hr />\n</blockquote>\n<p>a</p>"/utf8>>},
        markdown:to_html(<<"> ---\na"/utf8>>),
        "should not support lazyness (1)"
    ),
    ok.

-spec test_thematic_break_case_27(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_27(_Config) ->
    ?assertMatch(
        {ok, <<"<blockquote>\n<p>a</p>\n</blockquote>\n<hr />"/utf8>>},
        markdown:to_html(<<"> a\n---"/utf8>>),
        "should not support lazyness (2)"
    ),
    ok.

-spec test_thematic_break_case_28(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_28(_Config) ->
    ?assertMatch(
        {ok, <<"<p>***</p>"/utf8>>},
        markdown:to_html_with_options(
            <<"***"/utf8>>, markdown_options:new(#{parse => #{constructs => #{thematic_break => false}}})
        ),
        "should support turning off thematic breaks"
    ),
    ok.

-spec test_thematic_break_case_29(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_thematic_break_case_29(_Config) ->
    ?assertEqual(
        {ok,
            markdown_mdast_node:root(#markdown_mdast_root{
                children = ?'vec!'([
                    markdown_mdast_node:thematic_break(#markdown_mdast_thematic_break{
                        position = {some, markdown_unist_position:new(1, 1, 0, 1, 4, 3)}
                    })
                ]),
                position = {some, markdown_unist_position:new(1, 1, 0, 1, 4, 3)}
            })},
        markdown:to_mdast(<<"***"/utf8>>, markdown_parse_options:new(#{})),
        "should support thematic breaks as `ThematicBreak`s in mdast"
    ),
    ok.
