%%% % DO NOT EDIT: this file was generated by 'just codegen'
%%% % @generated SignedSource<<7b8659f58a7704da9582b78f89e249dc>>
%%%-----------------------------------------------------------------------------
%%% %CopyrightBegin%
%%%
%%% SPDX-License-Identifier: Apache-2.0
%%%
%%% Copyright (c) Meta Platforms, Inc. and affiliates.
%%% Copyright (c) WhatsApp LLC
%%%
%%% Licensed under the Apache License, Version 2.0 (the "License");
%%% you may not use this file except in compliance with the License.
%%% You may obtain a copy of the License at
%%%
%%%     http://www.apache.org/licenses/LICENSE-2.0
%%%
%%% Unless required by applicable law or agreed to in writing, software
%%% distributed under the License is distributed on an "AS IS" BASIS,
%%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%%% See the License for the specific language governing permissions and
%%% limitations under the License.
%%%
%%% %CopyrightEnd%
%%%-----------------------------------------------------------------------------
%%% % @format
-module(markdown_gfm_tagfilter_SUITE).
-moduledoc """

""".
-moduledoc #{author => ["Andrew Bennett <potatosaladx@meta.com>"]}.
-moduledoc #{created => "", modified => ""}.
-moduledoc #{copyright => "Meta Platforms, Inc. and affiliates."}.
-compile(warn_missing_spec_all).
-oncall("whatsapp_clr").

-include_lib("markdown/include/markdown_mdast.hrl").
-include_lib("markdown/include/markdown_util.hrl").
-include_lib("stdlib/include/assert.hrl").

-behaviour(ct_suite).

%% ct_suite callbacks
-export([
    all/0,
    groups/0,
    init_per_suite/1,
    end_per_suite/1,
    init_per_group/2,
    end_per_group/2
]).

%% Test Cases
-export([
    test_gfm_tagfilter_case_1/1,
    test_gfm_tagfilter_case_2/1,
    test_gfm_tagfilter_case_3/1,
    test_gfm_tagfilter_case_4/1,
    test_gfm_tagfilter_case_5/1,
    test_gfm_tagfilter_case_6/1
]).

%%%=============================================================================
%%% ct_suite callbacks
%%%=============================================================================

-spec all() -> markdown_test:all().
all() ->
    [
        {group, static}
    ].

-spec groups() -> markdown_test:groups().
groups() ->
    [
        {static, [parallel], [
            test_gfm_tagfilter_case_1,
            test_gfm_tagfilter_case_2,
            test_gfm_tagfilter_case_3,
            test_gfm_tagfilter_case_4,
            test_gfm_tagfilter_case_5,
            test_gfm_tagfilter_case_6
        ]}
    ].

-spec init_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:init_per_suite().
init_per_suite(Config) ->
    Config.

-spec end_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:end_per_suite().
end_per_suite(_Config) ->
    ok.

-spec init_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:init_per_group().
init_per_group(_Group, Config) ->
    Config.

-spec end_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:end_per_group().
end_per_group(_Group, _Config) ->
    ok.

%%%=============================================================================
%%% Test Cases
%%%=============================================================================

-spec test_gfm_tagfilter_case_1(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_tagfilter_case_1(_Config) ->
    ?assertMatch(
        {ok, <<"<iframe>"/utf8>>},
        markdown:to_html_with_options(
            <<"<iframe>"/utf8>>, markdown_options:default(#{compile => #{allow_dangerous_html => true}})
        ),
        "should not filter by default"
    ),
    ok.

-spec test_gfm_tagfilter_case_2(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_tagfilter_case_2(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a &lt;i&gt;</p>\n&lt;script&gt;"/utf8>>},
        markdown:to_html_with_options(
            <<"a <i>\n<script>"/utf8>>, markdown_options:default(#{compile => #{gfm_tagfilter => true}})
        ),
        "should not turn `allow_dangerous_html` on"
    ),
    ok.

-spec test_gfm_tagfilter_case_3(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_tagfilter_case_3(_Config) ->
    ?assertMatch(
        {ok, <<"&lt;iframe>"/utf8>>},
        markdown:to_html_with_options(
            <<"<iframe>"/utf8>>,
            markdown_options:default(#{compile => #{allow_dangerous_html => true, gfm_tagfilter => true}})
        ),
        "should filter"
    ),
    ok.

-spec test_gfm_tagfilter_case_4(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_tagfilter_case_4(_Config) ->
    ?assertMatch(
        {ok, <<"&lt;iframe\n>"/utf8>>},
        markdown:to_html_with_options(
            <<"<iframe\n>"/utf8>>,
            markdown_options:default(#{compile => #{allow_dangerous_html => true, gfm_tagfilter => true}})
        ),
        "should filter when followed by a line ending (1)"
    ),
    ok.

-spec test_gfm_tagfilter_case_5(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_tagfilter_case_5(_Config) ->
    ?assertMatch(
        {ok, <<"<div\n>"/utf8>>},
        markdown:to_html_with_options(
            <<"<div\n>"/utf8>>,
            markdown_options:default(#{compile => #{allow_dangerous_html => true, gfm_tagfilter => true}})
        ),
        "should filter when followed by a line ending (2)"
    ),
    ok.

-spec test_gfm_tagfilter_case_6(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_gfm_tagfilter_case_6(_Config) ->
    ?assertMatch(
        {ok, <<"""
        &lt;title>
        <div title="&lt;title>"></div>
        <p><span title="&lt;title>"></span></p>
        <div>&lt;title>&lt;/title></div>
        <p><span>&lt;title>&lt;/title></span></p>
        <p><b>&lt;textarea>&lt;/textarea></b></p>
        <p>&lt;script/src=&quot;#&quot;&gt;</p>
        &lt;SCRIPT SRC=http://xss.rocks/xss.js>&lt;/SCRIPT>
        <IMG SRC="javascript:alert('XSS');">
        <p>&lt;IMG SRC=javascript:alert('XSS')&gt;</p>
        <p>&lt;IMG SRC=<code>javascript:alert(&quot;RSnake says, 'XSS'&quot;)</code>&gt;</p>
        <p>&lt;IMG &quot;&quot;&quot;&gt;&lt;SCRIPT>alert(&quot;XSS&quot;)&lt;/SCRIPT>&quot;&gt;</p>
        <p>&lt;SCRIPT/XSS SRC=&quot;http://xss.rocks/xss.js&quot;&gt;&lt;/SCRIPT></p>
        <BODY onload!#$%&()*~+-_.,:;?@[/|\]^`=alert("XSS")>
        <p>&lt;&lt;SCRIPT>alert(&quot;XSS&quot;);//&lt;&lt;/SCRIPT></p>
        &lt;SCRIPT SRC=http://xss.rocks/xss.js?< B >

        &lt;SCRIPT SRC=//xss.rocks/.j>

        &lt;/TITLE>&lt;SCRIPT>alert("XSS");&lt;/SCRIPT>
        &lt;STYLE>li {list-style-image: url("javascript:alert('XSS')");}&lt;/STYLE><UL><LI>XSS</br>
        <p>javascript:/<em>--&gt;&lt;/title>&lt;/style>&lt;/textarea>&lt;/script>&lt;/xmp>&lt;svg/onload='+/&quot;/+/onmouseover=1/+/[</em>/[]/+alert(1)//'&gt;</p>
        &lt;STYLE>@import'http://xss.rocks/xss.css';&lt;/STYLE>

        """/utf8>>},
        markdown:to_html_with_options(
            <<"\n<title>\n\n<div title=\"<title>\"></div>\n\n<span title=\"<title>\"></span>\n\n<div><title></title></div>\n\n<span><title></title></span>\n\n<b><textarea></textarea></b>\n\n<script/src=\"#\">\n\n<SCRIPT SRC=http://xss.rocks/xss.js></SCRIPT>\n\n<IMG SRC=\"javascript:alert('XSS');\">\n\n<IMG SRC=javascript:alert('XSS')>\n\n<IMG SRC=`javascript:alert(\"RSnake says, 'XSS'\")`>\n\n<IMG \"\"\"><SCRIPT>alert(\"XSS\")</SCRIPT>\"\\>\n\n<SCRIPT/XSS SRC=\"http://xss.rocks/xss.js\"></SCRIPT>\n\n<BODY onload!#$%&()*~+-_.,:;?@[/|\\]^`=alert(\"XSS\")>\n\n<<SCRIPT>alert(\"XSS\");//\\<</SCRIPT>\n\n<SCRIPT SRC=http://xss.rocks/xss.js?< B >\n\n<SCRIPT SRC=//xss.rocks/.j>\n\n</TITLE><SCRIPT>alert(\"XSS\");</SCRIPT>\n\n<STYLE>li {list-style-image: url(\"javascript:alert('XSS')\");}</STYLE><UL><LI>XSS</br>\n\njavascript:/*--></title></style></textarea></script></xmp><svg/onload='+/\"/+/onmouseover=1/+/[*/[]/+alert(1)//'>\n\n<STYLE>@import'http://xss.rocks/xss.css';</STYLE>\n"/utf8>>,
            markdown_options:default(#{compile => #{allow_dangerous_html => true, gfm_tagfilter => true}})
        ),
        "should handle things like GitHub"
    ),
    ok.
