%%% % DO NOT EDIT: this file was generated by 'just codegen'
%%% % @generated SignedSource<<060a37a33042101354b15fc44249c0d5>>
%%%-----------------------------------------------------------------------------
%%% %CopyrightBegin%
%%%
%%% SPDX-License-Identifier: Apache-2.0
%%%
%%% Copyright (c) Meta Platforms, Inc. and affiliates.
%%% Copyright (c) WhatsApp LLC
%%%
%%% Licensed under the Apache License, Version 2.0 (the "License");
%%% you may not use this file except in compliance with the License.
%%% You may obtain a copy of the License at
%%%
%%%     http://www.apache.org/licenses/LICENSE-2.0
%%%
%%% Unless required by applicable law or agreed to in writing, software
%%% distributed under the License is distributed on an "AS IS" BASIS,
%%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%%% See the License for the specific language governing permissions and
%%% limitations under the License.
%%%
%%% %CopyrightEnd%
%%%-----------------------------------------------------------------------------
%%% % @format
-module(markdown_mdx_esm_SUITE).
-moduledoc """

""".
-moduledoc #{author => ["Andrew Bennett <potatosaladx@meta.com>"]}.
-moduledoc #{created => "2025-10-09", modified => "2025-10-09"}.
-moduledoc #{copyright => "Meta Platforms, Inc. and affiliates."}.
-compile(warn_missing_spec_all).
-oncall("whatsapp_clr").

-include_lib("markdown/include/markdown_mdast.hrl").
-include_lib("markdown/include/markdown_util.hrl").
-include_lib("stdlib/include/assert.hrl").

-behaviour(ct_suite).

%% ct_suite callbacks
-export([
    all/0,
    groups/0,
    init_per_suite/1,
    end_per_suite/1,
    init_per_group/2,
    end_per_group/2
]).

%% Test Cases
-export([
    test_mdx_esm_case_1/1,
    test_mdx_esm_case_2/1,
    test_mdx_esm_case_3/1,
    test_mdx_esm_case_4/1,
    test_mdx_esm_case_5/1,
    test_mdx_esm_case_6/1,
    test_mdx_esm_case_7/1,
    test_mdx_esm_case_8/1,
    test_mdx_esm_case_9/1,
    test_mdx_esm_case_10/1,
    test_mdx_esm_case_11/1,
    test_mdx_esm_case_12/1,
    test_mdx_esm_case_13/1,
    test_mdx_esm_case_14/1,
    test_mdx_esm_case_15/1,
    test_mdx_esm_case_16/1,
    test_mdx_esm_case_17/1,
    test_mdx_esm_case_18/1,
    test_mdx_esm_case_19/1,
    test_mdx_esm_case_20/1,
    test_mdx_esm_case_21/1,
    test_mdx_esm_case_22/1,
    test_mdx_esm_case_23/1,
    test_mdx_esm_case_24/1,
    test_mdx_esm_case_25/1,
    test_mdx_esm_case_26/1,
    test_mdx_esm_case_27/1,
    test_mdx_esm_case_28/1,
    test_mdx_esm_case_29/1,
    test_mdx_esm_case_30/1,
    test_mdx_esm_case_31/1,
    test_mdx_esm_case_32/1,
    test_mdx_esm_case_33/1,
    test_mdx_esm_case_34/1,
    test_mdx_esm_case_35/1,
    test_mdx_esm_case_36/1,
    test_mdx_esm_case_37/1,
    test_mdx_esm_case_38/1,
    test_mdx_esm_case_39/1,
    test_mdx_esm_case_40/1,
    test_mdx_esm_case_41/1,
    test_mdx_esm_case_42/1,
    test_mdx_esm_case_43/1,
    test_mdx_esm_case_44/1,
    test_mdx_esm_case_45/1,
    test_mdx_esm_case_46/1,
    test_mdx_esm_case_47/1,
    test_mdx_esm_case_48/1,
    test_mdx_esm_case_49/1
]).

%% Macros
-define(swc,
    markdown_options:mdx(#{
        parse => #{
            mdx_expression_parse => {some, fun markdown_test_utils_swc:parse_expression/2},
            mdx_esm_parse => {some, fun markdown_test_utils_swc:parse_esm/1}
        }
    })
).
-define(swc_parse,
    markdown_parse_options:mdx(#{
        mdx_expression_parse => {some, fun markdown_test_utils_swc:parse_expression/2},
        mdx_esm_parse => {some, fun markdown_test_utils_swc:parse_esm/1}
    })
).

%%%=============================================================================
%%% ct_suite callbacks
%%%=============================================================================

-spec all() -> markdown_test:all().
all() ->
    [
        {group, static}
    ].

-spec groups() -> markdown_test:groups().
groups() ->
    [
        {static, [parallel], [
            test_mdx_esm_case_1,
            test_mdx_esm_case_2,
            test_mdx_esm_case_3,
            test_mdx_esm_case_4,
            test_mdx_esm_case_5,
            test_mdx_esm_case_6,
            test_mdx_esm_case_7,
            test_mdx_esm_case_8,
            test_mdx_esm_case_9,
            test_mdx_esm_case_10,
            test_mdx_esm_case_11,
            test_mdx_esm_case_12,
            test_mdx_esm_case_13,
            test_mdx_esm_case_14,
            test_mdx_esm_case_15,
            test_mdx_esm_case_16,
            test_mdx_esm_case_17,
            test_mdx_esm_case_18,
            test_mdx_esm_case_19,
            test_mdx_esm_case_20,
            test_mdx_esm_case_21,
            test_mdx_esm_case_22,
            test_mdx_esm_case_23,
            test_mdx_esm_case_24,
            test_mdx_esm_case_25,
            test_mdx_esm_case_26,
            test_mdx_esm_case_27,
            test_mdx_esm_case_28,
            test_mdx_esm_case_29,
            test_mdx_esm_case_30,
            test_mdx_esm_case_31,
            test_mdx_esm_case_32,
            test_mdx_esm_case_33,
            test_mdx_esm_case_34,
            test_mdx_esm_case_35,
            test_mdx_esm_case_36,
            test_mdx_esm_case_37,
            test_mdx_esm_case_38,
            test_mdx_esm_case_39,
            test_mdx_esm_case_40,
            test_mdx_esm_case_41,
            test_mdx_esm_case_42,
            test_mdx_esm_case_43,
            test_mdx_esm_case_44,
            test_mdx_esm_case_45,
            test_mdx_esm_case_46,
            test_mdx_esm_case_47,
            test_mdx_esm_case_48,
            test_mdx_esm_case_49
        ]}
    ].

-spec init_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:init_per_suite().
init_per_suite(Config) ->
    Config.

-spec end_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:end_per_suite().
end_per_suite(_Config) ->
    ok.

-spec init_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:init_per_group().
init_per_group(_Group, Config) ->
    Config.

-spec end_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:end_per_group().
end_per_group(_Group, _Config) ->
    ok.

%%%=============================================================================
%%% Test Cases
%%%=============================================================================

-spec test_mdx_esm_case_1(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_1(_Config) ->
    ?assertMatch(
        {ok, <<"<p>c</p>"/utf8>>},
        markdown:to_html_with_options(<<"import a from 'b'\n\nc"/utf8>>, ?swc),
        "should support an import"
    ),
    ok.

-spec test_mdx_esm_case_2(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_2(_Config) ->
    ?assertMatch(
        {ok, <<"<p>b</p>"/utf8>>},
        markdown:to_html_with_options(<<"export default a\n\nb"/utf8>>, ?swc),
        "should support an export"
    ),
    ok.

-spec test_mdx_esm_case_3(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_3(_Config) ->
    ?assertMatch(
        {ok, <<"<p>impossible</p>"/utf8>>},
        markdown:to_html_with_options(<<"impossible"/utf8>>, ?swc),
        "should not support other keywords (`impossible`)"
    ),
    ok.

-spec test_mdx_esm_case_4(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_4(_Config) ->
    ?assertMatch(
        {ok, <<"<p>exporting</p>"/utf8>>},
        markdown:to_html_with_options(<<"exporting"/utf8>>, ?swc),
        "should not support other keywords (`exporting`)"
    ),
    ok.

-spec test_mdx_esm_case_5(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_5(_Config) ->
    ?assertMatch(
        {ok, <<"<p>import.</p>"/utf8>>},
        markdown:to_html_with_options(<<"import."/utf8>>, ?swc),
        "should not support a non-whitespace after the keyword"
    ),
    ok.

-spec test_mdx_esm_case_6(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_6(_Config) ->
    ?assertMatch(
        {ok, <<"<p>import('a')</p>"/utf8>>},
        markdown:to_html_with_options(<<"import('a')"/utf8>>, ?swc),
        "should not support a non-whitespace after the keyword (import-as-a-function)"
    ),
    ok.

-spec test_mdx_esm_case_7(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_7(_Config) ->
    ?assertMatch(
        {ok, <<"<p>import a from 'b'\nexport default c</p>"/utf8>>},
        markdown:to_html_with_options(<<"  import a from 'b'\n  export default c"/utf8>>, ?swc),
        "should not support an indent"
    ),
    ok.

-spec test_mdx_esm_case_8(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_8(_Config) ->
    ?assertMatch(
        {ok, <<"<ul>\n<li>import a from 'b'</li>\n</ul>\n<blockquote>\n<p>export default c</p>\n</blockquote>"/utf8>>},
        markdown:to_html_with_options(<<"- import a from 'b'\n> export default c"/utf8>>, ?swc),
        "should not support keywords in containers"
    ),
    ok.

-spec test_mdx_esm_case_9(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_9(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"import a from 'b'\nexport default c"/utf8>>, ?swc),
        "should support imports and exports in the same “block”"
    ),
    ok.

-spec test_mdx_esm_case_10(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_10(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"import a from 'b'\n\nexport default c"/utf8>>, ?swc),
        "should support imports and exports in separate “blocks”"
    ),
    ok.

-spec test_mdx_esm_case_11(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_11(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a</p>\n<p>b</p>\n"/utf8>>},
        markdown:to_html_with_options(<<"a\n\nimport a from 'b'\n\nb\n\nexport default c"/utf8>>, ?swc),
        "should support imports and exports in between other constructs"
    ),
    ok.

-spec test_mdx_esm_case_12(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_12(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a\nimport a from 'b'</p>\n<p>b\nexport default c</p>"/utf8>>},
        markdown:to_html_with_options(<<"a\nimport a from 'b'\n\nb\nexport default c"/utf8>>, ?swc),
        "should not support import/exports when interrupting paragraphs"
    ),
    ok.

-spec test_mdx_esm_case_13(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_13(_Config) ->
    ?assertMatch(
        {ok, <<"<p>c</p>"/utf8>>},
        markdown:to_html_with_options(<<"export {\n  a\n} from 'b'\n\nc"/utf8>>, ?swc),
        "should support line endings in import/exports"
    ),
    ok.

-spec test_mdx_esm_case_14(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_14(_Config) ->
    ?assertMatch(
        {ok, <<"<p>c</p>"/utf8>>},
        markdown:to_html_with_options(<<"export {\n\n  a\n\n} from 'b'\n\nc"/utf8>>, ?swc),
        "should support blank lines in import/exports"
    ),
    ok.

-spec test_mdx_esm_case_15(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_15(_Config) ->
    ?assertMatch(
        {ok, <<"<p>d</p>"/utf8>>},
        markdown:to_html_with_options(<<"export var a = 1\n// b\n/* c */\n\nd"/utf8>>, ?swc),
        "should support comments in “blocks”"
    ),
    ok.

-spec test_mdx_esm_case_16(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_16(_Config) ->
    ?assertMatch(
        {ok, <<"<p>c</p>"/utf8>>},
        markdown:to_html_with_options(<<"import a from 'b'\nexport {a}\n\nc"/utf8>>, ?swc),
        "should support a reexport from another import"
    ),
    ok.

-spec test_mdx_esm_case_17(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_17(_Config) ->
    ?assertMatch(
        {ok, <<"<p>c</p>"/utf8>>},
        markdown:to_html_with_options(<<"import a from 'b';\nexport {a};\n\nc"/utf8>>, ?swc),
        "should support a reexport from another import w/ semicolons"
    ),
    ok.

-spec test_mdx_esm_case_18(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_18(_Config) ->
    ?assertMatch(
        {ok, <<"<p>c</p>"/utf8>>},
        markdown:to_html_with_options(<<"import a from 'b'\nexport {a as default}\n\nc"/utf8>>, ?swc),
        "should support a reexport default from another import"
    ),
    ok.

-spec test_mdx_esm_case_19(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_19(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"export var a = () => <b />"/utf8>>, ?swc),
        "should support JSX by default"
    ),
    ok.

-spec test_mdx_esm_case_20(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_20(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"export {a}\n"/utf8>>, ?swc),
        "should support EOF after EOL"
    ),
    ok.

-spec test_mdx_esm_case_21(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_21(_Config) ->
    ?assertMatch(
        {ok, <<"<p>c</p>"/utf8>>},
        markdown:to_html_with_options(<<"import a from 'b'\n\nexport {a}\n\nc"/utf8>>, ?swc),
        "should support a reexport from another esm block (1)"
    ),
    ok.

-spec test_mdx_esm_case_22(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_22(_Config) ->
    ?assertMatch(
        {ok, <<"<h1>c</h1>"/utf8>>},
        markdown:to_html_with_options(<<"import a from 'b'\n\nexport {a}\n\n# c"/utf8>>, ?swc),
        "should support a reexport from another esm block (2)"
    ),
    ok.

-spec test_mdx_esm_case_23(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_23(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"import a from \"b\""/utf8>>, ?swc),
        "should support imports: default"
    ),
    ok.

-spec test_mdx_esm_case_24(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_24(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"import * as a from \"b\""/utf8>>, ?swc),
        "should support imports: whole"
    ),
    ok.

-spec test_mdx_esm_case_25(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_25(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"import {a} from \"b\""/utf8>>, ?swc),
        "should support imports: destructuring"
    ),
    ok.

-spec test_mdx_esm_case_26(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_26(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"import {a as b} from \"c\""/utf8>>, ?swc),
        "should support imports: destructuring and rename"
    ),
    ok.

-spec test_mdx_esm_case_27(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_27(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"import a, {b as c} from \"d\""/utf8>>, ?swc),
        "should support imports: default and destructuring"
    ),
    ok.

-spec test_mdx_esm_case_28(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_28(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"import a, * as b from \"c\""/utf8>>, ?swc),
        "should support imports: default and whole"
    ),
    ok.

-spec test_mdx_esm_case_29(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_29(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"import \"a\""/utf8>>, ?swc),
        "should support imports: side-effects"
    ),
    ok.

-spec test_mdx_esm_case_30(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_30(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"export var a = \"\""/utf8>>, ?swc),
        "should support exports: var"
    ),
    ok.

-spec test_mdx_esm_case_31(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_31(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"export const a = \"\""/utf8>>, ?swc),
        "should support exports: const"
    ),
    ok.

-spec test_mdx_esm_case_32(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_32(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"export let a = \"\""/utf8>>, ?swc),
        "should support exports: let"
    ),
    ok.

-spec test_mdx_esm_case_33(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_33(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"export var a, b"/utf8>>, ?swc),
        "should support exports: multiple"
    ),
    ok.

-spec test_mdx_esm_case_34(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_34(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"export var a = \"a\", b = \"b\""/utf8>>, ?swc),
        "should support exports: multiple w/ assignment"
    ),
    ok.

-spec test_mdx_esm_case_35(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_35(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"export function a() {}"/utf8>>, ?swc),
        "should support exports: function"
    ),
    ok.

-spec test_mdx_esm_case_36(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_36(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"export class a {}"/utf8>>, ?swc),
        "should support exports: class"
    ),
    ok.

-spec test_mdx_esm_case_37(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_37(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"export var {a} = {}"/utf8>>, ?swc),
        "should support exports: destructuring"
    ),
    ok.

-spec test_mdx_esm_case_38(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_38(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"export var {a: b} = {}"/utf8>>, ?swc),
        "should support exports: rename destructuring"
    ),
    ok.

-spec test_mdx_esm_case_39(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_39(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"export var [a] = []"/utf8>>, ?swc),
        "should support exports: array destructuring"
    ),
    ok.

-spec test_mdx_esm_case_40(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_40(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"export default a = 1"/utf8>>, ?swc),
        "should support exports: default"
    ),
    ok.

-spec test_mdx_esm_case_41(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_41(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"export default function a() {}"/utf8>>, ?swc),
        "should support exports: default function"
    ),
    ok.

-spec test_mdx_esm_case_42(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_42(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"export default class a {}"/utf8>>, ?swc),
        "should support exports: default class"
    ),
    ok.

-spec test_mdx_esm_case_43(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_43(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"export * from \"a\""/utf8>>, ?swc),
        "should support exports: aggregate"
    ),
    ok.

-spec test_mdx_esm_case_44(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_44(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"export * as a from \"b\""/utf8>>, ?swc),
        "should support exports: whole reexport"
    ),
    ok.

-spec test_mdx_esm_case_45(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_45(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"export {a} from \"b\""/utf8>>, ?swc),
        "should support exports: reexport destructuring"
    ),
    ok.

-spec test_mdx_esm_case_46(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_46(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"export {a as b} from \"c\""/utf8>>, ?swc),
        "should support exports: reexport destructuring w rename"
    ),
    ok.

-spec test_mdx_esm_case_47(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_47(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"export {default} from \"b\""/utf8>>, ?swc),
        "should support exports: reexport as a default whole"
    ),
    ok.

-spec test_mdx_esm_case_48(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_48(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"export {default as a, b} from \"c\""/utf8>>, ?swc),
        "should support exports: reexport default and non-default"
    ),
    ok.

-spec test_mdx_esm_case_49(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_esm_case_49(_Config) ->
    ?assertEqual(
        {ok,
            markdown_mdast_node:root(#markdown_mdast_root{
                children = ?'vec!'([
                    markdown_mdast_node:mdxjs_esm(#markdown_mdast_mdxjs_esm{
                        value = <<"import a from 'b'\nexport {a}">>,
                        position = {some, markdown_unist_position:new(1, 1, 0, 2, 11, 28)},
                        stops = ?'vec!'([
                            markdown_mdast_stop:new(0, 0),
                            markdown_mdast_stop:new(17, 17),
                            markdown_mdast_stop:new(18, 18)
                        ])
                    })
                ]),
                position = {some, markdown_unist_position:new(1, 1, 0, 2, 11, 28)}
            })},
        markdown:to_mdast(<<"import a from 'b'\nexport {a}"/utf8>>, ?swc_parse),
        "should support mdx esm as `MdxjsEsm`s in mdast"
    ),
    ok.
