%%% % DO NOT EDIT: this file was generated by 'just codegen'
%%% % @generated SignedSource<<3cd9121fb521b69d9861e210f5c25c0b>>
%%%-----------------------------------------------------------------------------
%%% %CopyrightBegin%
%%%
%%% SPDX-License-Identifier: Apache-2.0
%%%
%%% Copyright (c) Meta Platforms, Inc. and affiliates.
%%% Copyright (c) WhatsApp LLC
%%%
%%% Licensed under the Apache License, Version 2.0 (the "License");
%%% you may not use this file except in compliance with the License.
%%% You may obtain a copy of the License at
%%%
%%%     http://www.apache.org/licenses/LICENSE-2.0
%%%
%%% Unless required by applicable law or agreed to in writing, software
%%% distributed under the License is distributed on an "AS IS" BASIS,
%%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%%% See the License for the specific language governing permissions and
%%% limitations under the License.
%%%
%%% %CopyrightEnd%
%%%-----------------------------------------------------------------------------
%%% % @format
-module(markdown_mdx_expression_flow_SUITE).
-moduledoc """

""".
-moduledoc #{author => ["Andrew Bennett <potatosaladx@meta.com>"]}.
-moduledoc #{created => "2025-10-28", modified => "2025-10-28"}.
-moduledoc #{copyright => "Meta Platforms, Inc. and affiliates."}.
-compile(warn_missing_spec_all).
-oncall("whatsapp_clr").

-include_lib("markdown/include/markdown_mdast.hrl").
-include_lib("markdown/include/markdown_util.hrl").
-include_lib("stdlib/include/assert.hrl").

-behaviour(ct_suite).

%% ct_suite callbacks
-export([
    all/0,
    groups/0,
    init_per_suite/1,
    end_per_suite/1,
    init_per_group/2,
    end_per_group/2
]).

%% Test Cases
-export([
    test_mdx_expression_flow_case_1/1,
    test_mdx_expression_flow_case_2/1,
    %% Note: in MDX, indented code is turned off:
    test_mdx_expression_flow_case_3/1,
    test_mdx_expression_flow_case_4/1,
    test_mdx_expression_flow_case_5/1,
    test_mdx_expression_flow_case_6/1,
    test_mdx_expression_flow_case_7/1,
    test_mdx_expression_flow_case_8/1,
    test_mdx_expression_flow_case_9/1,
    test_mdx_expression_flow_case_10/1,
    test_mdx_expression_flow_case_11/1,
    test_mdx_expression_flow_case_12/1,
    test_mdx_expression_flow_case_13/1,
    test_mdx_expression_flow_case_14/1,
    test_mdx_expression_flow_case_15/1,
    test_mdx_expression_flow_case_16/1,
    test_mdx_expression_flow_case_17/1,
    test_mdx_expression_flow_case_18/1,
    test_mdx_expression_flow_case_19/1,
    test_mdx_expression_flow_case_20/1,
    test_mdx_expression_flow_case_21/1,
    test_mdx_expression_flow_case_22/1,
    test_mdx_expression_flow_case_23/1,
    test_mdx_expression_flow_case_24/1,
    test_mdx_expression_flow_case_25/1,
    test_mdx_expression_flow_case_26/1,
    test_mdx_expression_flow_case_27/1,
    test_mdx_expression_flow_case_28/1,
    test_mdx_expression_flow_case_29/1,
    test_mdx_expression_flow_case_30/1,
    test_mdx_expression_flow_case_31/1,
    test_mdx_expression_flow_case_32/1,
    test_mdx_expression_flow_case_33/1,
    test_mdx_expression_flow_case_34/1,
    test_mdx_expression_flow_case_35/1,
    test_mdx_expression_flow_case_36/1,
    test_mdx_expression_flow_case_37/1,
    test_mdx_expression_flow_case_38/1,
    %% Note: `erlang-markdown` has no `allowEmpty`.
    test_mdx_expression_flow_case_39/1,
    test_mdx_expression_flow_case_40/1
]).

%% Macros
-define(mdx, markdown_options:mdx(#{})).
-define(swc,
    markdown_options:mdx(#{
        parse => #{
            mdx_expression_parse => {some, fun markdown_test_utils_swc:parse_expression/2},
            mdx_esm_parse => {some, fun markdown_test_utils_swc:parse_esm/1}
        }
    })
).
-define(mdx_parse, markdown_parse_options:mdx(#{})).
-define(swc_parse,
    markdown_parse_options:mdx(#{
        mdx_expression_parse => {some, fun markdown_test_utils_swc:parse_expression/2},
        mdx_esm_parse => {some, fun markdown_test_utils_swc:parse_esm/1}
    })
).

%%%=============================================================================
%%% ct_suite callbacks
%%%=============================================================================

-spec all() -> markdown_test:all().
all() ->
    [
        {group, static}
    ].

-spec groups() -> markdown_test:groups().
groups() ->
    [
        {static, [parallel], [
            test_mdx_expression_flow_case_1,
            test_mdx_expression_flow_case_2,
            %% Note: in MDX, indented code is turned off:
            test_mdx_expression_flow_case_3,
            test_mdx_expression_flow_case_4,
            test_mdx_expression_flow_case_5,
            test_mdx_expression_flow_case_6,
            test_mdx_expression_flow_case_7,
            test_mdx_expression_flow_case_8,
            test_mdx_expression_flow_case_9,
            test_mdx_expression_flow_case_10,
            test_mdx_expression_flow_case_11,
            test_mdx_expression_flow_case_12,
            test_mdx_expression_flow_case_13,
            test_mdx_expression_flow_case_14,
            test_mdx_expression_flow_case_15,
            test_mdx_expression_flow_case_16,
            test_mdx_expression_flow_case_17,
            test_mdx_expression_flow_case_18,
            test_mdx_expression_flow_case_19,
            test_mdx_expression_flow_case_20,
            test_mdx_expression_flow_case_21,
            test_mdx_expression_flow_case_22,
            test_mdx_expression_flow_case_23,
            test_mdx_expression_flow_case_24,
            test_mdx_expression_flow_case_25,
            test_mdx_expression_flow_case_26,
            test_mdx_expression_flow_case_27,
            test_mdx_expression_flow_case_28,
            test_mdx_expression_flow_case_29,
            test_mdx_expression_flow_case_30,
            test_mdx_expression_flow_case_31,
            test_mdx_expression_flow_case_32,
            test_mdx_expression_flow_case_33,
            test_mdx_expression_flow_case_34,
            test_mdx_expression_flow_case_35,
            test_mdx_expression_flow_case_36,
            test_mdx_expression_flow_case_37,
            test_mdx_expression_flow_case_38,
            %% Note: `erlang-markdown` has no `allowEmpty`.
            test_mdx_expression_flow_case_39,
            test_mdx_expression_flow_case_40
        ]}
    ].

-spec init_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:init_per_suite().
init_per_suite(Config) ->
    Config.

-spec end_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:end_per_suite().
end_per_suite(_Config) ->
    ok.

-spec init_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:init_per_group().
init_per_group(_Group, Config) ->
    Config.

-spec end_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:end_per_group().
end_per_group(_Group, _Config) ->
    ok.

%%%=============================================================================
%%% Test Cases
%%%=============================================================================

-spec test_mdx_expression_flow_case_1(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_1(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"{a}"/utf8>>, ?mdx),
        "should support an expression"
    ),
    ok.

-spec test_mdx_expression_flow_case_2(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_2(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"{}"/utf8>>, ?mdx),
        "should support an empty expression"
    ),
    ok.

-spec test_mdx_expression_flow_case_3(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_3(_Config) ->
    %% Note: in MDX, indented code is turned off:
    ?assertMatch(
        {ok, <<"<pre><code>{}\n</code></pre>"/utf8>>},
        markdown:to_html_with_options(
            <<"    {}"/utf8>>, markdown_options:new(#{parse => #{constructs => #{mdx_expression_flow => true}}})
        ),
        "should prefer indented code over expressions if it’s enabled"
    ),
    ok.

-spec test_mdx_expression_flow_case_4(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_4(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(
            <<"   {}"/utf8>>, markdown_options:new(#{parse => #{constructs => #{mdx_expression_flow => true}}})
        ),
        "should support indented expressions if indented code is enabled"
    ),
    ok.

-spec test_mdx_expression_flow_case_5(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_5(_Config) ->
    ?assertMatch(
        {ok,
            <<"1:3: Unexpected end of file in expression, expected a corresponding closing brace for `{` (erlang-markdown:unexpected-eof)"/utf8>>},
        markdown:to_html_with_options(<<"{a"/utf8>>, ?mdx),
        "should crash if no closing brace is found (1)"
    ),
    ok.

-spec test_mdx_expression_flow_case_6(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_6(_Config) ->
    ?assertMatch(
        {ok,
            <<"1:9: Unexpected end of file in expression, expected a corresponding closing brace for `{` (erlang-markdown:unexpected-eof)"/utf8>>},
        markdown:to_html_with_options(<<"{b { c }"/utf8>>, ?mdx),
        "should crash if no closing brace is found (2)"
    ),
    ok.

-spec test_mdx_expression_flow_case_7(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_7(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a</p>"/utf8>>},
        markdown:to_html_with_options(<<"{\n}\na"/utf8>>, ?mdx),
        "should support a line ending in an expression"
    ),
    ok.

-spec test_mdx_expression_flow_case_8(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_8(_Config) ->
    ?assertMatch(
        {ok, <<"<p>b</p>"/utf8>>},
        markdown:to_html_with_options(<<"{ a } \t\nb"/utf8>>, ?mdx),
        "should support expressions followed by spaces"
    ),
    ok.

-spec test_mdx_expression_flow_case_9(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_9(_Config) ->
    ?assertMatch(
        {ok, <<"<p>b</p>"/utf8>>},
        markdown:to_html_with_options(<<"  { a }\nb"/utf8>>, ?mdx),
        "should support expressions preceded by spaces"
    ),
    ok.

-spec test_mdx_expression_flow_case_10(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_10(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a</p>\n<ul>\n<li>b</li>\n</ul>"/utf8>>},
        markdown:to_html_with_options(<<"a\n\n* b"/utf8>>, ?mdx),
        "should support lists after non-expressions (wooorm/erlang-markdown#11)"
    ),
    ok.

-spec test_mdx_expression_flow_case_11(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_11(_Config) ->
    ?assertMatch(
        {ok,
            <<"2:1: Unexpected lazy line in expression in container, expected line to be prefixed with `>` when in a block quote, whitespace when in a list, etc (erlang-markdown:unexpected-lazy)"/utf8>>},
        markdown:to_html_with_options(<<"> {a\nb}"/utf8>>, ?mdx),
        "should not support lazyness (1)"
    ),
    ok.

-spec test_mdx_expression_flow_case_12(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_12(_Config) ->
    ?assertMatch(
        {ok, <<"<blockquote>\n<p>a</p>\n</blockquote>\n"/utf8>>},
        markdown:to_html_with_options(<<"> a\n{b}"/utf8>>, ?mdx),
        "should not support lazyness (2)"
    ),
    ok.

-spec test_mdx_expression_flow_case_13(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_13(_Config) ->
    ?assertMatch(
        {ok, <<"<blockquote>\n</blockquote>\n<p>b</p>"/utf8>>},
        markdown:to_html_with_options(<<"> {a}\nb"/utf8>>, ?mdx),
        "should not support lazyness (3)"
    ),
    ok.

-spec test_mdx_expression_flow_case_14(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_14(_Config) ->
    ?assertMatch(
        {ok,
            <<"3:1: Unexpected lazy line in expression in container, expected line to be prefixed with `>` when in a block quote, whitespace when in a list, etc (erlang-markdown:unexpected-lazy)"/utf8>>},
        markdown:to_html_with_options(<<"> {\n> a\nb}"/utf8>>, ?mdx),
        "should not support lazyness (4)"
    ),
    ok.

-spec test_mdx_expression_flow_case_15(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_15(_Config) ->
    ?assertEqual(
        {ok,
            markdown_mdast_node:root(#markdown_mdast_root{
                children = ?'vec!'([
                    markdown_mdast_node:mdx_flow_expression(#markdown_mdast_mdx_flow_expression{
                        value = <<"alpha +\nbravo">>,
                        position = {some, markdown_unist_position:new(1, 1, 0, 2, 7, 15)},
                        stops = ?'vec!'([
                            markdown_mdast_stop:new(0, 1),
                            markdown_mdast_stop:new(7, 8),
                            markdown_mdast_stop:new(8, 9)
                        ])
                    })
                ]),
                position = {some, markdown_unist_position:new(1, 1, 0, 2, 7, 15)}
            })},
        markdown:to_mdast(<<"{alpha +\nbravo}"/utf8>>, ?mdx_parse),
        "should support mdx expressions (flow) as `MdxFlowExpression`s in mdast"
    ),
    ok.

-spec test_mdx_expression_flow_case_16(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_16(_Config) ->
    ?assertEqual(
        {ok,
            markdown_mdast_node:root(#markdown_mdast_root{
                children = ?'vec!'([
                    markdown_mdast_node:mdx_flow_expression(#markdown_mdast_mdx_flow_expression{
                        value = <<"`\n  a\n`">>,
                        position = {some, markdown_unist_position:new(1, 3, 2, 3, 5, 15)},
                        stops = ?'vec!'([
                            markdown_mdast_stop:new(0, 3),
                            markdown_mdast_stop:new(1, 4),
                            markdown_mdast_stop:new(2, 7),
                            markdown_mdast_stop:new(5, 10),
                            markdown_mdast_stop:new(6, 13)
                        ])
                    })
                ]),
                position = {some, markdown_unist_position:new(1, 1, 0, 3, 5, 15)}
            })},
        markdown:to_mdast(<<"  {`\n    a\n  `}"/utf8>>, ?mdx_parse),
        "should support indent in `MdxFlowExpression` in mdast"
    ),
    ok.

-spec test_mdx_expression_flow_case_17(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_17(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"{a}"/utf8>>, ?swc),
        "should support an expression"
    ),
    ok.

-spec test_mdx_expression_flow_case_18(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_18(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"{}"/utf8>>, ?swc),
        "should support an empty expression"
    ),
    ok.

-spec test_mdx_expression_flow_case_19(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_19(_Config) ->
    ?assertMatch(
        {ok,
            <<"1:3: Unexpected end of file in expression, expected a corresponding closing brace for `{` (erlang-markdown:unexpected-eof)"/utf8>>},
        markdown:to_html_with_options(<<"{a"/utf8>>, ?swc),
        "should crash if no closing brace is found (1)"
    ),
    ok.

-spec test_mdx_expression_flow_case_20(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_20(_Config) ->
    ?assertMatch(
        {ok, <<"1:9: Could not parse expression with swc: Unexpected content after expression (mdx:swc)"/utf8>>},
        markdown:to_html_with_options(<<"{b { c }"/utf8>>, ?swc),
        "should crash if no closing brace is found (2)"
    ),
    ok.

-spec test_mdx_expression_flow_case_21(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_21(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a</p>"/utf8>>},
        markdown:to_html_with_options(<<"{\n}\na"/utf8>>, ?swc),
        "should support a line ending in an expression"
    ),
    ok.

-spec test_mdx_expression_flow_case_22(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_22(_Config) ->
    ?assertMatch(
        {ok, <<"<p>b</p>"/utf8>>},
        markdown:to_html_with_options(<<"{ a } \t\nb"/utf8>>, ?swc),
        "should support expressions followed by spaces"
    ),
    ok.

-spec test_mdx_expression_flow_case_23(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_23(_Config) ->
    ?assertMatch(
        {ok, <<"<p>b</p>"/utf8>>},
        markdown:to_html_with_options(<<"  { a }\nb"/utf8>>, ?swc),
        "should support expressions preceded by spaces"
    ),
    ok.

-spec test_mdx_expression_flow_case_24(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_24(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"  {`\n    a\n  `}"/utf8>>, ?swc),
        "should support indented expressions"
    ),
    ok.

-spec test_mdx_expression_flow_case_25(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_25(_Config) ->
    ?assertMatch(
        {ok, <<"<p>ac</p>"/utf8>>},
        markdown:to_html_with_options(<<"a{(b)}c"/utf8>>, ?swc),
        "should support expressions padded w/ parens"
    ),
    ok.

-spec test_mdx_expression_flow_case_26(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_26(_Config) ->
    ?assertMatch(
        {ok, <<"<p>af</p>"/utf8>>},
        markdown:to_html_with_options(<<"a{/* b */ ( (c) /* d */ + (e) )}f"/utf8>>, ?swc),
        "should support expressions padded w/ parens and comments"
    ),
    ok.

-spec test_mdx_expression_flow_case_27(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_27(_Config) ->
    ?assertEqual(
        {ok,
            markdown_mdast_node:root(#markdown_mdast_root{
                children = ?'vec!'([
                    markdown_mdast_node:mdx_flow_expression(#markdown_mdast_mdx_flow_expression{
                        value = <<"`\n  `">>,
                        position = {some, markdown_unist_position:new(1, 1, 0, 2, 7, 6)},
                        stops = ?'vec!'([
                            markdown_mdast_stop:new(0, 1),
                            markdown_mdast_stop:new(1, 2),
                            markdown_mdast_stop:new(2, 3)
                        ])
                    })
                ]),
                position = {some, markdown_unist_position:new(1, 1, 0, 2, 7, 6)}
            })},
        markdown:to_mdast(<<"{`\n\t`}"/utf8>>, ?swc_parse),
        "should use correct positional info when tabs are used (1, indent)"
    ),
    ok.

-spec test_mdx_expression_flow_case_28(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_28(_Config) ->
    ?assertEqual(
        {ok,
            markdown_mdast_node:root(#markdown_mdast_root{
                children = ?'vec!'([
                    markdown_mdast_node:mdx_flow_expression(#markdown_mdast_mdx_flow_expression{
                        value = <<"`\nalpha\t`">>,
                        position = {some, markdown_unist_position:new(1, 1, 0, 2, 11, 11)},
                        stops = ?'vec!'([
                            markdown_mdast_stop:new(0, 1),
                            markdown_mdast_stop:new(1, 2),
                            markdown_mdast_stop:new(2, 3)
                        ])
                    })
                ]),
                position = {some, markdown_unist_position:new(1, 1, 0, 2, 11, 11)}
            })},
        markdown:to_mdast(<<"{`\nalpha\t`}"/utf8>>, ?swc_parse),
        "should use correct positional info when tabs are used (2, content)"
    ),
    ok.

-spec test_mdx_expression_flow_case_29(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_29(_Config) ->
    ?assertEqual(
        {ok,
            markdown_mdast_node:root(#markdown_mdast_root{
                children = ?'vec!'([
                    markdown_mdast_node:blockquote(#markdown_mdast_blockquote{
                        children = ?'vec!'([
                            markdown_mdast_node:paragraph(#markdown_mdast_paragraph{
                                children = ?'vec!'([
                                    markdown_mdast_node:text(#markdown_mdast_text{
                                        value = <<"aaa ">>,
                                        position = {some, markdown_unist_position:new(1, 4, 3, 1, 8, 7)}
                                    }),
                                    markdown_mdast_node:mdx_jsx_text_element(#markdown_mdast_mdx_jsx_text_element{
                                        children = ?'vec!'([]),
                                        name = {some, <<"b">>},
                                        attributes = ?'vec!'([
                                            markdown_mdast_attribute_content:property(#markdown_mdast_mdx_jsx_attribute{
                                                name = <<"c">>,
                                                value =
                                                    {some,
                                                        markdown_mdast_attribute_value:expression(
                                                            #markdown_mdast_attribute_value_expression{
                                                                value = <<"`\n   d\n`">>,
                                                                stops = ?'vec!'([
                                                                    markdown_mdast_stop:new(0, 13),
                                                                    markdown_mdast_stop:new(1, 14),
                                                                    markdown_mdast_stop:new(2, 19),
                                                                    markdown_mdast_stop:new(6, 23),
                                                                    markdown_mdast_stop:new(7, 27)
                                                                ])
                                                            }
                                                        )}
                                            })
                                        ]),
                                        position = {some, markdown_unist_position:new(1, 8, 7, 3, 9, 32)}
                                    }),
                                    markdown_mdast_node:text(#markdown_mdast_text{
                                        value = <<" eee">>,
                                        position = {some, markdown_unist_position:new(3, 9, 32, 3, 13, 36)}
                                    })
                                ]),
                                position = {some, markdown_unist_position:new(1, 3, 2, 3, 13, 36)}
                            })
                        ]),
                        position = {some, markdown_unist_position:new(1, 1, 0, 3, 13, 36)}
                    })
                ]),
                position = {some, markdown_unist_position:new(1, 1, 0, 3, 13, 36)}
            })},
        markdown:to_mdast(<<">  aaa <b c={`\n>      d\n>  `} /> eee"/utf8>>, ?swc_parse),
        "should support template strings in JSX (text) in block quotes"
    ),
    ok.

-spec test_mdx_expression_flow_case_30(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_30(_Config) ->
    ?assertEqual(
        {ok,
            markdown_mdast_node:root(#markdown_mdast_root{
                children = ?'vec!'([
                    markdown_mdast_node:blockquote(#markdown_mdast_blockquote{
                        children = ?'vec!'([
                            markdown_mdast_node:paragraph(#markdown_mdast_paragraph{
                                children = ?'vec!'([
                                    markdown_mdast_node:text(#markdown_mdast_text{
                                        value = <<"ab ">>,
                                        position = {some, markdown_unist_position:new(1, 3, 2, 1, 6, 5)}
                                    }),
                                    markdown_mdast_node:mdx_text_expression(#markdown_mdast_mdx_text_expression{
                                        value = <<"`\n`">>,
                                        stops = ?'vec!'([
                                            markdown_mdast_stop:new(0, 6),
                                            markdown_mdast_stop:new(1, 7),
                                            markdown_mdast_stop:new(2, 10)
                                        ]),
                                        position = {some, markdown_unist_position:new(1, 6, 5, 2, 7, 12)}
                                    })
                                ]),
                                position = {some, markdown_unist_position:new(1, 3, 2, 2, 7, 12)}
                            })
                        ]),
                        position = {some, markdown_unist_position:new(1, 1, 0, 2, 7, 12)}
                    })
                ]),
                position = {some, markdown_unist_position:new(1, 1, 0, 2, 7, 12)}
            })},
        markdown:to_mdast(<<"> ab {`\n>\t`}"/utf8>>, ?swc_parse),
        "should use correct positional when there are virtual spaces due to a block quote"
    ),
    ok.

-spec test_mdx_expression_flow_case_31(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_31(_Config) ->
    ?assertEqual(
        {ok,
            markdown_mdast_node:root(#markdown_mdast_root{
                children = ?'vec!'([
                    markdown_mdast_node:blockquote(#markdown_mdast_blockquote{
                        children = ?'vec!'([
                            markdown_mdast_node:mdx_flow_expression(#markdown_mdast_mdx_flow_expression{
                                value = <<"`\nalpha\nbravo\ncharlie\n delta\n`">>,
                                position = {some, markdown_unist_position:new(1, 3, 2, 6, 5, 49)},
                                stops = ?'vec!'([
                                    markdown_mdast_stop:new(0, 3),
                                    markdown_mdast_stop:new(1, 4),
                                    markdown_mdast_stop:new(2, 7),
                                    markdown_mdast_stop:new(7, 12),
                                    markdown_mdast_stop:new(8, 16),
                                    markdown_mdast_stop:new(13, 21),
                                    markdown_mdast_stop:new(14, 26),
                                    markdown_mdast_stop:new(21, 33),
                                    markdown_mdast_stop:new(22, 38),
                                    markdown_mdast_stop:new(28, 44),
                                    markdown_mdast_stop:new(29, 47)
                                ])
                            })
                        ]),
                        position = {some, markdown_unist_position:new(1, 1, 0, 6, 5, 49)}
                    })
                ]),
                position = {some, markdown_unist_position:new(1, 1, 0, 6, 5, 49)}
            })},
        markdown:to_mdast(<<"> {`\n> alpha\n>  bravo\n>   charlie\n>    delta\n> `}"/utf8>>, ?swc_parse),
        "should keep the correct number of spaces in a blockquote (flow)"
    ),
    ok.

-spec test_mdx_expression_flow_case_32(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_32(_Config) ->
    ?assertEqual(
        {ok,
            markdown_mdast_node:root(#markdown_mdast_root{
                children = ?'vec!'([
                    markdown_mdast_node:blockquote(#markdown_mdast_blockquote{
                        children = ?'vec!'([
                            markdown_mdast_node:mdx_flow_expression(#markdown_mdast_mdx_flow_expression{
                                value = <<"`\nalpha\nbravo\ncharlie\n delta\n`">>,
                                position = {some, markdown_unist_position:new(1, 3, 2, 6, 5, 49)},
                                stops = ?'vec!'([
                                    markdown_mdast_stop:new(0, 3),
                                    markdown_mdast_stop:new(1, 4),
                                    markdown_mdast_stop:new(2, 7),
                                    markdown_mdast_stop:new(7, 12),
                                    markdown_mdast_stop:new(8, 16),
                                    markdown_mdast_stop:new(13, 21),
                                    markdown_mdast_stop:new(14, 26),
                                    markdown_mdast_stop:new(21, 33),
                                    markdown_mdast_stop:new(22, 38),
                                    markdown_mdast_stop:new(28, 44),
                                    markdown_mdast_stop:new(29, 47)
                                ])
                            })
                        ]),
                        position = {some, markdown_unist_position:new(1, 1, 0, 6, 5, 49)}
                    })
                ]),
                position = {some, markdown_unist_position:new(1, 1, 0, 6, 5, 49)}
            })},
        markdown:to_mdast(<<"> {`\n> alpha\n>  bravo\n>   charlie\n>    delta\n> `}"/utf8>>, ?swc_parse),
        "should keep the correct number of spaces in a blockquote (flow)"
    ),
    ok.

-spec test_mdx_expression_flow_case_33(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_33(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"<a {...b} />"/utf8>>, ?swc),
        "should support a spread"
    ),
    ok.

-spec test_mdx_expression_flow_case_34(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_34(_Config) ->
    ?assertMatch(
        {ok,
            <<"1:5: Unexpected prop in spread (such as `{x}`): only a spread is supported (such as `{...x}`) (mdx:swc)"/utf8>>},
        markdown:to_html_with_options(<<"<a {b} />"/utf8>>, ?swc),
        "should crash if not a spread"
    ),
    ok.

-spec test_mdx_expression_flow_case_35(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_35(_Config) ->
    ?assertMatch(
        {ok, <<"1:13: Could not parse expression with swc: Expression expected (mdx:swc)"/utf8>>},
        markdown:to_html_with_options(<<"<a {...?} />"/utf8>>, ?swc),
        "should crash on an incorrect spread"
    ),
    ok.

-spec test_mdx_expression_flow_case_36(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_36(_Config) ->
    ?assertMatch(
        {ok,
            <<"1:5: Unexpected prop in spread (such as `{x}`): only a spread is supported (such as `{...x}`) (mdx:swc)"/utf8>>},
        markdown:to_html_with_options(<<"<a {b=c}={} d>"/utf8>>, ?swc),
        "should crash on an incorrect spread that looks like an assignment"
    ),
    ok.

-spec test_mdx_expression_flow_case_37(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_37(_Config) ->
    ?assertMatch(
        {ok,
            <<"1:5: Unexpected extra content in spread (such as `{...x,y}`): only a single spread is supported (such as `{...x}`) (mdx:swc)"/utf8>>},
        markdown:to_html_with_options(<<"<a {...b,c} d>"/utf8>>, ?swc),
        "should crash if a spread and other things"
    ),
    ok.

-spec test_mdx_expression_flow_case_38(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_38(_Config) ->
    ?assertMatch(
        {ok, <<"1:12: Could not parse expression with swc: assignment property is invalid syntax (mdx:swc)"/utf8>>},
        markdown:to_html_with_options(<<"<a {b=c} />"/utf8>>, ?swc),
        "should crash if not an identifier"
    ),
    ok.

-spec test_mdx_expression_flow_case_39(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_39(_Config) ->
    %% Note: `erlang-markdown` has no `allowEmpty`.
    ?assertMatch(
        {ok,
            <<"1:9: Unexpected prop in spread (such as `{x}`): only a spread is supported (such as `{...x}`) (mdx:swc)"/utf8>>},
        markdown:to_html_with_options(<<"<a {} />"/utf8>>, ?swc),
        "should crash on an empty spread"
    ),
    ok.

-spec test_mdx_expression_flow_case_40(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_mdx_expression_flow_case_40(_Config) ->
    ?assertMatch(
        {ok,
            <<"1:5: Unexpected prop in spread (such as `{x}`): only a spread is supported (such as `{...x}`) (mdx:swc)"/utf8>>},
        markdown:to_html_with_options(<<"<a {/* b */} />"/utf8>>, ?swc),
        "should crash on a comment spread"
    ),
    ok.
