%%% % DO NOT EDIT: this file was generated by 'just codegen'
%%% % @generated SignedSource<<fe191c705883d5fdc8a72060c3a6fe06>>
%%% % @format
%%%-----------------------------------------------------------------------------
%%% Copyright (c) Meta Platforms, Inc. and affiliates.
%%% Copyright (c) WhatsApp LLC
%%%
%%% This source code is licensed under the MIT license found in the
%%% LICENSE.md file in the root directory of this source tree.
%%%-----------------------------------------------------------------------------
-module(markdown_misc_soft_break_SUITE).
-moduledoc """

""".
-moduledoc #{author => ["Andrew Bennett <potatosaladx@meta.com>"]}.
-moduledoc #{created => "", modified => ""}.
-moduledoc #{copyright => "Meta Platforms, Inc. and affiliates."}.
-compile(warn_missing_spec_all).
-oncall("whatsapp_clr").

-include_lib("markdown/include/markdown_mdast.hrl").
-include_lib("markdown/include/markdown_util.hrl").
-include_lib("stdlib/include/assert.hrl").

-behaviour(ct_suite).

%% ct_suite callbacks
-export([
    all/0,
    groups/0,
    init_per_suite/1,
    end_per_suite/1,
    init_per_group/2,
    end_per_group/2
]).

%% Test Cases
-export([
    test_misc_soft_break_case_1/1,
    test_misc_soft_break_case_2/1
]).

%%%=============================================================================
%%% ct_suite callbacks
%%%=============================================================================

-spec all() -> markdown_test:all().
all() ->
    [
        {group, static}
    ].

-spec groups() -> markdown_test:groups().
groups() ->
    [
        {static, [parallel], [
            test_misc_soft_break_case_1,
            test_misc_soft_break_case_2
        ]}
    ].

-spec init_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:init_per_suite().
init_per_suite(Config) ->
    Config.

-spec end_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:end_per_suite().
end_per_suite(_Config) ->
    ok.

-spec init_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:init_per_group().
init_per_group(_Group, Config) ->
    Config.

-spec end_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:end_per_group().
end_per_group(_Group, _Config) ->
    ok.

%%%=============================================================================
%%% Test Cases
%%%=============================================================================

-spec test_misc_soft_break_case_1(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_soft_break_case_1(_Config) ->
    ?assertMatch(
        {ok, <<"<p>foo\nbaz</p>"/utf8>>},
        markdown:to_html(<<"foo\nbaz"/utf8>>),
        "should support line endings"
    ),
    ok.

-spec test_misc_soft_break_case_2(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_misc_soft_break_case_2(_Config) ->
    ?assertMatch(
        {ok, <<"<p>foo\nbaz</p>"/utf8>>},
        markdown:to_html(<<"foo \n baz"/utf8>>),
        "should trim spaces around line endings"
    ),
    ok.
