%%% % DO NOT EDIT: this file was generated by 'just codegen'
%%% % @generated SignedSource<<9311899f10c191e0ead1780f68098a77>>
%%% % @format
%%%-----------------------------------------------------------------------------
%%% Copyright (c) Meta Platforms, Inc. and affiliates.
%%% Copyright (c) WhatsApp LLC
%%%
%%% This source code is licensed under the MIT license found in the
%%% LICENSE.md file in the root directory of this source tree.
%%%-----------------------------------------------------------------------------
-module(markdown_heading_atx_SUITE).
-moduledoc """

""".
-moduledoc #{author => ["Andrew Bennett <potatosaladx@meta.com>"]}.
-moduledoc #{created => "", modified => ""}.
-moduledoc #{copyright => "Meta Platforms, Inc. and affiliates."}.
-compile(warn_missing_spec_all).
-oncall("whatsapp_clr").

-include_lib("markdown/include/markdown_mdast.hrl").
-include_lib("markdown/include/markdown_util.hrl").
-include_lib("stdlib/include/assert.hrl").

-behaviour(ct_suite).

%% ct_suite callbacks
-export([
    all/0,
    groups/0,
    init_per_suite/1,
    end_per_suite/1,
    init_per_group/2,
    end_per_group/2
]).

%% Test Cases
-export([
    test_heading_atx_case_1/1,
    test_heading_atx_case_2/1,
    test_heading_atx_case_3/1,
    test_heading_atx_case_4/1,
    test_heading_atx_case_5/1,
    test_heading_atx_case_6/1,
    test_heading_atx_case_7/1,
    test_heading_atx_case_8/1,
    test_heading_atx_case_9/1,
    test_heading_atx_case_10/1,
    test_heading_atx_case_11/1,
    test_heading_atx_case_12/1,
    test_heading_atx_case_13/1,
    test_heading_atx_case_14/1,
    test_heading_atx_case_15/1,
    test_heading_atx_case_16/1,
    test_heading_atx_case_17/1,
    test_heading_atx_case_18/1,
    test_heading_atx_case_19/1,
    test_heading_atx_case_20/1,
    test_heading_atx_case_21/1,
    test_heading_atx_case_22/1,
    test_heading_atx_case_23/1,
    test_heading_atx_case_24/1,
    test_heading_atx_case_25/1,
    test_heading_atx_case_26/1,
    test_heading_atx_case_27/1,
    test_heading_atx_case_28/1,
    test_heading_atx_case_29/1,
    test_heading_atx_case_30/1,
    test_heading_atx_case_31/1,
    test_heading_atx_case_32/1,
    test_heading_atx_case_33/1,
    test_heading_atx_case_34/1,
    test_heading_atx_case_35/1
]).

%%%=============================================================================
%%% ct_suite callbacks
%%%=============================================================================

-spec all() -> markdown_test:all().
all() ->
    [
        {group, static}
    ].

-spec groups() -> markdown_test:groups().
groups() ->
    [
        {static, [parallel], [
            test_heading_atx_case_1,
            test_heading_atx_case_2,
            test_heading_atx_case_3,
            test_heading_atx_case_4,
            test_heading_atx_case_5,
            test_heading_atx_case_6,
            test_heading_atx_case_7,
            test_heading_atx_case_8,
            test_heading_atx_case_9,
            test_heading_atx_case_10,
            test_heading_atx_case_11,
            test_heading_atx_case_12,
            test_heading_atx_case_13,
            test_heading_atx_case_14,
            test_heading_atx_case_15,
            test_heading_atx_case_16,
            test_heading_atx_case_17,
            test_heading_atx_case_18,
            test_heading_atx_case_19,
            test_heading_atx_case_20,
            test_heading_atx_case_21,
            test_heading_atx_case_22,
            test_heading_atx_case_23,
            test_heading_atx_case_24,
            test_heading_atx_case_25,
            test_heading_atx_case_26,
            test_heading_atx_case_27,
            test_heading_atx_case_28,
            test_heading_atx_case_29,
            test_heading_atx_case_30,
            test_heading_atx_case_31,
            test_heading_atx_case_32,
            test_heading_atx_case_33,
            test_heading_atx_case_34,
            test_heading_atx_case_35
        ]}
    ].

-spec init_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:init_per_suite().
init_per_suite(Config) ->
    Config.

-spec end_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:end_per_suite().
end_per_suite(_Config) ->
    ok.

-spec init_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:init_per_group().
init_per_group(_Group, Config) ->
    Config.

-spec end_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:end_per_group().
end_per_group(_Group, _Config) ->
    ok.

%%%=============================================================================
%%% Test Cases
%%%=============================================================================

-spec test_heading_atx_case_1(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_1(_Config) ->
    ?assertMatch(
        {ok, <<"<h1>foo</h1>"/utf8>>},
        markdown:to_html(<<"# foo"/utf8>>),
        "should support a heading w/ rank 1"
    ),
    ok.

-spec test_heading_atx_case_2(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_2(_Config) ->
    ?assertMatch(
        {ok, <<"<h2>foo</h2>"/utf8>>},
        markdown:to_html(<<"## foo"/utf8>>),
        "should support a heading w/ rank 2"
    ),
    ok.

-spec test_heading_atx_case_3(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_3(_Config) ->
    ?assertMatch(
        {ok, <<"<h3>foo</h3>"/utf8>>},
        markdown:to_html(<<"### foo"/utf8>>),
        "should support a heading w/ rank 3"
    ),
    ok.

-spec test_heading_atx_case_4(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_4(_Config) ->
    ?assertMatch(
        {ok, <<"<h4>foo</h4>"/utf8>>},
        markdown:to_html(<<"#### foo"/utf8>>),
        "should support a heading w/ rank 4"
    ),
    ok.

-spec test_heading_atx_case_5(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_5(_Config) ->
    ?assertMatch(
        {ok, <<"<h5>foo</h5>"/utf8>>},
        markdown:to_html(<<"##### foo"/utf8>>),
        "should support a heading w/ rank 5"
    ),
    ok.

-spec test_heading_atx_case_6(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_6(_Config) ->
    ?assertMatch(
        {ok, <<"<h6>foo</h6>"/utf8>>},
        markdown:to_html(<<"###### foo"/utf8>>),
        "should support a heading w/ rank 6"
    ),
    ok.

-spec test_heading_atx_case_7(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_7(_Config) ->
    ?assertMatch(
        {ok, <<"<p>####### foo</p>"/utf8>>},
        markdown:to_html(<<"####### foo"/utf8>>),
        "should not support a heading w/ rank 7"
    ),
    ok.

-spec test_heading_atx_case_8(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_8(_Config) ->
    ?assertMatch(
        {ok, <<"<p>#5 bolt</p>"/utf8>>},
        markdown:to_html(<<"#5 bolt"/utf8>>),
        "should not support a heading for a number sign not followed by whitespace (1)"
    ),
    ok.

-spec test_heading_atx_case_9(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_9(_Config) ->
    ?assertMatch(
        {ok, <<"<p>#hashtag</p>"/utf8>>},
        markdown:to_html(<<"#hashtag"/utf8>>),
        "should not support a heading for a number sign not followed by whitespace (2)"
    ),
    ok.

-spec test_heading_atx_case_10(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_10(_Config) ->
    ?assertMatch(
        {ok, <<"<p>## foo</p>"/utf8>>},
        markdown:to_html(<<"\\## foo"/utf8>>),
        "should not support a heading for an escaped number sign"
    ),
    ok.

-spec test_heading_atx_case_11(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_11(_Config) ->
    ?assertMatch(
        {ok, <<"<h1>foo <em>bar</em> *baz*</h1>"/utf8>>},
        markdown:to_html(<<"# foo *bar* \\*baz\\*"/utf8>>),
        "should support text content in headings"
    ),
    ok.

-spec test_heading_atx_case_12(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_12(_Config) ->
    ?assertMatch(
        {ok, <<"<h1>foo</h1>"/utf8>>},
        markdown:to_html(<<"#                  foo                     "/utf8>>),
        "should support arbitrary initial and final whitespace"
    ),
    ok.

-spec test_heading_atx_case_13(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_13(_Config) ->
    ?assertMatch(
        {ok, <<"<h3>foo</h3>"/utf8>>},
        markdown:to_html(<<" ### foo"/utf8>>),
        "should support an initial space"
    ),
    ok.

-spec test_heading_atx_case_14(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_14(_Config) ->
    ?assertMatch(
        {ok, <<"<h2>foo</h2>"/utf8>>},
        markdown:to_html(<<"  ## foo"/utf8>>),
        "should support two initial spaces"
    ),
    ok.

-spec test_heading_atx_case_15(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_15(_Config) ->
    ?assertMatch(
        {ok, <<"<h1>foo</h1>"/utf8>>},
        markdown:to_html(<<"   # foo"/utf8>>),
        "should support three initial spaces"
    ),
    ok.

-spec test_heading_atx_case_16(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_16(_Config) ->
    ?assertMatch(
        {ok, <<"<pre><code># foo\n</code></pre>"/utf8>>},
        markdown:to_html(<<"    # foo"/utf8>>),
        "should not support four initial spaces"
    ),
    ok.

-spec test_heading_atx_case_17(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_17(_Config) ->
    ?assertMatch(
        {ok, <<"<p>foo\n# bar</p>"/utf8>>},
        markdown:to_html(<<"foo\n    # bar"/utf8>>),
        "should not support four initial spaces when interrupting"
    ),
    ok.

-spec test_heading_atx_case_18(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_18(_Config) ->
    ?assertMatch(
        {ok, <<"<h2>foo</h2>"/utf8>>},
        markdown:to_html(<<"## foo ##"/utf8>>),
        "should support a closing sequence (1)"
    ),
    ok.

-spec test_heading_atx_case_19(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_19(_Config) ->
    ?assertMatch(
        {ok, <<"<h3>bar</h3>"/utf8>>},
        markdown:to_html(<<"  ###   bar    ###"/utf8>>),
        "should support a closing sequence (2)"
    ),
    ok.

-spec test_heading_atx_case_20(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_20(_Config) ->
    ?assertMatch(
        {ok, <<"<h1>foo</h1>"/utf8>>},
        markdown:to_html(<<"# foo ##################################"/utf8>>),
        "should support a closing sequence w/ an arbitrary number of number signs (1)"
    ),
    ok.

-spec test_heading_atx_case_21(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_21(_Config) ->
    ?assertMatch(
        {ok, <<"<h5>foo</h5>"/utf8>>},
        markdown:to_html(<<"##### foo ##"/utf8>>),
        "should support a closing sequence w/ an arbitrary number of number signs (2)"
    ),
    ok.

-spec test_heading_atx_case_22(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_22(_Config) ->
    ?assertMatch(
        {ok, <<"<h3>foo</h3>"/utf8>>},
        markdown:to_html(<<"### foo ###     "/utf8>>),
        "should support trailing whitespace after a closing sequence"
    ),
    ok.

-spec test_heading_atx_case_23(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_23(_Config) ->
    ?assertMatch(
        {ok, <<"<h3>foo ### b</h3>"/utf8>>},
        markdown:to_html(<<"### foo ### b"/utf8>>),
        "should not support other content after a closing sequence"
    ),
    ok.

-spec test_heading_atx_case_24(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_24(_Config) ->
    ?assertMatch(
        {ok, <<"<h1>foo#</h1>"/utf8>>},
        markdown:to_html(<<"# foo#"/utf8>>),
        "should not support a closing sequence w/o whitespace before it"
    ),
    ok.

-spec test_heading_atx_case_25(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_25(_Config) ->
    ?assertMatch(
        {ok, <<"<h3>foo ###</h3>"/utf8>>},
        markdown:to_html(<<"### foo \\###"/utf8>>),
        "should not support an “escaped” closing sequence (1)"
    ),
    ok.

-spec test_heading_atx_case_26(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_26(_Config) ->
    ?assertMatch(
        {ok, <<"<h2>foo ###</h2>"/utf8>>},
        markdown:to_html(<<"## foo #\\##"/utf8>>),
        "should not support an “escaped” closing sequence (2)"
    ),
    ok.

-spec test_heading_atx_case_27(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_27(_Config) ->
    ?assertMatch(
        {ok, <<"<h1>foo #</h1>"/utf8>>},
        markdown:to_html(<<"# foo \\#"/utf8>>),
        "should not support an “escaped” closing sequence (3)"
    ),
    ok.

-spec test_heading_atx_case_28(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_28(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />\n<h2>foo</h2>\n<hr />"/utf8>>},
        markdown:to_html(<<"****\n## foo\n****"/utf8>>),
        "should support atx headings when not surrounded by blank lines"
    ),
    ok.

-spec test_heading_atx_case_29(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_29(_Config) ->
    ?assertMatch(
        {ok, <<"<p>Foo bar</p>\n<h1>baz</h1>\n<p>Bar foo</p>"/utf8>>},
        markdown:to_html(<<"Foo bar\n# baz\nBar foo"/utf8>>),
        "should support atx headings interrupting paragraphs"
    ),
    ok.

-spec test_heading_atx_case_30(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_30(_Config) ->
    ?assertMatch(
        {ok, <<"<h2></h2>\n<h1></h1>\n<h3></h3>"/utf8>>},
        markdown:to_html(<<"## \n#\n### ###"/utf8>>),
        "should support empty atx headings (1)"
    ),
    ok.

-spec test_heading_atx_case_31(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_31(_Config) ->
    ?assertMatch(
        {ok, <<"<h1></h1>\n<p>a</p>\n<h1>b</h1>"/utf8>>},
        markdown:to_html(<<"#\na\n# b"/utf8>>),
        "should support empty atx headings (2)"
    ),
    ok.

-spec test_heading_atx_case_32(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_32(_Config) ->
    ?assertMatch(
        {ok, <<"<blockquote>\n<h1></h1>\n</blockquote>\n<p>a</p>"/utf8>>},
        markdown:to_html(<<"> #\na"/utf8>>),
        "should not support lazyness (1)"
    ),
    ok.

-spec test_heading_atx_case_33(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_33(_Config) ->
    ?assertMatch(
        {ok, <<"<blockquote>\n<p>a</p>\n</blockquote>\n<h1></h1>"/utf8>>},
        markdown:to_html(<<"> a\n#"/utf8>>),
        "should not support lazyness (2)"
    ),
    ok.

-spec test_heading_atx_case_34(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_34(_Config) ->
    ?assertMatch(
        {ok, <<"<p># a</p>"/utf8>>},
        markdown:to_html_with_options(
            <<"# a"/utf8>>, markdown_options:default(#{parse => #{constructs => #{heading_atx => false}}})
        ),
        "should support turning off heading (atx)"
    ),
    ok.

-spec test_heading_atx_case_35(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_heading_atx_case_35(_Config) ->
    ?assertEqual(
        {ok,
            markdown_mdast_node:root(#markdown_mdast_root{
                children = ?'vec!'([
                    markdown_mdast_node:heading(#markdown_mdast_heading{
                        depth = 2,
                        children = ?'vec!'([
                            markdown_mdast_node:text(#markdown_mdast_text{
                                value = <<"alpha">>,
                                position = {some, markdown_unist_position:new(1, 4, 3, 1, 9, 8)}
                            })
                        ]),
                        position = {some, markdown_unist_position:new(1, 1, 0, 1, 11, 10)}
                    })
                ]),
                position = {some, markdown_unist_position:new(1, 1, 0, 1, 11, 10)}
            })},
        markdown:to_mdast(<<"## alpha #"/utf8>>, markdown_parse_options:default()),
        "should support heading (atx) as `Heading`s in mdast"
    ),
    ok.
