%%% % DO NOT EDIT: this file was generated by 'just codegen'
%%% % @generated SignedSource<<8de62ed5577c04b3e47aacbcc428513f>>
%%%-----------------------------------------------------------------------------
%%% %CopyrightBegin%
%%%
%%% SPDX-License-Identifier: Apache-2.0
%%%
%%% Copyright (c) Meta Platforms, Inc. and affiliates.
%%% Copyright (c) WhatsApp LLC
%%%
%%% Licensed under the Apache License, Version 2.0 (the "License");
%%% you may not use this file except in compliance with the License.
%%% You may obtain a copy of the License at
%%%
%%%     http://www.apache.org/licenses/LICENSE-2.0
%%%
%%% Unless required by applicable law or agreed to in writing, software
%%% distributed under the License is distributed on an "AS IS" BASIS,
%%% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
%%% See the License for the specific language governing permissions and
%%% limitations under the License.
%%%
%%% %CopyrightEnd%
%%%-----------------------------------------------------------------------------
%%% % @format
-module(markdown_hard_break_trailing_SUITE).
-moduledoc """

""".
-moduledoc #{author => ["Andrew Bennett <potatosaladx@meta.com>"]}.
-moduledoc #{created => "", modified => ""}.
-moduledoc #{copyright => "Meta Platforms, Inc. and affiliates."}.
-compile(warn_missing_spec_all).
-oncall("whatsapp_clr").

-include_lib("markdown/include/markdown_mdast.hrl").
-include_lib("markdown/include/markdown_util.hrl").
-include_lib("stdlib/include/assert.hrl").

-behaviour(ct_suite).

%% ct_suite callbacks
-export([
    all/0,
    groups/0,
    init_per_suite/1,
    end_per_suite/1,
    init_per_group/2,
    end_per_group/2
]).

%% Test Cases
-export([
    test_hard_break_trailing_case_1/1,
    test_hard_break_trailing_case_2/1,
    test_hard_break_trailing_case_3/1,
    test_hard_break_trailing_case_4/1,
    test_hard_break_trailing_case_5/1,
    test_hard_break_trailing_case_6/1,
    test_hard_break_trailing_case_7/1,
    test_hard_break_trailing_case_8/1,
    test_hard_break_trailing_case_9/1,
    test_hard_break_trailing_case_10/1,
    test_hard_break_trailing_case_11/1,
    test_hard_break_trailing_case_12/1,
    test_hard_break_trailing_case_13/1,
    test_hard_break_trailing_case_14/1,
    test_hard_break_trailing_case_15/1,
    test_hard_break_trailing_case_16/1,
    test_hard_break_trailing_case_17/1,
    test_hard_break_trailing_case_18/1,
    test_hard_break_trailing_case_19/1
]).

%%%=============================================================================
%%% ct_suite callbacks
%%%=============================================================================

-spec all() -> markdown_test:all().
all() ->
    [
        {group, static}
    ].

-spec groups() -> markdown_test:groups().
groups() ->
    [
        {static, [parallel], [
            test_hard_break_trailing_case_1,
            test_hard_break_trailing_case_2,
            test_hard_break_trailing_case_3,
            test_hard_break_trailing_case_4,
            test_hard_break_trailing_case_5,
            test_hard_break_trailing_case_6,
            test_hard_break_trailing_case_7,
            test_hard_break_trailing_case_8,
            test_hard_break_trailing_case_9,
            test_hard_break_trailing_case_10,
            test_hard_break_trailing_case_11,
            test_hard_break_trailing_case_12,
            test_hard_break_trailing_case_13,
            test_hard_break_trailing_case_14,
            test_hard_break_trailing_case_15,
            test_hard_break_trailing_case_16,
            test_hard_break_trailing_case_17,
            test_hard_break_trailing_case_18,
            test_hard_break_trailing_case_19
        ]}
    ].

-spec init_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:init_per_suite().
init_per_suite(Config) ->
    Config.

-spec end_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:end_per_suite().
end_per_suite(_Config) ->
    ok.

-spec init_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:init_per_group().
init_per_group(_Group, Config) ->
    Config.

-spec end_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:end_per_group().
end_per_group(_Group, _Config) ->
    ok.

%%%=============================================================================
%%% Test Cases
%%%=============================================================================

-spec test_hard_break_trailing_case_1(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_trailing_case_1(_Config) ->
    ?assertMatch(
        {ok, <<"<p>foo<br />\nbaz</p>"/utf8>>},
        markdown:to_html(<<"foo  \nbaz"/utf8>>),
        "should support two trailing spaces to form a hard break"
    ),
    ok.

-spec test_hard_break_trailing_case_2(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_trailing_case_2(_Config) ->
    ?assertMatch(
        {ok, <<"<p>foo<br />\nbaz</p>"/utf8>>},
        markdown:to_html(<<"foo       \nbaz"/utf8>>),
        "should support multiple trailing spaces"
    ),
    ok.

-spec test_hard_break_trailing_case_3(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_trailing_case_3(_Config) ->
    ?assertMatch(
        {ok, <<"<p>foo<br />\nbar</p>"/utf8>>},
        markdown:to_html(<<"foo  \n     bar"/utf8>>),
        "should support leading spaces after a trailing hard break"
    ),
    ok.

-spec test_hard_break_trailing_case_4(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_trailing_case_4(_Config) ->
    ?assertMatch(
        {ok, <<"<p><em>foo<br />\nbar</em></p>"/utf8>>},
        markdown:to_html(<<"*foo  \nbar*"/utf8>>),
        "should support trailing hard breaks in emphasis"
    ),
    ok.

-spec test_hard_break_trailing_case_5(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_trailing_case_5(_Config) ->
    ?assertMatch(
        {ok, <<"<p><code>code   text</code></p>"/utf8>>},
        markdown:to_html(<<"`code  \ntext`"/utf8>>),
        "should not support trailing hard breaks in code"
    ),
    ok.

-spec test_hard_break_trailing_case_6(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_trailing_case_6(_Config) ->
    ?assertMatch(
        {ok, <<"<p>foo</p>"/utf8>>},
        markdown:to_html(<<"foo  "/utf8>>),
        "should not support trailing hard breaks at the end of a paragraph"
    ),
    ok.

-spec test_hard_break_trailing_case_7(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_trailing_case_7(_Config) ->
    ?assertMatch(
        {ok, <<"<h3>foo</h3>"/utf8>>},
        markdown:to_html(<<"### foo  "/utf8>>),
        "should not support trailing hard breaks at the end of a heading"
    ),
    ok.

-spec test_hard_break_trailing_case_8(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_trailing_case_8(_Config) ->
    ?assertMatch(
        {ok, <<"<p>aaa\nbb</p>"/utf8>>},
        markdown:to_html(<<"aaa  \t\nbb"/utf8>>),
        "should support a mixed line suffix (1)"
    ),
    ok.

-spec test_hard_break_trailing_case_9(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_trailing_case_9(_Config) ->
    ?assertMatch(
        {ok, <<"<p>aaa\nbb</p>"/utf8>>},
        markdown:to_html(<<"aaa\t  \nbb"/utf8>>),
        "should support a mixed line suffix (2)"
    ),
    ok.

-spec test_hard_break_trailing_case_10(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_trailing_case_10(_Config) ->
    ?assertMatch(
        {ok, <<"<p>aaa\nbb</p>"/utf8>>},
        markdown:to_html(<<"aaa  \t  \nbb"/utf8>>),
        "should support a mixed line suffix (3)"
    ),
    ok.

-spec test_hard_break_trailing_case_11(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_trailing_case_11(_Config) ->
    ?assertMatch(
        {ok, <<"<p>aaa�<br />\nbb</p>"/utf8>>},
        markdown:to_html(<<"aaa\x00  \nbb"/utf8>>),
        "should support a hard break after a replacement character"
    ),
    ok.

-spec test_hard_break_trailing_case_12(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_trailing_case_12(_Config) ->
    ?assertMatch(
        {ok, <<"<p>aaa�\nbb</p>"/utf8>>},
        markdown:to_html(<<"aaa\x00\t\nbb"/utf8>>),
        "should support a line suffix after a replacement character"
    ),
    ok.

-spec test_hard_break_trailing_case_13(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_trailing_case_13(_Config) ->
    ?assertMatch(
        {ok, <<"<p><em>a</em><br />\nbb</p>"/utf8>>},
        markdown:to_html(<<"*a*  \nbb"/utf8>>),
        "should support a hard break after a span"
    ),
    ok.

-spec test_hard_break_trailing_case_14(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_trailing_case_14(_Config) ->
    ?assertMatch(
        {ok, <<"<p><em>a</em>\nbb</p>"/utf8>>},
        markdown:to_html(<<"*a*\t\nbb"/utf8>>),
        "should support a line suffix after a span"
    ),
    ok.

-spec test_hard_break_trailing_case_15(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_trailing_case_15(_Config) ->
    ?assertMatch(
        {ok, <<"<p><em>a</em>\nbb</p>"/utf8>>},
        markdown:to_html(<<"*a*  \t\nbb"/utf8>>),
        "should support a mixed line suffix after a span (1)"
    ),
    ok.

-spec test_hard_break_trailing_case_16(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_trailing_case_16(_Config) ->
    ?assertMatch(
        {ok, <<"<p><em>a</em>\nbb</p>"/utf8>>},
        markdown:to_html(<<"*a*\t  \nbb"/utf8>>),
        "should support a mixed line suffix after a span (2)"
    ),
    ok.

-spec test_hard_break_trailing_case_17(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_trailing_case_17(_Config) ->
    ?assertMatch(
        {ok, <<"<p><em>a</em>\nbb</p>"/utf8>>},
        markdown:to_html(<<"*a*  \t  \nbb"/utf8>>),
        "should support a mixed line suffix after a span (3)"
    ),
    ok.

-spec test_hard_break_trailing_case_18(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_trailing_case_18(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a\nb</p>"/utf8>>},
        markdown:to_html_with_options(
            <<"a  \nb"/utf8>>, markdown_options:default(#{parse => #{constructs => #{hard_break_trailing => false}}})
        ),
        "should support turning off hard break (trailing)"
    ),
    ok.

-spec test_hard_break_trailing_case_19(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_hard_break_trailing_case_19(_Config) ->
    ?assertEqual(
        {ok,
            markdown_mdast_node:root(#markdown_mdast_root{
                children = ?'vec!'([
                    markdown_mdast_node:paragraph(#markdown_mdast_paragraph{
                        children = ?'vec!'([
                            markdown_mdast_node:text(#markdown_mdast_text{
                                value = <<"a">>,
                                position = {some, markdown_unist_position:new(1, 1, 0, 1, 2, 1)}
                            }),
                            markdown_mdast_node:break(#markdown_mdast_break{
                                position = {some, markdown_unist_position:new(1, 2, 1, 2, 1, 4)}
                            }),
                            markdown_mdast_node:text(#markdown_mdast_text{
                                value = <<"b.">>,
                                position = {some, markdown_unist_position:new(2, 1, 4, 2, 3, 6)}
                            })
                        ]),
                        position = {some, markdown_unist_position:new(1, 1, 0, 2, 3, 6)}
                    })
                ]),
                position = {some, markdown_unist_position:new(1, 1, 0, 2, 3, 6)}
            })},
        markdown:to_mdast(<<"a  \nb."/utf8>>, markdown_parse_options:default()),
        "should support hard break (trailing) as `Break`s in mdast"
    ),
    ok.
