%%% % DO NOT EDIT: this file was generated by 'just codegen'
%%% % @generated SignedSource<<550c37c234a1ecdc35d80de4d044f1e2>>
%%% % @format
%%%-----------------------------------------------------------------------------
%%% Copyright (c) Meta Platforms, Inc. and affiliates.
%%% Copyright (c) WhatsApp LLC
%%%
%%% This source code is licensed under the MIT license found in the
%%% LICENSE.md file in the root directory of this source tree.
%%%-----------------------------------------------------------------------------
-module(markdown_frontmatter_SUITE).
-moduledoc """

""".
-moduledoc #{author => ["Andrew Bennett <potatosaladx@meta.com>"]}.
-moduledoc #{created => "", modified => ""}.
-moduledoc #{copyright => "Meta Platforms, Inc. and affiliates."}.
-compile(warn_missing_spec_all).
-oncall("whatsapp_clr").

-include_lib("markdown/include/markdown_mdast.hrl").
-include_lib("markdown/include/markdown_util.hrl").
-include_lib("stdlib/include/assert.hrl").

-behaviour(ct_suite).

%% ct_suite callbacks
-export([
    all/0,
    groups/0,
    init_per_suite/1,
    end_per_suite/1,
    init_per_group/2,
    end_per_group/2
]).

%% Test Cases
-export([
    test_frontmatter_case_1/1,
    test_frontmatter_case_2/1,
    test_frontmatter_case_3/1,
    test_frontmatter_case_4/1,
    test_frontmatter_case_5/1,
    test_frontmatter_case_6/1,
    test_frontmatter_case_7/1,
    test_frontmatter_case_8/1,
    test_frontmatter_case_9/1,
    test_frontmatter_case_10/1,
    test_frontmatter_case_11/1,
    test_frontmatter_case_12/1,
    test_frontmatter_case_13/1,
    test_frontmatter_case_14/1,
    test_frontmatter_case_15/1,
    test_frontmatter_case_16/1,
    test_frontmatter_case_17/1,
    test_frontmatter_case_18/1,
    test_frontmatter_case_19/1,
    test_frontmatter_case_20/1,
    test_frontmatter_case_21/1,
    test_frontmatter_case_22/1
]).

%% Macros
-define(frontmatter, markdown_options:new(#{parse => #{constructs => #{frontmatter => true}}})).
-define(frontmatter_parse, markdown_parse_options:new(#{constructs => #{frontmatter => true}})).

%%%=============================================================================
%%% ct_suite callbacks
%%%=============================================================================

-spec all() -> markdown_test:all().
all() ->
    [
        {group, static}
    ].

-spec groups() -> markdown_test:groups().
groups() ->
    [
        {static, [parallel], [
            test_frontmatter_case_1,
            test_frontmatter_case_2,
            test_frontmatter_case_3,
            test_frontmatter_case_4,
            test_frontmatter_case_5,
            test_frontmatter_case_6,
            test_frontmatter_case_7,
            test_frontmatter_case_8,
            test_frontmatter_case_9,
            test_frontmatter_case_10,
            test_frontmatter_case_11,
            test_frontmatter_case_12,
            test_frontmatter_case_13,
            test_frontmatter_case_14,
            test_frontmatter_case_15,
            test_frontmatter_case_16,
            test_frontmatter_case_17,
            test_frontmatter_case_18,
            test_frontmatter_case_19,
            test_frontmatter_case_20,
            test_frontmatter_case_21,
            test_frontmatter_case_22
        ]}
    ].

-spec init_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:init_per_suite().
init_per_suite(Config) ->
    Config.

-spec end_per_suite(Config :: ct_suite:ct_config()) -> markdown_test:end_per_suite().
end_per_suite(_Config) ->
    ok.

-spec init_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:init_per_group().
init_per_group(_Group, Config) ->
    Config.

-spec end_per_group(GroupName :: ct_suite:ct_groupname(), Config :: ct_suite:ct_config()) ->
    markdown_test:end_per_group().
end_per_group(_Group, _Config) ->
    ok.

%%%=============================================================================
%%% Test Cases
%%%=============================================================================

-spec test_frontmatter_case_1(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_frontmatter_case_1(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />\n<h2>title: Jupyter</h2>"/utf8>>},
        markdown:to_html(<<"---\ntitle: Jupyter\n---"/utf8>>),
        "should not support frontmatter by default"
    ),
    ok.

-spec test_frontmatter_case_2(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_frontmatter_case_2(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"---\ntitle: Jupyter\n---"/utf8>>, ?frontmatter),
        "should support frontmatter (yaml)"
    ),
    ok.

-spec test_frontmatter_case_3(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_frontmatter_case_3(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"+++\ntitle = \"Jupyter\"\n+++"/utf8>>, ?frontmatter),
        "should support frontmatter (toml)"
    ),
    ok.

-spec test_frontmatter_case_4(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_frontmatter_case_4(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"---\n---"/utf8>>, ?frontmatter),
        "should support empty frontmatter"
    ),
    ok.

-spec test_frontmatter_case_5(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_frontmatter_case_5(_Config) ->
    ?assertMatch(
        {ok, <<"<h2>--</h2>"/utf8>>},
        markdown:to_html_with_options(<<"--\n---"/utf8>>, ?frontmatter),
        "should not support 2 markers in an opening fence"
    ),
    ok.

-spec test_frontmatter_case_6(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_frontmatter_case_6(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />\n<hr />"/utf8>>},
        markdown:to_html_with_options(<<"----\n---"/utf8>>, ?frontmatter),
        "should not support 4 markers in an opening fence"
    ),
    ok.

-spec test_frontmatter_case_7(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_frontmatter_case_7(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />\n<p>--</p>"/utf8>>},
        markdown:to_html_with_options(<<"---\n--"/utf8>>, ?frontmatter),
        "should not support 2 markers in a closing fence"
    ),
    ok.

-spec test_frontmatter_case_8(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_frontmatter_case_8(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />\n<p>--</p>\n"/utf8>>},
        markdown:to_html_with_options(<<"---\n--\n"/utf8>>, ?frontmatter),
        "should not panic if newline after 2 marker closing fence"
    ),
    ok.

-spec test_frontmatter_case_9(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_frontmatter_case_9(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />\n<hr />"/utf8>>},
        markdown:to_html_with_options(<<"---\n----"/utf8>>, ?frontmatter),
        "should not support 4 markers in a closing fence"
    ),
    ok.

-spec test_frontmatter_case_10(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_frontmatter_case_10(_Config) ->
    ?assertMatch(
        {ok, <<"<h2>Neptune</h2>"/utf8>>},
        markdown:to_html_with_options(<<"---\n---\n## Neptune"/utf8>>, ?frontmatter),
        "should support content after frontmatter"
    ),
    ok.

-spec test_frontmatter_case_11(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_frontmatter_case_11(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"--- \t\n---"/utf8>>, ?frontmatter),
        "should support spaces and tabs after opening fence"
    ),
    ok.

-spec test_frontmatter_case_12(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_frontmatter_case_12(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"---\n---\t "/utf8>>, ?frontmatter),
        "should support spaces and tabs after closing fence"
    ),
    ok.

-spec test_frontmatter_case_13(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_frontmatter_case_13(_Config) ->
    ?assertMatch(
        {ok, <<"<p>a\nb</p>"/utf8>>},
        markdown:to_html_with_options(<<"---\n---\na\nb"/utf8>>, ?frontmatter),
        "should support line endings after frontmatter"
    ),
    ok.

-spec test_frontmatter_case_14(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_frontmatter_case_14(_Config) ->
    ?assertMatch(
        {ok, <<"<h2>--- a</h2>"/utf8>>},
        markdown:to_html_with_options(<<"--- a\n---"/utf8>>, ?frontmatter),
        "should not support content after opening fence"
    ),
    ok.

-spec test_frontmatter_case_15(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_frontmatter_case_15(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />\n<p>--- b</p>"/utf8>>},
        markdown:to_html_with_options(<<"---\n--- b"/utf8>>, ?frontmatter),
        "should not support content after closing fence"
    ),
    ok.

-spec test_frontmatter_case_16(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_frontmatter_case_16(_Config) ->
    ?assertMatch(
        {ok, <<"<h2>Neptune</h2>\n<hr />\n<hr />"/utf8>>},
        markdown:to_html_with_options(<<"## Neptune\n---\n---"/utf8>>, ?frontmatter),
        "should not support frontmatter after content"
    ),
    ok.

-spec test_frontmatter_case_17(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_frontmatter_case_17(_Config) ->
    ?assertMatch(
        {ok, <<"<blockquote>\n<hr />\n<hr />\n<h2>Neptune</h2>\n</blockquote>"/utf8>>},
        markdown:to_html_with_options(<<"> ---\n> ---\n> ## Neptune"/utf8>>, ?frontmatter),
        "should not support frontmatter in a container"
    ),
    ok.

-spec test_frontmatter_case_18(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_frontmatter_case_18(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />"/utf8>>},
        markdown:to_html_with_options(<<"---"/utf8>>, ?frontmatter),
        "should not support just an opening fence"
    ),
    ok.

-spec test_frontmatter_case_19(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_frontmatter_case_19(_Config) ->
    ?assertMatch(
        {ok, <<"<hr />\n<p>title: Neptune</p>"/utf8>>},
        markdown:to_html_with_options(<<"---\ntitle: Neptune"/utf8>>, ?frontmatter),
        "should not support a missing closing fence"
    ),
    ok.

-spec test_frontmatter_case_20(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_frontmatter_case_20(_Config) ->
    ?assertMatch(
        {ok, <<""/utf8>>},
        markdown:to_html_with_options(<<"---\na\n\nb\n \t\nc\n---"/utf8>>, ?frontmatter),
        "should support blank lines in frontmatter"
    ),
    ok.

-spec test_frontmatter_case_21(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_frontmatter_case_21(_Config) ->
    ?assertEqual(
        {ok,
            markdown_mdast_node:root(#markdown_mdast_root{
                children = ?'vec!'([
                    markdown_mdast_node:yaml(#markdown_mdast_yaml{
                        value = <<"a: b">>,
                        position = {some, markdown_unist_position:new(1, 1, 0, 3, 4, 12)}
                    })
                ]),
                position = {some, markdown_unist_position:new(1, 1, 0, 3, 4, 12)}
            })},
        markdown:to_mdast(<<"---\na: b\n---"/utf8>>, ?frontmatter_parse),
        "should support yaml as `Yaml`s in mdast"
    ),
    ok.

-spec test_frontmatter_case_22(Config) -> markdown_test:testcase() when
    Config :: ct_suite:ct_config().
test_frontmatter_case_22(_Config) ->
    ?assertEqual(
        {ok,
            markdown_mdast_node:root(#markdown_mdast_root{
                children = ?'vec!'([
                    markdown_mdast_node:toml(#markdown_mdast_toml{
                        value = <<"title = \"Jupyter\"">>,
                        position = {some, markdown_unist_position:new(1, 1, 0, 3, 4, 25)}
                    })
                ]),
                position = {some, markdown_unist_position:new(1, 1, 0, 3, 4, 25)}
            })},
        markdown:to_mdast(<<"+++\ntitle = \"Jupyter\"\n+++"/utf8>>, ?frontmatter_parse),
        "should support toml as `Toml`s in mdast"
    ),
    ok.
